### ISSUE TITLE
purescript-halogen-ace

### ISSUE THREAD

**Issue by puffnfresh** [slamdata/purescript-halogen#102]
I'm integrating purescript-ace into SlamData, which uses Halogen. I'm mostly extracting relevant parts of the Ace example. I think it would be useful to extract it into a subproject of this repo.

**Comment by jdegoes** [comment]
Phil may be working on this, careful!

**Comment by paf31** [comment]
No, not yet. I was hoping to get a list of requirements first:

https://github.com/slamdata/purescript-halogen/issues/100
