### ISSUE TITLE
Question about components

### ISSUE THREAD

**Issue by archaeron** [slamdata/purescript-halogen#103]
If this is the wrong time in the release cycle to ask a question, please feel free to close it.

I wanted to try to create a small chat with halogen.
The chat consists essentially of a list of users and a list of messages from a certain user (depending on what user you clicked on in the list of users).

What I did in my first try was making a large component and that worked.

Then I thought: the list of the users only needs as an input a list of online users and should return the user you clicked on.
So something like:
```haskell
usersComponent :: forall p m. (Applicative m) => Component p m [Users] User
```

The messages component should take a user and return messages of that user
```haskell
messagesComponent :: forall p m. (Applicative m) => Component p m User Message
```

is this a bad idea?

I'm getting into trouble combining the two components, because `runUI` wants the input and the return type to be the same.

**Comment by paf31** [comment]
I wouldn't focus too much on components for now, since there is a change they will go away soon (#99). In terms of signal functions, you need something of type

```
SF1 input (HTML p (m input))
```

and the type `input` is the type of input (and output) messages from your component. Usually, I would expect this to be a sum type, representing the things which the user can do in your UI, or external inputs:

```
data Input = LoadUserList | UserClicked UserID | ...
```

**Comment by archaeron** [comment]
Would that sum type consist of all the actions on the whole application?
Wouldn't that quickly grow out of proportions?

I tried using the components, because I'd have hoped there would be a chance to build an application from a collection of smaller parts and only let the whole application see the events that it needs to function, without worrying about the inner events of a smaller part.

**Comment by paf31** [comment]
> Wouldn't that quickly grow out of proportions?

Yes, but there are techniques to manage the complexity: lenses/prisms for one. Component takes a different approach, by hiding parts of the sum inside an existential type.

The main issue with `Component` is that it is difficult to compose.

**Comment by archaeron** [comment]
Yes, they felt hard to work with :)

Is there somewhere a writeup about how to work with this complexity?
That would be really interesting. Otherwise I'll close the issue and wait for future of halogen.

Thanks for your work on this and your help.

**Comment by paf31** [comment]
> Is there somewhere a writeup about how to work with this complexity?

Right now, it's sort of "active research" :)

You might like to join #purescript IRC, there are some other users there, with the same sorts of questions.

**Comment by jdegoes** [comment]
> I'd have hoped there would be a chance to build an application from a collection of smaller parts and only let the whole application see the events that it needs to function

Not possible right now, basically you cannot throw away information right now so every single little detail about any jot or comma in any part of your application will bubble up to the top. This makes composition painful and verbose, although it does have benefits in reproducibility and control.

But like @paf31 says, it's an open topic and we're researching it. :smile:

**Comment by archaeron** [comment]
Thank you for your answers.
I'm so excited about these new ways of writing functional UIs :)

I know Elm is a bit of a competitor, but I read something about mailboxes here: http://elm-lang.org/blog/announce/0.15.elm, that seem to be a way of handling this.

I like purescript as a language more though, so I'm eagerly waiting for more news in this repo.
Thanks again!

**Comment by archaeron** [comment]
I'd like to help, if you need any.
But probably I'm not capable of helping you with the code directly.
I'm working on the chat in this repo: https://github.com/archaeron/chatty-web-client-halogen
What I could do is work on it some more and then write up what I found difficult to do.
Would this help?
