### ISSUE TITLE
Change representation of Attributes

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#111]
`Attr` has a complex representation, and doesn't offer any real type safety. We would get just as much type safety if we used an `Any` type and hid the implementation behind smart constructors.

Alternatively, we could represent `Attr` as a large sum type, but that would make it more difficult to support new attributes.

**Comment by jdegoes** [comment]
I'm not sure what I think about this, but I definitely agree that `Attr` is messy as it stands. What problem would this solve, or does it more fall in the order of cleaning things up?

**Comment by paf31** [comment]
It's just about cleaning up the code.

**Comment by garyb** [comment]
Closing as things have changed a little since this issue was raised (although we're still essentially using the same formulation for `Prop` which is the new `Attr`).
