### ISSUE TITLE
the 9 lives of components

### ISSUE THREAD

**Issue by jdegoes** [slamdata/purescript-halogen#112]
Was chatting to @puffnfresh about pre-0.5 component ideas, and we agreed to post this on the project page in case we want to further develop or refer to it.

```purescript
-- | p   - placeholder / address of a particular widget
-- | m   - the type of effects of the component
-- | req - requests (passing info to component)
-- | res - responses (passing info out of component)
-- | s   - state of the component
-- | i   - the internal type of events generated / consumed

type ComponentI p m req res s i = { 
  current :: s, 
  render  :: s -> HTML p i, 
  handle  :: Either i req -> m (Either res (s -> s)) }

type Component p m req res = exists s i. ComponentI p m req res

install :: forall ...
  Component p m (Either req (Tuple p res')) (Either res (Tuple p req')) -> 
  (p -> Maybe (Component p' m req' res')) -> 
  Component (Either p p') m req res

installAll :: forall ...
  Component p m (Either req (Tuple p res')) (Either res (Tuple p req')) -> 
  (p -> Component p' m req' res') -> 
  Component p' m req res
```

**Comment by puffnfresh** [comment]
The `install` specifically is what I was wanting a few days ago. The `p -> Maybe (Component p m req res)` is exactly what I wanted, I tried implementing it but the existential made it impossible.

**Comment by paf31** [comment]
Doesn't this have the same problems with existentials that we had before?

**Comment by puffnfresh** [comment]
@paf31 yeah, I'm totally unsold on that part.

**Comment by jdegoes** [comment]
@paf31 What problems does this one have? i.e. is there some function which cannot be implemented?

**Comment by paf31** [comment]
Here are the problems I'm referring to:

- we couldn't implement things like `Applicative`, `Strong`, or `Choice`. All we had was `Profunctor` which made composition very difficult.
- widgets could be added using placeholders, but we couldn't query the internal structure of components, and we had to resort to hacks to make sure updates got applied correctly.
- the existential type made it impossible to implement `install` in a type-safe way.

I'm not saying we can't implement these things now, but the implementations certainly aren't obvious to me - It's hard to figure out how things are supposed to work from only type signatures.

**Comment by jdegoes** [comment]
> we couldn't implement things like Applicative, Strong, or Choice. All we had was Profunctor which made composition very difficult.

That's with the old busted black-hole of a component, which could leak information only through HTML. This one is quite different, and forms `Applicative` for sure in `res`, not sure about the other ones.

> widgets could be added using placeholders, but we couldn't query the internal structure of components, and we had to resort to hacks to make sure updates got applied correctly.

This one separates the rendering function from the state updating function, which should clean this up quite a bit.

> the existential type made it impossible to implement install in a type-safe way.

Existential is not necessary in this definition, it's just for convenience. Pretty sure `install` can be implemented and willing to give it a try pending the above 2 points.

**Comment by paf31** [comment]
> This one is quite different, and forms Applicative for sure in res

If it's the one I'm thinking of, is it a sensible `Applicative`? If you have `ComponentI p m req (a -> b) s i` and `ComponentI p m req a s i`, the first can respond with either an `a -> b` or an `s -> s`, and similarly the second can respond with either an `a` or an `s -> s`. Two of the four combinations have obvious implementations for `<*>`, but in the other two, you end up discarding at least one response.

> This one separates the rendering function from the state updating function, which should clean this up quite a bit.

But you still have to use a `widget` to render, which means you run into the same "stale input"/versioning issue we had previously. Also, what is `m` in the case of a widget. If it's not `Eff` or something similar, you won't be able to interrogate the internal state of the widget (unless you cram the whole state into `s`), and then we're back to stateful signal functions.

Also, something seems wrong about the type of `install` - I don't see where the various combinations of requests get routed to.

**Comment by jdegoes** [comment]
> Two of the four combinations have obvious implementations for <*>, but in the other two, you end up discarding at least one response.

I think you just need some constraint on `m` to solve this (something like MonadEvent).

> But you still have to use a widget to render, 

I'm not so much interested in cramming this into vdom as figuring out if the type signatures make sense and permit the use cases we want. I would at least grant the above isn't fully baked for foreign components, but the core thing I would personally want from a foreign component is this:

```purescript
req -> m res
```

You could imagine a sum type for component that allows pure components or effectful widgets, but both end up being unified to the above, which you can compose with `Profunctor`, `Applicative`, etc.

> then we're back to stateful signal functions.

Well, effectful components, with effects tracked by `m`, and yeah, for echarts or ace, those effects would be pretty comprehensive, but there'd still be a lot of polymorphic pure code / components. You can't really eliminate these effects, you can just push them around, pushing them to the top makes for a lot of really hideous imperative code that's hard to reason about. A notion of component lets you still have tons of pure code but also reason about the composition between effectful and pure code, and tie them together in a somewhat declarative fashion.

> Also, something seems wrong about the type of install - I don't see where the various combinations of requests get routed to.

Let me break it down, I am probably missing something:

```purescript
Component p m (Either req (Tuple p res')) (Either res (Tuple p req'))
```

The parent component either accepts a `req` from higher up, or gets a response `res'` from a child `p`. The parent component either returns a `res` higher up, or issues a request `req'` to a child `p`.

Note various constraints may be missing (e.g. `Eq` on `p`, etc.).

```purescript
(p -> Maybe (Component p' m req' res')) -> 
```

The installer function, which takes a `p` and maybe installs a child component. The child component has placeholders `p'` (maybe `Void`), accepts requests `req'`, and responds with `res'`.

```purescript
Component (Either p p') m req res
```

The installed component has placeholders `p` or `p'` (but see `installAll`), and accepts `req` and returns `res`. Internally the implementation uses a `Map` to manage children state (map from `p` to its individual child states). It probably uses attributes or something to detect cases where creation of children is necessary. Not sure exactly how that would work efficiently yet.

**Comment by jdegoes** [comment]
@paf31 It does have problems, namely you can't prove to the compiler that a child component's state / input types are actually valid. I would argue it can be proved by hand and that only a small amount of 'unsafe' code would be necessary.

That said, it may be unnecessary as an alternate formulation may end up working just as well, just have to work on it some more. TBD.

On the whole widget thing, if `Attr`'s initializers / finalizers were passed `Node` and could generate `m i`, well then, installation of a foreign widget and destruction could happen entirely in PureScript code with mostly the above signatures. 

I'll work on this more tomorrow, not sure if it'll go anywhere.

**Comment by jdegoes** [comment]
Subsumed by #138
