### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by yemi** [slamdata/purescript-halogen#119]
Liking how the library looks like and still have to play around some more but I have a question regarding server side rendering: 

Is it possible, with a python/django backend to render the halogen app and let the frontend pick the components up from there? Asking for something similar to Reacts' `renderComponentToString`

Im asking because lately about django specifically because thats what we use and not too long ago i found out about https://github.com/markfinger/python-react and I'm looking for more Purescript "pros" to switch our frontend to Purescript :)

**Comment by paf31** [comment]
You can render a component as a String, if that's what you need:

https://github.com/slamdata/purescript-halogen/blob/master/src/Halogen/HTML/Renderer/String.purs#L26

Which part would be running in PureScript?

**Comment by yemi** [comment]
Cool! And probably not the whole site but rather parts of the site, like form pages, profile page and other kinds of interactive pages

**Comment by yemi** [comment]
So, more on a widget kind of level rather than creating a SPA
