### ISSUE TITLE
Provide a separate template project

### ISSUE THREAD

**Issue by epost** [slamdata/purescript-halogen#127]
Going from seeing a Halogen presentation to compiling and running a Hello World seems a bit more finnicky that it should. I think it would be immensely valuable to be able to clone a project containing all the right deps and a build script (preferably based on pulp and perhaps one or two lines of bash...) so people can start tinkering right away. The examples and readme in this repo help somewhat, but they're not exactly plug and play, and there seems to be some discrepancy between master and release versions.

**Comment by jdegoes** [comment]
:+1:

**Comment by epost** [comment]
I was after something like this: https://github.com/parsonsmatt/purs-architecture-tutorial. Just thought I'd mention it here for future reference.

**Comment by mchaver** [comment]
Hmm, I am having this problem as well. It seems strange that the examples are dependent on the parent's build script. The examples shows me how to get started with Halogen, but I am still left wondering how to setup a new project that uses Halogen.

**Comment by marcoalkema** [comment]
+1 for raising this issue. Having trouble with this as well.

**Comment by garyb** [comment]
Sorry, this has been starred and hovering around the top of my inbox for months now, I'll get it done.

**Comment by marcoalkema** [comment]
Thanks Gary! Awesome quick respond!

**Comment by garyb** [comment]
Done at last! https://github.com/slamdata/purescript-halogen-template

Please open any issues or problems you have relating to it on the repo over there. I hope it helps!

**Comment by epost** [comment]
Gary, you're totally awesome! :D Thanks so much!
