### ISSUE TITLE
Is the ClassName newtype necessary?

### ISSUE THREAD

**Issue by hansler** [slamdata/purescript-halogen#130]
In src/Halogen/HTML/Attributes.purs, ClassName is defined:

    -- | A wrapper for strings which are used as CSS classes
    newtype ClassName = ClassName String

    -- Create a class name
    className :: String -> ClassName
    className = ClassName

    -- | Unpack a class name
    runClassName :: ClassName -> String
    runClassName (ClassName s) = s

Along with the following functions:

    class_ :: forall i. ClassName -> Attr i
    class_ = attr (attributeName "className") <<< runClassName

    classes :: forall i. [ClassName] -> Attr i
    classes ss = attr (attributeName "className") (joinWith " " $ map runClassName ss)

Why is this? I've just started playing around with Halogen the last couple days, but I'm already finding it tedious to read & write HTML templates because of this. For example, I end up with code like:

    [ ul [ classes [ className "side-nav", className "dark-side-nav", className "collapsable-nav" ]]
         [ li [ classes [ className "dropdown", className "dropdown-user", className "dropdown-dark" ]]
              [ a [ class_ (className "dropdown-switch")]]
                  [ ... ]
              ]
         ]
    ]

Why not treat classes like most of the other attributes and just use strings? E.g.:

    class_ :: forall i. String -> Attr i
    class_ = attr $ attributeName "className"

Unless I'm missing something, there would be nothing lost here, and it would make writing the HTML templates much quicker. My example code above would instead be able to be written as:

    [ ul [ classes [ "side-nav", "dark-side-nav", "collapsable-nav" ]]
         [ li [ classes [ "dropdown", "dropdown-user", "dropdown-dark" ]]
              [ a [ class_ "dropdown-switch" ]]
                  [ ... ]
              ]
         ]
    ]

(Note: This doesn't really bother me personally, since I can just make my own modified class_ and classes functions for my projects, but I thought it might make Halogen more  friendly for those that work with other designers or pre-existing CSS templates.)

**Comment by puffnfresh** [comment]
Here's how we've use the type:

https://github.com/slamdata/slamdata/blob/master/src/View/Css.purs

I think it has worked out well for us.

**Comment by esad** [comment]
Just stumbled upon this myself. This is really inconsistent compared to other attributes (`id`, `name` etc.) and offers no benefit over simple strings.

**Comment by garyb** [comment]
Good point, but probably the wrong way from what you intended: I think that those should have newtypes also :wink:.

There is an advantage to having the newtype: it makes it slightly harder to mix up values of different categories; by which I mean like using an `id` where a `class` should go, etc.
