### ISSUE TITLE
Provide a way to maintain separate state for components

### ISSUE THREAD

**Issue by puffnfresh** [slamdata/purescript-halogen#137]
In slamdata/slamdata we have lots of Ace components and we need to maintain sessions for each one. We use this type:

```purescript
type AceSessions = M.Map CellId EditSession
```

And create an empty map in a RefVal in main, which is passed to the Ace postRender hook, which then maintains it.

It would be great if Halogen could create and help maintain the map without the need for creating and passing around a RefVal.

**Comment by jdegoes** [comment]
Addressed by #138 (children components installed into a parent have their state maintained automatically and without the need for refs).
