### ISSUE TITLE
Provide HTTP example which works

### ISSUE THREAD

**Issue by beckyconning** [slamdata/purescript-halogen#139]
The provided HTTP example doesn't work without disabling CORS. This can be very disconcerting for new users as immediately it looks as if Halogen's HTTP capacity doesn't work.

**Comment by jdegoes** [comment]
:+1: Should change the example to use a site supporting CORS so it works out of the box.

**Comment by paf31** [comment]
Try PureScript does use CORS.

**Comment by beckyconning** [comment]
It doesn't accept all domains though.

**Comment by paf31** [comment]
Which domain doesn't work for you?

**Comment by beckyconning** [comment]
Localhost

**Comment by paf31** [comment]
You're running Try PureScript on localhost, or the example?

If I open the file from the filesystem in Chrome, and use the default `try.purescript.org` endpoint, everything works fine. CORS headers are enabled for `try.purescript.org` in nginx.

What browser are you using?

**Comment by philderbeast** [comment]
When running the halogen ajax example from the filesystem in chrome on windows, the origin is null and the server responds with a 403.

```
POST /compile/text HTTP/1.1
Host: try.purescript.org
Connection: keep-alive
Content-Length: 166
Pragma: no-cache
Cache-Control: no-cache
Origin: null
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```

**Comment by garyb** [comment]
We should probably just switch the example to use some public API that has `Access-Control-Allow-Origin: *`.

**Comment by philderbeast** [comment]
When I run the example with http-server, origin is localhost. Likewise the server gives a 403 response.

```
Origin:http://localhost:8080
```
