### ISSUE TITLE
Wrap Bootstrap

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#14]
- Forms: 
  - [x] input groups
  - [ ] buttons
  - [x] triggering disabling/enabling, ```has-success```, ```has-warning``` etc 
- [x] navbars
- [ ] list groups
- [x] breadcrumbs.

**Comment by jdegoes** [comment]
:+1: Foundation and maybe others too over time. `Halogen.Themes` or something?

**Comment by paf31** [comment]
I started working on a library of class names, but I'd like to support whole components (navbar, dropdown buttons, button groups, etc.) in a strongly-typed way. If you have any preference for which of those I look at first, just let me know.

**Comment by jdegoes** [comment]
^^^ @cryogenian

**Comment by cryogenian** [comment]
Please, make the following features at first:
* Forms: 
  - input groups
  - buttons
  - triggering disabling/enabling, ```has-success```, ```has-warning``` etc 
* navbars
* list groups
* breadcrumbs.

Thank you!

**Comment by paf31** [comment]
Very helpful, thanks!

**Comment by paf31** [comment]
I made a bit of progress on this, and I'll try to work on some more components later in the week.

**Comment by jdegoes** [comment]
@cryogenian If you need more from bootstrap, just implement the minimum amount needed, I will push this ticket back for now.

**Comment by paf31** [comment]
Shall we move these issues to `halogen-bootstrap`?

**Comment by jdegoes** [comment]
> Shall we move these issues to halogen-bootstrap?

:+1:
