### ISSUE TITLE
Add type for size value attributes

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#141]
Something like:
``` purescript
data Size = Pixels Number | Percent Number
```

Unfortunately a more general one for CSS including `em` sizes and the like wouldn't work here, as `width` and `height` attributes only support numbers and numbers followed by %.

**Comment by garyb** [comment]
(Of course, using CSS is the better way, but there are some things that don't behave correctly unless sized with attributes - `canvas` for example, `iframe` in older browsers).

**Comment by jdegoes** [comment]
:+1:

**Comment by jonsterling** [comment]
Resolved by #172
