### ISSUE TITLE
Example of component composition

### ISSUE THREAD

**Issue by timbod7** [slamdata/purescript-halogen#142]
I'm looking for example code for component composition. From the readme:

> The Ace editor example demonstrates how components can be composed

The ace example has the following comment:

```
-- | Using `combine` and `mapP` and some `Profunctor` trickery, we can make the types
-- | match what is required by `runUI`.
-- |
-- | `combine` takes a function which renders two `HTML` elements side-by-side, and
-- | combines the `Component`s, taking the sum of the input types.
```

Yet doesn't seem to actually call `combine` or `mapP`. Is this demo no longer intended as a composition example?

**Comment by jdegoes** [comment]
That's right. We'll update this when we decide on the new architecture for components. Existing version has some issues with composition.
