### ISSUE TITLE
new-components: investigate a placeholder addressing scheme that uses Exists

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#149]
I'm not sure if this would work yet, it occurred to me it might be worth looking into while on the train today - the idea being that we could simplify some types with component containers, and instead wrap up the child component states etc. using `Exists`.

I'll try and come up with a real example once I'm done with the current component issues.

**Comment by garyb** [comment]
A sample of what it would be nice to avoid: 

`ui :: forall g. (Monad g, Plus g) => Component (InstalledState State TickState (FreeC TickInput) TickPlaceholder Void g) (Coproduct (FreeC Input) (ChildF TickPlaceholder (FreeC TickInput))) g Void`

And this is only installing one type of child component :smile:

**Comment by jdegoes** [comment]
Every time we tried to hide state existentially, we ended up with composition problems. That said, this is a different design, so who knows.

I do think that type synonyms and / or newtypes will help a lot with this. If I build `AceCell`, for example, then I can wrap up its state in a synonym / newtype `AceState`, which of course includes `InstalledState ...` etc.i.e. every component that's not "polymorphic" in its placeholders, but which binds them to concrete components, can wrap up its state so the complexity of the type signatures remains relatively flat as you work your way up the application.

That still leaves the cascading complexity of the composite query DSLs. Obviously type synonyms can help here for self-contained components, but what would really help are infix types. e.g. some sort of XPath-like notation for `ChildF`: `AceCell // ControlCell // EditorCell //: AceDSL`.

**Comment by garyb** [comment]
> Every time we tried to hide state existentially, we ended up with composition problems.

Yeah, that's my worry too. The types for what I have in mind might not work out anyway, it's pretty handwavey right now, so I'll try and reason it out once the other component and widget related changes are in.

**Comment by garyb** [comment]
I explored this route a bit, I think there's potential, but some things still need figuring out.

The basic gist was you'd have a monad that can generate keys/symbols for component _types_. Something like this:

``` purescript
-- These would have hidden constructors:
newtype ComponentKey s (f :: * -> *) g (o :: * -> *) p = ComponentKey (ComponentKeyValue Int)
newtype ComponentKeyValue (g :: * -> *) p = ComponentKeyValue Int

-- And only be producible by the following functions:
componentKey :: ComponentP s f g o p -> M ComponentKey s f g o p
keyValue :: ComponentKey s f g o p -> ComponentKeyValue g p
```

Then, in `children` the map would become two dimensional:
``` purescript
type Children g p = M.Map (ComponentKeyValue g p) (M.Map p (ComponentStateE g p))
```

And you'd create a lookup like:
``` purescript
lookup :: Children g p -> ComponentKey s f g o p -> p -> ComponentState s f g o p
```

Where we use an unsafe coercion to get from `ComponentStateE g p` to `ComponentState s f g o p` - this would be known to be safe, as the only way to get a `ComponentKeyValue g p` value for a component type is from the `componentKey` function.

The main problem with this approach is it means you're stuck in `M` for the entire app, and I haven't fully figured out the the consequences of multiple layers of nesting. Peeking would need some work again too.

**Comment by jdegoes** [comment]
I'm not a huge fan of this. But I'm still thinking about possible ways of simplifying the types (beyond type aliases / newtypes which really only work well for fully installed components).

**Comment by garyb** [comment]
Yeah, that's the unfortunate thing with using synonyms in the current scheme. At least the types are quite a bit simpler now we don't use or need `Free`/`FreeC`/`Coyoneda` for the query algebras, I think that helps a lot when trying to read a composite component type signature.

**Comment by garyb** [comment]
I'm not a huge fan of this approach either by the way, just thought I'd record where I got to with one harebrained attempt :smile:

**Comment by garyb** [comment]
Closing this, as I don't think it's going to happen now - or not for 0.5 at least. The set of type synonyms we arrived at eventually keep the types fairly reasonable, and introducing new type synonyms when dealing with highly nested children can keep the noise down also.
