### ISSUE TITLE
Support 'thunk' from virtual-dom

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#15]
It would be nice to be able to use `SF` to handle this somehow.

Ideally I would like to use an `Eq s` instance to generate appropriate calls to `thunk`.

**Comment by jdegoes** [comment]
Our use cases include `purescript-ace`, `purescript-echarts`, and probably others. Having a modular, clean, and robust way of using these pre-built DOM-native components is quite important.

**Comment by paf31** [comment]
The simplest approach seems to be something like adding a new constructor to `HTML` which prevents redraws using `thunk`:

```purescript
data HTML i
  = NoRedraw (Unit -> HTML i)
  | Text ...
```

We could then extend that in some simple way, like adding a `String` identifier which could be stuck in a `data-` attribute and used to implement limited updates:

```purescript
type Hash = String

data HTML i
  = Hashed String (Unit -> HTML i)
  | Text ...
```

If the hashes are equal, we assume the `VTree`s are equal and use the previous `VTree`. Otherwise, we rerender the `HTML` structure.

**Comment by paf31** [comment]
Also, @jdegoes, I'm not a `vdom` expert yet, but I feel like the "widget" concept might be useful for the examples you mentioned. I'll write up a separate issue for that.

https://github.com/Matt-Esch/virtual-dom/blob/master/docs/widget.md

**Comment by garyb** [comment]
I'd agree with that, `thunk` is for custom patching logic, `widget` is more for things like Ace.
