### ISSUE TITLE
new-components: widget init function needs a way of being able to deal with event listeners

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#150]
The current formulation of widgets is just using `Intializer` and `Finalizer` to do much of the work, but that's not good enough as we can't add event-listenery-things in the widget init function. For example, the Ace example needs this to be able to send `TextCopied` and `TextChanged` inputs to itself.

So it seems widgets will need their own representation in `HTML` after all, unfortunately, as to link things up like this we need to pass the driver through so there is some way of sending inputs back into the state machine.

**Comment by jdegoes** [comment]
> So it seems widgets will need their own representation in HTML after all, unfortunately, as to link things up like this we need to pass the driver through so there is some way of sending inputs back into the state machine.

What about something like:

```
...
Initializer (HTMLElement -> Eff _ ((f Unit -> Eff _ Unit) -> Eff _ Unit)) |
Finalizer (HTMLElement -> Eff _ ((f Unit -> Eff _ Unit) -> Eff _ Unit))
```

Or more generally, with the ability to not just add event listeners to the DOM, but also emit an action for the query processor.

I think something much nicer is possible, with much greater unification potential, but it requires rethinking how event listeners are described — the above would be a short-term workaround.

**Comment by garyb** [comment]
Yeah, I think something like that might be what I end up with for now. I'm just finishing up some work on a basic installed-components example that doesn't require the widget interface, so I'll be back on it after that.

**Comment by garyb** [comment]
I started making these issues as the tasks I'm working on were starting to multiply and I didn't want to forget where I was up to :smile:

**Comment by garyb** [comment]
59feac25b9c3ab7130d62378ad00f0c07fdf6335
