### ISSUE TITLE
break out purescript-css support into purescript-halogen-css?

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#153]
Perhaps we should do this, as it's not a requirement for Halogen to function, and can be built without any "internal knowledge".

**Comment by garyb** [comment]
@jdegoes if you're in favour of this can you make a repo for it please?

**Comment by jdegoes** [comment]
I'm in favor, you should also be able to create repos now. :) Make it a public repo and add the engineering team to it.

**Comment by garyb** [comment]
Ah cool! I was able to make it okay, but looks like an Owner will have to change the permissions on it - I don't have the option to give Engineering access.

**Comment by garyb** [comment]
Closing now the module has been moved over to the new repo.
