### ISSUE TITLE
`main` might start before the dom loaded

### ISSUE THREAD

**Issue by zudov** [slamdata/purescript-halogen#156]
After the https://github.com/slamdata/purescript-halogen/commit/068faf3732b42171643d8516be3cb8e0a53d53a1 I started experiencing a problem when the app compiles and starts, but nothing gets attached to the `<body>`, it happens with examples and with my app.

With some debugging I found out that when `appendToBody`, is trying to attach the element to body, the body doesn't yet exist. As a crude way to test it, I made a binding to `window.onload` and wrapped my `main` into it. After that the problem dissapeared.

It's hard to say whether that's a problem in halogen, but we might at least fix the examples and put some form of "onload" in there.

Even better would be to improve the `appendToBody` shortcut and wait for `onload` in there.

At the moment `appendToBody`  silently returns when the body isn't found. We certainly should report the error somehow. We may either just print an error message, or fail the thing entirely.

**Comment by zudov** [comment]
Moving the <script> to the end of the document also fixes the problem, but I am not sure how stable that is.

**Comment by garyb** [comment]
That latter solution is fine, it's the best way to ensure things fire as soon as possible without blocking the page from loading like having `<script>` in the head does... I don't think it's the fix we should rely on though. I'll make `appendToBody` wait for `onload`.
