### ISSUE TITLE
Style property on elements

### ISSUE THREAD

**Issue by yemi** [slamdata/purescript-halogen#161]
Is there a reason why there isn't a `style` function in `Halogen.HTML.Properties`? 
Would like to do add some css to the element based on state.

**Comment by garyb** [comment]
`style` is defined in `purescript-halogen-css`... or would be if I had pushed anything to that repository! I'll fix it now.

**Comment by garyb** [comment]
It's [there now](https://github.com/slamdata/purescript-halogen-css), and I've made an initial release that is compatible with Halogen master.

**Comment by yemi** [comment]
Nice, thanks!
