### ISSUE TITLE
The example-todo fails with 'Cannot export unknown module Halogen.HTML.Core'

### ISSUE THREAD

**Issue by philderbeast** [slamdata/purescript-halogen#163]
With an OS of windows 2012 server, I did a fresh clone of this repo, followed the instructions for building the examples ...

    git clone https://github.com/slamdata/purescript-halogen.git
    cd purescript-halogen
    npm install
    npm run example-todo

I got the error ...

    Cannot export unknown module Halogen.HTML.Core, it either does not exist or has not been imported by the current module

**Comment by philderbeast** [comment]
The contents of npm-debug.log ...

    1 info it worked if it ends with ok
    1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
    1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'run',
    1 verbose cli   'example-todo' ]
    2 info using npm@1.4.23
    3 info using node@v0.10.31
    4 verbose node symlink C:\Program Files\nodejs\\node.exe
    5 verbose run-script [ 'preexample-todo', 'example-todo', 'postexample-todo' ]
    6 info preexample-todo purescript-halogen@
    7 info example-todo purescript-halogen@
    8 verbose unsafe-perm in lifecycle true
    9 info purescript-halogen@ Failed to exec example-todo script
    10 error purescript-halogen@ example-todo: `bower link && cd examples/todo && bower link purescript-halogen && gulp`
    10 error Exit status 1
    11 error Failed at the purescript-halogen@ example-todo script.
    11 error This is most likely a problem with the purescript-halogen package,
    11 error not with npm itself.
    11 error Tell the author that this fails on your system:
    11 error     bower link && cd examples/todo && bower link purescript-halogen && gulp
    11 error You can get their info via:
    11 error     npm owner ls purescript-halogen
    11 error There is likely additional logging output above.
    12 error System Windows_NT 6.2.9200
    13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "example-todo"
    14 error cwd e:\Dev\Src\slamdata\purescript-halogen
    15 error node -v v0.10.31
    16 error npm -v 1.4.23
    17 error code ELIFECYCLE
    18 verbose exit [ 1, true ]

**Comment by philderbeast** [comment]
The command line ..

    e:\Dev\Src\slamdata\purescript-halogen>npm run example-todo

    > purescript-halogen@ example-todo e:\Dev\Src\slamdata\purescript-halogen
    > bower link && cd examples/todo && bower link purescript-halogen && gulp

    bower                    link C:\Users\pdejoux\AppData\Local\bower\data\links\purescript-halogen > e:\Dev\Src\slamdata\purescript-halogen
    bower purescript-aff-coroutines#^0.2.0           cached git://github.com/paf31/purescript-aff-coroutines.git#0.2.1
    bower purescript-aff-coroutines#^0.2.0         validate 0.2.1 against git://github.com/paf31/purescript-aff-coroutines.git#^0.2.0
    bower purescript-free#^0.7.0                     cached git://github.com/purescript/purescript-free.git#0.7.0
    bower purescript-free#^0.7.0                   validate 0.7.0 against git://github.com/purescript/purescript-free.git#^0.7.0
    bower purescript-const#^0.5.0                    cached git://github.com/mankyKitty/purescript-const.git#0.5.0
    bower purescript-const#^0.5.0                  validate 0.5.0 against git://github.com/mankyKitty/purescript-const.git#^0.5.0
    bower purescript-dom#^0.2.3                      cached git://github.com/joneshf/purescript-dom.git#0.2.6
    bower purescript-dom#^0.2.3                    validate 0.2.6 against git://github.com/joneshf/purescript-dom.git#^0.2.3
    bower purescript-foreign#^0.7.0                  cached git://github.com/purescript/purescript-foreign.git#0.7.0
    bower purescript-foreign#^0.7.0                validate 0.7.0 against git://github.com/purescript/purescript-foreign.git#^0.7.0
    bower purescript-nullable#^0.2.0                 cached git://github.com/paf31/purescript-nullable.git#0.2.1
    bower purescript-nullable#^0.2.0               validate 0.2.1 against git://github.com/paf31/purescript-nullable.git#^0.2.0
    bower purescript-unsafe-coerce#^0.1.0            cached git://github.com/purescript-contrib/purescript-unsafe-coerce.git#0.1.0
    bower purescript-unsafe-coerce#^0.1.0          validate 0.1.0 against git://github.com/purescript-contrib/purescript-unsafe-coerce.git#^0.1.0
    bower purescript-maps#^0.5.0                     cached git://github.com/purescript/purescript-maps.git#0.5.0
    bower purescript-maps#^0.5.0                   validate 0.5.0 against git://github.com/purescript/purescript-maps.git#^0.5.0
    bower purescript-void#^0.3.0                     cached git://github.com/joneshf/purescript-void.git#0.3.0
    bower purescript-void#^0.3.0                   validate 0.3.0 against git://github.com/joneshf/purescript-void.git#^0.3.0
    bower                                     link e:\Dev\Src\slamdata\purescript-halogen\examples\todo\bower_components\purescript-halogen > C:\Users\pdejoux\AppData\Local\bower\data\
    links\purescript-halogen
    [00:46:16] Using gulpfile e:\Dev\Src\slamdata\purescript-halogen\examples\todo\gulpfile.js
    [00:46:16] Starting 'make'...
    [00:46:17] 'make' errored after 1.32 s
    [00:46:17] Error: Error found:
    Error in module Halogen.HTML:
    Cannot export unknown module Halogen.HTML.Core, it either does not exist or has not been imported by the current module
    See https://github.com/purescript/purescript/wiki/Error-Code-UnknownExportModule for more information, or to contribute content related to this error.


        at ChildProcess.<anonymous> (e:\Dev\Src\slamdata\purescript-halogen\node_modules\gulp-purescript\index.js:7428:32)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:756:16)
        at Process.ChildProcess._handle.onexit (child_process.js:823:5)

    npm ERR! purescript-halogen@ example-todo: `bower link && cd examples/todo && bower link purescript-halogen && gulp`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the purescript-halogen@ example-todo script.
    npm ERR! This is most likely a problem with the purescript-halogen package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     bower link && cd examples/todo && bower link purescript-halogen && gulp
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls purescript-halogen
    npm ERR! There is likely additional logging output above.
    npm ERR! System Windows_NT 6.2.9200
    npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "example-todo"
    npm ERR! cwd e:\Dev\Src\slamdata\purescript-halogen
    npm ERR! node -v v0.10.31
    npm ERR! npm -v 1.4.23
    npm ERR! code ELIFECYCLE
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     e:\Dev\Src\slamdata\purescript-halogen\npm-debug.log
    npm ERR! not ok code 0

**Comment by garyb** [comment]
Thanks for reporting. This repo will be updated with the fix soon, but in the meantime please take a look at #162 for a workaround, or switch to the branch mentioned in there.

**Comment by philderbeast** [comment]
Thanks for the quick response. Running of the branch works for me.
