### ISSUE TITLE
New component with multiple types of child components

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#167]
I'm playing around with halogen's new components and got stuck where I want to install different types of child components into the same parent component.

Basically, I have three state and input types for the children, but the `ParentComponent` and `InstalledComponent` type aliases only allow me to specify one type of children state and input, respectively.

Is there a pattern for these kinds of situations that you had in mind?

**Comment by garyb** [comment]
This is what #166 is attempting to address :)

**Comment by themoritz** [comment]
Ah I missed that PR :) Also thanks for the example in there!

**Comment by garyb** [comment]
I'm hoping to have it wrapped up and merged soon, the PR as it is does work but there are a few things I want to take another look at regarding the types variables used for `peek` and the like, as even though I wrote it I don't fully understand the implications of the composition setup when peeking is also desired :wink:

**Comment by themoritz** [comment]
Ok, I'm curious to see how it will turn out! Really looking forward to migrating our project to the new components version.
