### ISSUE TITLE
Halogen performance (and new components)

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#168]
I modified the components (ticker) example to show a grid of tickers. It turned out that for a 30x30 grid, increasing the counter of one ticker takes about 2s because every time (I guess?) the whole app is re-rendered.

I'm not very familiar with the internal workings of halogen, but my intuition was that if I only modify the local state of a component's child, I don't need to re-render the whole component.

In general, I'm wondering what I can expect performance-wise when using halogen as compared to similar UI frameworks (e.g., React).

The code can be found here:
https://github.com/themoritz/halogen-components-performance

**Comment by jdegoes** [comment]
Halogen is definitely not optimized. The parent components know when their children change state, so it should be possible to be _very smart_ about caching the views. Currently that's not done.

Beyond just view caching, I'm sure general profiling & optimization could increase performance by at least 10x.

**Comment by garyb** [comment]
It certainly shouldn't be re-rendering the whole DOM, as Halogen is backed by `virtual-dom` which operates on the same principle as React... so yeah, I guess it must be the internal rendering that is currently not smart. Caching of child components should be quite easy to implement so I'll definitely take a look at this once the composition PR is resolved.

Thanks for constructing the handy example too!

**Comment by themoritz** [comment]
That makes sense. I think overall halogen performance is not a big concern, but the reconstruction of the whole virtual-dom after every input is what's causing our current project to be quite laggy.

Unfortunately at the moment I don't have the resources to look into caching myself. When would you estimate to have time working on this (given your other priorities)?

**Comment by garyb** [comment]
Sorry I didn't get back to you about this earlier... I'm looking into it now though :)

**Comment by kristianmandrup** [comment]
I guess this one can be closed now due to #173 ?

**Comment by garyb** [comment]
Almost! The performance is significantly better, but I want to make some improvements to the internal `virtual-dom` rendering, so I'll close this once that is done too - as I mentioned in the other issue, this will be a post-release patch though as it won't affect the API.

**Comment by garyb** [comment]
#196 eliminated the state monad from `virtual-dom`'s rendering so that should further improve the performance.

The next version of halogen may have its own layer of diffing when rendering HTML to virtual-dom, but for 0.5.x the obvious improvements are now complete.

**Comment by themoritz** [comment]
I just checked out the performance of version 0.12, and I'm impressed. Lag in the 30x30 grid is virtually unnoticable, and with 2400 cells it's still totally fine to work with it. Amazing work guys!
