### ISSUE TITLE
Invesigate replacing initialize/finalize attributes with a "lifecycle widget"

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#170]
From @natefaubion:

> I was browsing halogen, and noticed how initializers/finalizers are attributes. Would it make sense to have a virtual dom widget that can handle these cases, and they just return the inner dom on init? so to control initialize and finalize, you have a widget that takes both as a param, plus the inner virtual-dom. then when it mounts, it doesn’t actually create a new element it just assembles the inner virtual-dom and runs the initializer? 
>
> or another way to put it, when you need to control the lifecycle, you wrap it in a widget that controls that cycle for a section of the dom, instead of adding attributes to any arbitrary element

This potentially lets us eliminate the need for the memoization key for these init/final attributes too.

**Comment by garyb** [comment]
@natefaubion I did look at squeezing the last thing in as part of 0.5 but I think I need just a little more time to figure out how best to do it. I'd _really_ like to be able to get rid of the key property that we use with the initializers/finalizers currently too, and not have to just move it up to the widget... I can almost see a way through it, although it might depend on some more changes we're considering for maybe 0.6 (diffing `HTML` as well as using virtual dom). There's also maybe something in using a slot address as the key rather than just a string...

**Comment by natefaubion** [comment]
@garyb in my experiments, just changing the hooks to this worked great and eliminated the need for a key.

```js
function InitHook(f) {
  this.f = f;
}

InitHook.prototype = {
  hook: function(node, prop, previous) {
    if (typeof previous === 'undefined') {
      this.f(node)();
    }
  }
};

function FinalHook(f) {
  this.f = f;
}

FinalHook.prototype = {
  unhook: function(node, prop, next) {
    if (typeof next === 'undefined') {
      this.f(node)();
    }
  }
}

// jshint maxparams: 1
exports.initProp = function (f) {
  return { "halogen-init": new InitHook(f) };
};

exports.finalizerProp = function (f) {
  return { "halogen-final": new FinalHook(f) };
};
```

I'd be happy to work up a PR.

**Comment by garyb** [comment]
Ah interesting, yeah if you get a chance at some point I'd like to see that.

**Comment by garyb** [comment]
#280
