### ISSUE TITLE
What is the timeframe for 0.7 release

### ISSUE THREAD

**Issue by kristianmandrup** [slamdata/purescript-halogen#177]
Just curious. Trying to learn PureScript taking some time as well... lots to grasp.
Looks like most the architecture discussion is pretty settled and looks very promising!!
What about all the missing sections on the main Readme?
Cheers!!

**Comment by garyb** [comment]
The Readme is the last thing that needs updating before making the release, I should be done with that on Monday. There may be a few patch releases after that to improve performance, but the types and “external” API are all set now. :)

**Comment by kristianmandrup** [comment]
Excellent!! Thanks :)
