### ISSUE TITLE
Persist child state (or access state during install)

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-halogen#180]
What is the best way to persist child state, even when a particular slot isn't active? I'm thinking of the tabs use case, where you swap out a slot based on the currently active tab, but you want to persist state between tabs. I know you could do this by hiding tabs with CSS, but then everything is being rendered all the time.

Right now, if you were to swap out say 3 installed components based on a tab, the state is reset each time. If you want to persist that state, I'd think you have to move it into the parent state when swapping (so you'd query the child for its state). But you don't have access to the current state when installing, so you have no way of getting the old state when you swap it back in. The only thing I can think of is to put the state of the component into the slot, so you can thread it through when rendering (this seems problematic). Would it make sense to just give the installer access to the current state?

**Comment by garyb** [comment]
Hmm, yeah, we definitely don't offer an easy way of doing this currently. Does the installer need access to the current state? An action on the parent will be required to modify its state to reintroduce the slot for the child, so can we not reassign the state there? I can see why that might not work - the child may not exist yet so we can't modify its state, but I haven't checked whether that's the case.

Threading through the slot works but I agree it's not a good idea, mainly as it becomes confusing.

**Comment by garyb** [comment]
Actually, the first thing I suggested almost certainly won't work - rendering would have to happen for the child installer to run, and one of the optimisations I added was to not render after every state modification.

Passing the current state to the installer is not a problem though, maybe that is the best answer to this. Any objections @jdegoes?

**Comment by natefaubion** [comment]
> Threading through the slot works but I agree it's not a good idea, mainly as it becomes confusing.

I've just found that this makes it very difficult to query child components (you'd have to provide bogus params just to run it), so this is definitely a no go :)

**Comment by garyb** [comment]
Yeah, that too! Unless you define a dodgy `Eq` that only considers one part of the constructor.

**Comment by garyb** [comment]
Using an `initializer` would be another option potentially, but... yuck.

**Comment by natefaubion** [comment]
Demo request: generic tab component that runs the other demos in each tab, with the parameters of this issue :P

**Comment by jdegoes** [comment]
@garyb Not sure what you mean by 'passing the current state to the installer'.

Can, for example, each child state have a flag, `isActive`, and just renders empty DOM if it's not active? Then the parent only has to set the `isActive` state of the currently active child component.

**Comment by garyb** [comment]
@jdegoes I mean currently our `install` is typed:

``` purescript
install :: forall s s' f f' g p p'. (Plus g, Ord p)
        => ParentComponent s s' f f' g p p'
        -> (p -> ChildState s' f' g p')
        -> InstalledComponent s s' f f' g p p'
```

The suggestion is to modify it to:

``` purescript
install :: forall s s' f f' g p p'. (Plus g, Ord p)
        => ParentComponent s s' f f' g p p'
        -> (s -> p -> ChildState s' f' g p')
        -> InstalledComponent s s' f f' g p p'
```

So it can read the parent's state while installing.

Your suggestion sounds good too though.

**Comment by jdegoes** [comment]
@garyb I don't have a huge preference, although the installer function peeking into the parent's state may lead to coupling between the child and the parent (and possibly parent state capture).

In general, I like the parent to have control and not the children. Although the installer is neither parent nor child, but some sort of integration glues, who knows. :laughing:

**Comment by natefaubion** [comment]
> Can, for example, each child state have a flag, isActive, and just renders empty DOM if it's not active? Then the parent only has to set the isActive state of the currently active child component.

Does this just push the problem down? Each child component would have to know that it is in a tab, you couldn't just embed an arbitrary component directly. So you create a `tabPanel` component that can handle this behavior, and wraps an existing component. but then you still need to install the child component in the tab panel with resumed state.

**Comment by garyb** [comment]
That's true - so we either have the same problem or have to write our child component with knowledge that it's going to be used inside a tabbed view.

I'll make the change to `install` - I think despite the risks it probably is the cleanest way of handling this currently. The much more radical alternative we didn't discuss is some mechanism for saying that the state of child components should persist in a particular parent, but I think that might be a whole other can of worms.

**Comment by natefaubion** [comment]
> The much more radical alternative we didn't discuss is some mechanism for saying that the state of child components should persist in a particular parent, but I think that might be a whole other can of worms.

Yes, this was my first thought, but then you go down the route of solving cache invalidation, and no one wants to do that.

**Comment by natefaubion** [comment]
Or, you could just expose the child state handling logic in some way. Right now you always remove it, but could you factor that out?

**Comment by garyb** [comment]
It would be a bit tricky to do so in its current form - or, to give access in a way that is actually useful anyway: https://github.com/slamdata/purescript-halogen/blob/d894a2a160478927df0143fe2a6de4438a3c168a/src/Halogen/Component.purs#L271-L275

We basically start with an empty dictionary and re-populate it at the moment, I guess we'd want something more diff-like, so after rendering we would have two things: the new state map, and the old state map, filtered to only containing entries for the slots that were removed.

**Comment by garyb** [comment]
I added `installWithState` combinators here https://github.com/garyb/purescript-halogen/commit/c9420794209dab545f3ed2c07919eaff99caad4c, will close this when the (hopefully final :wink:) PR is merged.
