### ISSUE TITLE
Components that take children

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-halogen#181]
What would be the best way to write a component that takes components as parameters? For example, a generic modal or popover that has its own state and lets you embed a form component or something (or even just HTML). With the slot scheme, because of the addressing, you want them to have as little information as possible to lookup the component state, so this means you can't really pass in children to the slot in `render`. I'm sure its likely possible to do when installing if the state is available, but it doesn't seem desirable to split up rendering like this.

**Comment by garyb** [comment]
Wouldn't you just use a function for this? You wouldn't be passing a component in then, but I think you could achieve what you're describing here, if I understand correctly.

**Comment by natefaubion** [comment]
> Wouldn't you just use a function for this?

I mean, yes, at some point its a function but I don't think its something easily solved by the slot architecture as is. I'm referring to something like [createElement](https://github.com/purescript-contrib/purescript-react/blob/master/docs/React.md#createelement) from `purescript-react`. If the "component" was just a function of `HTML -> HTML`, that would work, but if the component needs its own state/query algebra, I don't have a way of giving children or props to the component in the render function. Slots are just opaque addresses, they really shouldn't hold props/children, otherwise your queries are going to be impossible to construct. You might be able to give HTML and props to the component in `install`, but this just couples `install` even more (and you're effectively splitting up rendering between render and install).

**Comment by garyb** [comment]
I don't think I'm understanding what you're describing here - have you got a pseudocode example or something of what you'd like to be able to do?

From what you were saying in your first example, I thought something like this would suffice:

``` purescript
listP :: forall s f g p. (Functor g) => ParentComponentP ListState s ListInput (Coproduct ItemInput f) g ListSlot p
listP = component' render eval peek
  where

  render :: Render ListState ListInput ListSlot
  render st =
    H.div_ [ H.p_ [ H.button [ E.onClick (E.input_ AddItem) ]
                             [ H.text "New Item" ]
                  ]
           , H.ul_ (map (H.slot <<< ListSlot) st.items)
           ]

  eval :: EvalP ListInput ListState s ListInput (Coproduct ItemInput f) g ListSlot p
  eval (AddItem next) = modify addItem $> next

  peek :: Peek ListState s ListInput (Coproduct ItemInput f) g ListSlot p
  peek (ChildF p q) = coproduct go (const (pure unit)) q
    where
    go (Remove _) = modify (removeItem p)

list :: forall s f g p. (Plus g) => (ListSlot -> ChildState s (Coproduct ItemInput f) g p)
                               -> InstalledComponent ListState s ListInput (Coproduct ItemInput f) g ListSlot p
list mkItem = install' list mkItem
```

So here we're defining a generic `list` component that knows nothing about its children, aside from stating the child query algebra must be a coproduct of `ItemInput` and something else - that part isn't necessary, this was just an idea I had sitting around for how we might be able to define generic parent components that still can do something with their children without needing to know much about them.

**Comment by natefaubion** [comment]
Phew, got a basic generic tab component compiling:
https://gist.github.com/natefaubion/848c2f1a97b213bb7e96

Want to make sure its on the right path. So in terms of fundamental expressiveness, it seems to all be there. Getting `exampleUI` working took a little while. I would say the biggest frustration is jumping between the `render` and `install` worlds, and reasoning about the nested types. Render is a nice, declarative DSL for HTML, but once you need components you have to switch over to `install` which feels very much the opposite of declarative.

```purescript
example :: forall s i g p. (Functor g) => ParentComponent Unit s VoidF i g ExampleSlot p
example = component render absurdF where
  render :: Render Unit VoidF ExampleSlot
  render _ =
    H.div
      [ P.id_ "app" ]
      [ H.slot Tabs ]

exampleUI :: forall g p. (Plus g) => InstalledComponent Unit (InstalledState (TabState ExampleTab) Unit (TabInput ExampleTab) VoidF g (TabSlot ExampleTab) p) VoidF _ g ExampleSlot p
exampleUI = example `install` tabs where
  tabs Tabs = createChild (tabSet Tab3 `install` panels) (installedState { activeTab: Tab1 })

  panels (TabLabel Tab1) = htmlText "Tab 1"
  panels (TabPanel Tab1) = htmlText "Foo"

  panels (TabLabel Tab2) = htmlText "Tab 2"
  panels (TabPanel Tab2) = htmlText "Bar"

  panels (TabLabel Tab3) = htmlText "Tab 3"
  panels (TabPanel Tab3) = htmlText "Baz"
```

Whereas in something like React, everything would be bundled in a single render (like in the [react-tabs](https://github.com/rackt/react-tabs)). You get a nice view of the hierarchy (like what you get with the HTML DSL). But to use components you necessarily have to split up into `install`, and when you have lots of reusable components, the bulk of rendering just becomes installing. I'd argue that this makes `render` and `install` fundamentally coupled anyway. I love the idea of slots/installing as a kind of DI framework, but it would be great if there was someway you could combine the two when you don't need the separation. This is nonsense, and probably can't typecheck as anything, but it would neat if I could lift up an install into render:

```purescript
example = component render absurdF where
  render _ =
    H.div
      [ P.id_ "app" ]
      [ H.installed (tabSet Tab3) \t -> case t of
          TabLabel Tab1 -> htmlText "Tab 1"
          TabPanel Tab1 -> htmlText "Foo"

          TabLabel Tab2 -> htmlText "Tab 2"
          TabPanel Tab2 -> htmlText "Bar"

          TabLabel Tab3 -> htmlText "Tab 3"
          TabPanel Tab3 -> htmlText "Baz" ]
```

**Comment by jdegoes** [comment]
I agree something like "inline install" would be nice. The (currently unsolved) problem with such a concept is that, in the case of foreign components (e.g. an ace editor or chart renderer or maybe even 3d game engine), you need a way for parent components to (a) send commands to the child component, and (b) receive responses from the child component. The component can be embedded anywhere in the HTML, which means that you need a way to *address* a specific child component. 

To date, no one has come up with an "inline" solution for doing this. Which leaves the current bulky design, which allows the view to embed the addresses, and allows the parent to query by address, but which requires the tedious installation process.

Halogen is still evolving, of course, and I have no doubt we'll make composition easier with time (if you have ideas, let us know!). In the meantime, I suggest not over abusing components. Composition of ordinary views works well for large chunks of the application -- in fact, views compose in all the same ways they did in Halogen < 0.4. Components should be reserved for encapsulating complex, self-contained modules of functionality, and ordinary functions can be used for merely eliminating duplication or sharing functionality in views.

**Comment by garyb** [comment]
I guess a combination of the two could potentially work - have `slot` as more like a marker for "addressable child component goes here": and then you could use it as `H.slot keyValue component state`

**Comment by jdegoes** [comment]
@garyb I'm not sure exactly what that would look like, but sounds interesting.

**Comment by garyb** [comment]
I'm trying it out now, but it's a pretty big change - `HTML` would need to carry more type variables around, as `slot`'s type would be something like:

``` purescript
slot :: p -> Component s' f' g Void -> s' -> HTML s' f f' g p
```

**Comment by jdegoes** [comment]
@garyb This evening I played around with an "inline installation" that's sort of a hybrid between 0.4 and 0.5:

```haskell
data Component f g = Component (forall i. f i -> g (HTML i))
```

(Simplified version without state or `HalogenF`)

The user is then responsible for deconstructing `f` into dispatches to child components. Some lens machinery could possibly ensure the child state is a subset of the parent state (via lifting the child component into some suitable `SubscribeF` of the parent).

Children are queried by "calling" their components with their inputs, relying on the lifting mechanism.

Of course, child would probably be represented by a map, so again you're looking at mapping from some sort of key (address / placeholder / slot). 

Hmmm, now that I say this, I see it's sort of like your formulation, in which you `install` by specifying that key and then address elsewhere:

```haskell
div [install AceEditor aceEditorComponent] ...
```

Worth thinking about inline installation, anyway, as it might clean up some of the painful bits.

**Comment by jdegoes** [comment]
Scratch my previous example, it's not quite right. Ideally one would be able to fuse `SubscribeF` into `HTML` in such a way that elements (with added event listeners, for example) could produce `i`s. That is, there should be a single mechanism for describing the production of streams of values, rather than two (`Prop` and `SubscribeF`).

In any case, I think inline installing *by specifying the address during installation* and then *directly querying the child component* and *lifting it into the parent's HalogenF* could work.

**Comment by garyb** [comment]
I think the unified `SubscribeF` potentially would require our alternative FP-friendly `virtual-dom` equivalent... at the minimum we'd have to come up with our own hooks to use instead of the the standard `virtual-dom` event listeners.

Regarding your point from the deleted message - I think inline installation would definitely simplify things as it means we'd no longer need to distinguish between `ParentComponent` (`Component` with a `QueryF` in `g`) and normal `Component` anymore.

**Comment by jdegoes** [comment]
>  I think inline installation would definitely simplify things as it means we'd no longer need to distinguish between ParentComponent (Component with a QueryF in g) and normal Component anymore.

Yes, could make sense, although you will have to construct your state in a certain fashion (`ParentState`?) so that the child components can be lifted up into the same output algebra. Lenses could probably make that pretty simple (accessing the component's own state, for example).
