### ISSUE TITLE
Alter `peek` to only have visibility of the immediate children

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#184]
Currently `peek` can see queries going to any descendant, which suggests components know far too much about their children. However, as there is no way to "bubble" queries up the hierarchy, removing this ability now would be problematic.

A concrete example of the problem, discovered while working on SlamData:

1. The notebook component has a menu bar
2. The menu bar component contains drowdown submenus
3. The submenu components contain items that raise actions for the notebook

So when choosing an item in the submenu, the menu bar can observe this by `peek`, but `peek` has no way of letting us raise a query on the menu bar component itself, so this means if we only allow one-level-deep peeking there is no way the notebook component will be able to see the chosen menu item.

One possible fix would be to change `peek` so all it can do is return a query that is then processed in `eval`, rather than having it operate in `Free HalogenF` as it does currently, but making this actually possible would need a lot of figuring out.

**Comment by jdegoes** [comment]
> Currently peek can see queries going to any descendant, which suggests components know far too much about their children. 

I *might* argue this is a benefit. A component can always be polymorphic in the type of its children, if it doesn't want to know about them. 

A component already has access to the state of all descendants, and can send messages to all its descendants, so why should it not see the behavior of all descendants? Parents sometimes have to facilitate interaction between descendants along different paths. It's sort of natural a parent is the union of all capabilities of all its descendants (and polymorphism, above, can be used to indicate a component doesn't care about certain parts of its children / descendants).

**Comment by garyb** [comment]
That's true, I mean yeah, the parent definitely knows all about its children as the type has all that information in it. :smile: I did consider this when writing up the issue, but still wasn't totally sure it's the right thing.

Allowing peeking of descendant queries does cut down on some boilerplate too actually - in my suggested scheme every intermediate query algebra between the child and parent that wants to observe the action would need to replicate an equivalent constructor to "bubble" the query up manually.

Shall I close this then?

**Comment by jdegoes** [comment]
> Shall I close this then?

Up to you (based on pain of working with Halogen), but personally I don't think there's anything sinister about a parent knowing about descendants (if it wants to, since again, it can always be polymorphic in their type).

**Comment by garyb** [comment]
I'll close it for now then, can revisit later if needs be.

**Comment by themoritz** [comment]
@garyb do you have an example of multiple-level-deep peeking?

My use case is that the root component of my app needs to have a loading indicator, and whenever any descendant is doing ajax calls, the root component should take notice of that and turn the indicator on/off.
