### ISSUE TITLE
identity child path

### ISSUE THREAD

**Issue by jonsterling** [slamdata/purescript-halogen#185]
In `purescript-markdown-halogen`, the demo is a component that has a single child. In this case, it is helpful to have a child path like this:

```
identity = ChildPath id id id
```

**Comment by garyb** [comment]
Like this https://github.com/slamdata/purescript-halogen/pull/178/files#diff-2820d2461f2c8fcf310110695d9cb5b1R36? :smile:

**Comment by jonsterling** [comment]
Agh, can't believe I didn't see that! Thanks :smile:

**Comment by jonsterling** [comment]
@garyb Oh, heh, it's in a PR. OK, :+1:!

**Comment by garyb** [comment]
Well, it's not merged yet, so it's probably not in the version you were looking at - but actually, there are none-`ChildPath`'d versions of all the functions, so generally I don't think you need this anyway?

I added it as a convenience for when you know you're going to be setting up a multi-children component but are starting off with a single child first.

**Comment by jonsterling** [comment]
Oh, you're right... I didn't realize that it would work to use the non-child-path'd versions in my code, but it does! Thanks.
