### ISSUE TITLE
Missing purescript-profunctor dependency

### ISSUE THREAD

**Issue by jonsterling** [slamdata/purescript-halogen#186]
It may be that the Halogen build ended up somehow having profunctors transitively, but when using purescript-halogen as a dependency elsewhere, the profunctor dependency does not appear to get installed.

There's a trade-off here... If you take advantage of a transitive dependency, you may be sorry when your immediate dependency changes its own dependencies. I think it is necessary to specify as a dependency anything which you will import, since transitive dependencies are not part of the signature / interface of a library, and may be changed out from under you (for instance, there is no versioning policy for when I remove a dependency from a library, but that will break any other package that relies on the transitive dep).

The trade-off is of course that it makes upgrading the ecosystem a bit more involved. However, I think that this is less undesirable than builds seemingly randomly going wrong.

**Comment by LiamGoodacre** [comment]
I raised a similar issue a while ago on a different purescript repo.  The conclusion was essentially that using transitive dependencies is fine and changing dependencies constitues a breaking change.

But even though that was the conclusion it still makes me uncomfortable and I usually list everything explicitly.

**Comment by garyb** [comment]
There was actually a different issue causing this, but yeah - I don't mind either way we do it. By convention relying on transitive dependencies is how things are in core, but I can definitely see both sides of it.

I guess my main problem with being explicit is this: it's easy to accidentally rely on transitive dependencies by mistake, even if you are trying to list everything explicitly. So if we start making the claim that every dependency is listed it means we have to put real effort into making sure that that is true.
