### ISSUE TITLE
"autocomplete" property

### ISSUE THREAD

**Issue by michael-swan** [slamdata/purescript-halogen#190]
The form and input elements make mention of the "autocomplete" option but there is no corresponding property in purescript-halogen/src/Halogen/HTML/Properties/Indexed.purs.

**Comment by jonsterling** [comment]
Yes... I wrote the refinements "exhaustively", even though we have not yet implemented every HTML attribute. So there are likely other examples of this.

If I don't get around to adding this soon enough, PRs are always welcome!
