### ISSUE TITLE
non-ascii character in src/Halogen/Query/StateF.purs

### ISSUE THREAD

**Issue by cdepillabout** [slamdata/purescript-halogen#192]
I am using the current tip of Halogen's master branch (c9f6efd24a9) in a project.  I am getting an error when I try to build my project:

```
$ pulp build
* Building project in /opt/src
psc: No files found using pattern: src/**/*.js
psc: /opt/src/bower_components/purescript-halogen/src/Halogen/Query/StateF.purs: hGetContents: invalid argument (invalid byte sequence)
* ERROR: Subcommand terminated with error code 1
```

It looks like there is a non-ascii character in `src/Halogen/Query/StateF.purs`.  It is the quote character in the third line.  

Replacing the non-ascii quote with an ascii quote makes the file compile correctly.

**Comment by garyb** [comment]
Interesting... I don't see this, but perhaps it depends on the system codepage.

The next release of the PureScript compiler should fix this, as it forces reading files as UTF-8, but I'll change the comment too.

**Comment by cdepillabout** [comment]
Thanks a lot :+1:

**Comment by garyb** [comment]
Fixed now!
