### ISSUE TITLE
README not showing up

### ISSUE THREAD

**Issue by aspidites** [slamdata/purescript-halogen#200]
I suspect this is a pursuit issue, so I've opened [this](https://github.com/purescript/pursuit/issues/154) issue. This is mostly for book keeping and to notify you of my attempt to reupload the package to pursuit with no positive change in results.

**Comment by garyb** [comment]
Yeah, I saw this too after uploading, I wondered if it was something to do with the size of the README, as it's massive compared to any of the others out there currently.

Additionally I think the README won't work too well on Pursuit even if it was appearing as there are a lot of embedded links that will be broken on there.

**Comment by aspidites** [comment]
I wonder if a compromise would be to elide text after so many characters or force the inclusion of a short description section to be used on pursuit with a link to the full readme on github?

**Comment by garyb** [comment]
This would be the idea fix IMO purescript/pursuit#150

**Comment by aspidites** [comment]
Ah. Reading that now.

**Comment by garyb** [comment]
Closing this as it's definitely pursuit-related. Thanks!
