### ISSUE TITLE
initializer fires before dom loaded 

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#203]
I'm not sure that this is really halogen issue. But it's confusing and non-obvious. 

I've been working on `zeroclipboard` integration. And have this code 
```purescript 
 eval (InitZClipboard url htmlEl next) = do
    let el = htmlElementToElement htmlEl
    liftEff' $ Z.make el >>= Z.onCopy (Z.setData "text/plain" url)
    pure next
```
If I set state to show this element an error is raised. In short there is no `document`. 
I've added 
```
-- DOM.Shortcuts.purs
foreign import waitLoaded :: forall e. Aff (dom :: DOM |e) Unit
-- DOM.Shortcuts.js
// module DOM.Shortcuts
exports.waitLoaded = function(cb, eb) {
    window.addEventListener("load", cb);
};
-- ShareDialog.purs
 eval (InitZClipboard url htmlEl next) = do
    let el = htmlElementToElement htmlEl
    liftAff' waitLoaded
    liftEff' $ Z.make el >>= Z.onCopy (Z.setData "text/plain" url)
    pure next
```
And it works.

**Comment by garyb** [comment]
How are you adding the component to the page in `main`? It should already be waiting for `onload` in there before even running the UI if you're using `Halogen.Util.appendToBody`.

**Comment by cryogenian** [comment]
```purescript
main :: forall e. Eff FileSystemEffects Unit
main = runAff throwException (const (pure unit)) do
  halogen <- runUI ui (installedState initialState)
  appendToBody halogen.node
  forkAff $ routeSignal halogen.driver
```

**Comment by cryogenian** [comment]
May it be connected with initializer machinery somehow?

**Comment by garyb** [comment]
Ah right, maybe this is happening before `appendToBody` even then.

Yeah, the initializer runs when the element is created by virtual-dom, but I don't think that's guaranteed to be _in_ the DOM at that point - I looked through the patching code and it appears hooks are run before `appendChild` when a node is created (but when it is being patched it happens after `appendChild`). Annoying :(

Perhaps we could put an `onload` handler around the whole `main`? I'm not sure that will work either though if this is failing because it runs before `appendToBody`.

**Comment by cryogenian** [comment]
> Perhaps we could put an onload handler around the whole main? I'm not sure that will work either though if this is failing because it runs before appendToBody.

Doesn't work. Blank screen and no error.

**Comment by natefaubion** [comment]
I mentioned this in another PR (https://github.com/slamdata/purescript-halogen/pull/196#issuecomment-148916873). Virtual-dom provides no facilities to run code when the element is actually loaded in the DOM (hooks are always run during patch). If you want a `componentDidMount` type hook, we have to wire up that machinery ourselves. Virtual-dom docs just have an example of using `setImmediate` to defer, which obviously doesn't guarantee anything.

**Comment by garyb** [comment]
Yep :( I meant to respond to that comment of yours but got sidetracked when were looking at something else.

I had an idea for how we might work around this, but it's ugly as it means keeping track of the current set of initializers and then running them from within Halogen's rendering _after_ the patch process, but even then we don't have a guarantee that the elements are actually on the page.

**Comment by beckyconning** [comment]
I think your solution of making it reattempt / wait until successful is correct @cryogenian. I think its easy to understand : ).

I guess sometimes you just have to fix a library's assumptions to make it work in this situation.

**Comment by natefaubion** [comment]
> I had an idea for how we might work around this, but it's ugly as it means keeping track of the current set of initializers and then running them from within Halogen's rendering after the patch process, but even then we don't have a guarantee that the elements are actually on the page.

That's basically what I tried, but didn't complete. I added a couple of different options (`Preinitializer` and `Postfinalizer`). When the hook was run it would push the effect code to a mutable array. You have to change the signature of the initialization process to not return a node, but an effect that will append the node somewhere, and run the initializers.

**Comment by garyb** [comment]
This should be fixed in the next version: we require an element in `runUI` now, and the way `initializers` are handled is after rendering completes, so it should be guaranteed that an element returned by a `ref` is now in the DOM when an `initializer` fires.
