### ISSUE TITLE
unecessary IProp type synonym?

### ISSUE THREAD

**Issue by cdepillabout** [slamdata/purescript-halogen#206]
In `Halogen/HTML/Properties/Indexed.purs`, the following type alias exists:

```
-- | The phantom row `r` can be thought of as a context which is synthesized in the
-- | course of constructing a refined HTML expression.
type IProp (r :: # *) i = Unsafe.IProp r i
```

`Unsafe.IProp` is defined in `Halogen/HTML/Properties/Indexed/Unsafe.purs` like the following:

```
-- | The phantom row `r` can be thought of as a context which is synthesized in the
-- | course of constructing a refined HTML expression.
newtype IProp (r :: # *) i = IProp (Prop i)
```

I'm not sure I understand why IProp type synonym exists.  Couldn't `Halogen/HTML/Properties/Indexed.purs` just re-export the `Unsafe.IProp` type (and not export the the data constructor)?  Then `Halogen/HTML/Properties/Indexed/Unsafe.purs` could export both the `Unsafe.IProp` type constructor and data constructor.

Maybe this wouldn't work for some reason?

**Comment by jonsterling** [comment]
I can't quire remember why I did it this way, but I seem to recall that it was forced by some frustrating issue with the compiler. @garyb Maybe it was that problem with re-exports that we were talking about before?

**Comment by garyb** [comment]
I'm not sure actually, I hadn't even noticed we had two `IProp`s! I'll see if we can do without now.
