### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by mchaver** [slamdata/purescript-halogen#207]
Reading through the todo example code, it looks like `peek` has changed and this has not been updated on the front page documentation. `ParentDSL` doesn't seem to be mentioned either. Most challenging part of halogen is managing all the type stacks.

Edit: Sorry, it looks like those types were just added recently, didn't mean to be pushy.

**Comment by garyb** [comment]
No problem :smile:

The `render`, `eval`, `peek` types in the todo example are still typed as per the documentation, but arriving there via alternative synonyms.

I think we probably should switch over all the documentation to use the new synonyms though, as they are a bit more useful on the whole (and actually look like functions which should help comprehension).

**Comment by mchaver** [comment]
Thanks! One thing that would be helpful would be to see AJAX and other effects get mixed in the Parent/Child component. Anyway, that's where I am stuck on now, getting the types to work. I think others might run into that issue as well ;)

**Comment by mchaver** [comment]
This has an example in `Five.purs` and `Six.purs` where AJAX is used in the child, but using it in the Parent and getting the types right is the challenge.
https://github.com/parsonsmatt/purs-architecture-tutorial/tree/master/src/Example

**Comment by garyb** [comment]
Sorry, I don't have time to make an example of this right now, but I'll try and do so tomorrow.

**Comment by parsonsmatt** [comment]
You should just be able to run `liftFI (yourAffjaxRequest)` in the parent component as well. Can you post what exactly you're having issues with?

**Comment by natefaubion** [comment]
> I think we probably should switch over all the documentation to use the new synonyms though, as they are a bit more useful on the whole (and actually look like functions which should help comprehension).

Would you consider reexporting the `Natural` synonym? All the other synonyms are available under the root `Halogen` import. It'd be nice to not have that there as well.

**Comment by garyb** [comment]
I think the specific issues in here were addressed a while ago, and I'll be updating the docs again for the new release to ensure everything is up to date for 0.6 since we've now eliminated some of these old type synonyms, etc.
