### ISSUE TITLE
Halogen and html

### ISSUE THREAD

**Issue by user471** [slamdata/purescript-halogen#208]
Is there any plans to split halogen and html similar to how react was spitted to react and react-dom?
So you could use halogen with any UI backend like canvas, mobile UI, etc and not only html.

**Comment by garyb** [comment]
Rendering to targets other than virtual-dom is possible (there's a string renderer, for example) but there is no way to change components to use a render DSL other than `HTML` - however `HTML` can represent any XML node, so it is possible to render SVG or other XML based markups too.

Possibly 0.6 will allow other render DSLs, but there are a few things internally which make this difficult right now.
