### ISSUE TITLE
Different approach to Ajax errors

### ISSUE THREAD

**Issue by mchaver** [slamdata/purescript-halogen#209]
I'm not sure if this issues lies in Halgoen or Affjax. Feel free to move it to the appropriate project.

I've noticed if you make an Ajax call and something goes wrong like not finding the website, the function ends early. I think a better approach would be to call a function returning Aff (ajax :: AJAX) and have it wrapped in something like Either, and then you can check if the AJAX call ran properly or not. Here is an example, if you can't find the testUrl, doSomething won't get called.

```purescript
testUrl :: String
testUrl = "http://127.0.0.1:5000/test/"

testRequestUrl :: String -> String
testRequestUrl s = testUrl ++ s 

fetchTest :: forall eff. String -> Aff (ajax :: AJAX | eff) String
fetchTest s = do
  result <- AJ.get (testRequestUrl s)
  let response = result.response
  return case readProp "val" response of
    Right r -> r
    Left  _  -> "Invalid response"

eval :: ...
eval ... = do
  val <- liftFI (fetchTest s)
  doSomething
  pure next
```

**Comment by garyb** [comment]
If you use `attempt` from `purescript-aff` it will lift the failure out of `Aff _ result` and give you an `Aff _ (Either Error result)` back instead - I think that's basically what you're looking to do here?

**Comment by mchaver** [comment]
That works just fine.
