### ISSUE TITLE
Input field type and default value

### ISSUE THREAD

**Issue by parsonsmatt** [slamdata/purescript-halogen#210]
So, I've got an input field [here](https://github.com/parsonsmatt/ql-purs/blob/master/src/Components/Sessions.purs#L96-L99):

```purescript
H.input [ P.classes [ B.formControl ]
        , P.value (formDateFromDate $ st.currSessionDate)
        , P.inputType P.InputDate
        ]
```

If I have the `P.inputType` property, then the `P.value` is always overridden, and the value is always "mm/dd/yyyy". If I omit the `P.inputType`, then I can have a default value, but the type of the input goes unspecified, and Chrome etc doesn't put in a datepicker.

It seems like I should be able to specify both an input type and a default value. What's the way to do that?

**Comment by garyb** [comment]
The "non standard" form inputs behave absymally - I'm not sure this is down to Halogen necessarily. Have you tried the equivalent code just in HTML? Does that work? How about if you construct an input in javascript and assign the value/type properties?

**Comment by parsonsmatt** [comment]
Ahhh, my fault! I was providing the value as `yyyy/mm/dd` and it wanted `yyyy-mm-dd`. :|
