### ISSUE TITLE
Communication from grandchild to grandparent

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#217]
It is not clear to me how communication from a grandchild component to a grandparent component is working/will be working in halogen.

Communication from grandparent to grandchild (both query and action) is not a problem, since, when the parent is evaluating the actions that are called from the grandchild, it can always call actions on the grandchildren.

However, when peeking (this is how currently communication from child to parent is implemented), the parent has no way of issuing actions in its own query algebra that can then be peeked into by the grandparent, and therefore, messages from the child cannot "bubble" up the hierarchy.

What are the options at the moment?

* @garyb mentions in #184 that components can peek arbitrarily deep, but I cannot figure out how this would look like. If this will be the best practice way of doing it, adding an example would be great.

* Maybe there is some way to feed input into the root component (similar to the driver, but from any descendant component in the app), so that it can then trickle down the hierarchy? Independent of the technical possibilities, this would be a nice feature, since it would cover many use cases without the need to carry messages up to the root and then down to other components.

**Comment by garyb** [comment]
I'll put together a deep-peeking example now.

Option 2 is problematic for a few reasons, and technical issues aside I don't think it's a good idea because it destroys the modularity of components - if a child component knows about the structure of the tree it resides within it's no longer a self contained thing, which is kinda the whole point. :smile:

My preference would be to allow a parent to raise actions "in itself" in response to peeking - I did look into how this might work, but it's certainly not easy to do currently, so may be something we revisit in the next version.

**Comment by themoritz** [comment]
Yeah, that's right. ;) And I agree that peek raising an action in the same component is the most natural way.

Looking forward to the example!

**Comment by jdegoes** [comment]
Right now `peek` observes the child input and then produces a parent output. But what if `peek` observed the child input and produced a parent input? i.e. 'When my child is told to do X, tell me to do Y.'

Basically, "raising actions in the parent" is as powerful as you need, you don't need that *and* current peek, AFAICS.

That said, I think there's something even more general here we're ignoring: it'd be nice to do fully "self-contained" communication by proving a child's output algebra `g'` can be expressed in terms of the parent's input algebra `f`. (Maybe that's another way of stating the above?) It's sort of a way of saying, "I don't need to do anything here, my parent can do it for me, and here's the proof that my output can be translated into the parent input."

i.e. during "installation" you provide some way of pulling off and / or translating the child's output (not necessarily `g`) to both the parent output and the parent input, so you can decide on just how self-contained this is.

**Comment by garyb** [comment]
Yeah, "raising actions on the parent" is what I had in mind as the way of solving this, seems like the most elegant way of handling it - I just haven't figured out the details of making that happen as things are.

**Comment by jdegoes** [comment]
I don't want to know what it does to type inference. :smile: But the basic idea would be something along these lines:

```purescript
quotient :: Natural g' (Coproduct g f)
```

Where you express the idea that a child component's `g` is really a factoring of the parent's input algebra `f` and the parent's output algebra `g`.
