### ISSUE TITLE
Newtype `InstalledState`

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-halogen#220]
Type errors that include an `InstalledState` somewhere throw up the desugared synonym, which is very distracting, and is mostly information the user doesn't need to know.

**Comment by jonsterling** [comment]
I've experienced this as well...

**Comment by garyb** [comment]
Me too! Great idea :+1:

**Comment by natefaubion** [comment]
Great, I'll work up a PR later.

**Comment by garyb** [comment]
Closed by #226
