### ISSUE TITLE
Switching from composable to decomposable

### ISSUE THREAD

**Issue by jdegoes** [slamdata/purescript-halogen#221]
I think a fairly conservative change can make it easier to build applications under Halogen.

Currently, components are built by composing them from smaller components. This leads to some rather complicated intermediate structures, which are not very easy to work with (e.g. 4-way nested `Coproduct`). However, there's nothing in Halogen that prevents us from going the other way: that is, from decomposing components from larger ones.

First, define a `Nest` (like bird's nest), which represents the location a component sits inside a parent:

``` purescript
type Nest s s' f f' g g' =
 { state :: LensP s s', input :: Prism1P f f', output :: Prism1P g g' }
```

The `Nest` is a description of how to get and set the component's state, how to extract out the component's input from the parent's, and out to map the component's output to the parent (types are _approximate_).

Now, when defining the component, you actually define it as a function from its nest to the component:

``` purescript
aceEditor :: forall eff s f g. (Functor f) => Nest s AceState f AceIn g AceOut -> Component s f g
aceEditor self = ...
```

Then when accessing the sate through helpers, one must supply the nest:

``` purescript
getState self
```

Similarly, when processing an input or producing an output, one must supply the nest.

It would be a convention for every component `X` to define `XState`, `XNest`, etc.

Various lens-related machinery can be used to access children and so forth.

Needs more fleshing out, but what do people think? Decomposition a viable alternative to composition?

/cc @garyb @beckyconning @cryogenian @jonsterling

**Comment by garyb** [comment]
This is very much related to the things Jon and I have been looking at, but the real sticking point is the inability to provide a non-partial function that can safely transform to and from `s` and `s'`.

The `f` and `g` cases are a bit easier as you can require a `Plus` constraint and fall back to `empty`, but I am yet to figure out how to handle the state mapping.

**Comment by garyb** [comment]
Although our use case was perhaps a little different, as we were trying to simplify having large sums of children, whereas this isn't quite that - here we're just "zooming" in on a part of the parent's state for the inner component to use, so it can definitely work for that.

**Comment by jdegoes** [comment]
> whereas this isn't quite that - here we're just "zooming in" on a part of the parent's state for the inner component to use, so it can definitely work for that.

That's correct. 

Parents would then explicitly contain the state of their children, e.g.:

```purescript
data MyState = MyState
  { children :: Map AceId AceState, ... }
```

When you query a child, you "lift" it to the parent, and because the lookup may fail, the helper which performs the query requires a failure state in `g`.

**Comment by cryogenian** [comment]
This approach is very similar with `purescript-optic-ui` I think. 
Can we not switch from coposition to decomposition, but add this approach?

**Comment by jdegoes** [comment]
> This approach is very similar with purescript-optic-ui I think. 
Well, opti-cui relies heavily on effects, so the only thing it decomposes is the state. Halogen has a purely declarative approach, so you have to decompose the state and the input / output algebras. But yes, it's similar.

> Can we not switch from coposition to decomposition, but add this approach?

Yes, I think they should be compatible. The main advantages of decomposition will be that:

a. You can use natural sum types at every layer of the hierarchy, instead of composing them from eithers / coproducts / etc.
b. You can move some boilerplate to the optics definitions.

**Comment by natefaubion** [comment]
This probably won't be happening in Halogen proper, but it's easy enough to do a TEA architecture on top of it like https://github.com/natefaubion/purescript-halogen-startapp
