### ISSUE TITLE
Can only subscribe to one event

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#222]
If I subscribe to a second event in the ace example, only the first handler is attached.

```purescript
subscribe $ eventSource_ (Editor.onFocus editor) $ do
  pure $ action (ChangeText "focus")
subscribe $ eventSource_ (Session.onChange session) $ do
  text <- liftEff $ Editor.getValue editor
  pure $ action (ChangeText text)
```

In the above example, the `onFocus` handler works, but if I put `onChange` first, only that one works.

**Comment by garyb** [comment]
Well that's a pretty huge flaw! Thanks for the report.

**Comment by garyb** [comment]
Actually it's even worse than what you describe: when you use `subscribe` no actions after it are evaluated.
