### ISSUE TITLE
Feature similar to React's props?

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#227]
React components have "props", which are a convenient and declarative way of passing state information read-only from parent to child component:

``` coffeescript
Parent = React.createClass
  getInitialState: ->
    msg: "Foo"
  render: ->
    <div><Child content={@state.msg}></div>

Child = React.createClass
  render: ->
    <p>{@props.content}</p>
```

The interesting thing being that `Child` re-renders automatically when the state of `Parent` changes. Is something like this possible in halogen / could it be possible in future versions?

The alternative to props is replicating part of the parent's state in the child and then sending update actions to the child whenever the parent's state changes. This is not declarative and you get the typical bugs where you forget updating the child's state, etc.

**Comment by cryogenian** [comment]
I think `slot` is more or less identical with `props` I.e.
```purescript
parent = component render eval (const $ pure unit) 
  where 
  render state = p_ [ slot state.content \_ -> { component: child
                                               , initialState: initialChildState state.child}]
  eval ...
```
when `state.content` changes slot and child will be changed too. (Note that only changing slot will produce new component, changing `state.child` will not have effect)

**Comment by themoritz** [comment]
I see, this works because the placeholder is not part of the thunk. Wouldn't the implication then be that the state of the child component will be reset when the placeholder changes?

What I'd love to have is that the child component operates in some sort of closure that is defined by the parent and changes with the parent's state.

**Comment by cryogenian** [comment]
Yep, child component state resets after slot changes. But you can place child state to placeholder. Though, this can be done only if child state is instance of `Ord`. 

I'm not sure that creating such closure is possible, @garyb probably knows better... Maybe #221 can help with this

**Comment by garyb** [comment]
I think #221 is exactly what would be needed to make this possible - children have no access to their parent's state, and Halogen currently hides the plumbing so that parents cannot directly access or modify child states either.

**Comment by natefaubion** [comment]
You could do this with the current Component model with some existential magic. You essentially tuple up the props and private state, but hide the type of props in `InstalledState`. This lets you keep typesafe props, but not worry about composing them since its only a parent -> immediate child propagation of state. This also lets you move `initialState` into the component definition since you aren't using it as a means to propagate one-time "props". The disadvantage of props is that `memo` in `InstalledState` becomes useless since props is equivalent to just changing the state every time you render. You would definitely have to go back to using an opt-in virtual-dom `Thunk` instead of doing it automatically based on whether a component was queries.

```purescript
-- `a` is the type of props
newtype Component a s f g = Component
  { render :: a -> s -> ComponentHTML ...
  , initialState :: Unit -> s
  , ...
  }

type Propped a s =
  { props :: a
  , state :: s
  }

newtype InstalledState a s s' f f' g p = InstalledState
  { state :: Propped a s
  , children :: Map p (Installed s' f' g)
  , ...
  }


data InstalledF a s f g = Installed (Propped a s) (Component a s f g)

foreign import data Installed :: * -> (* -> *) -> (* -> *) -> *

installComponent :: forall a s f g. a -> s -> Component a s f g -> Installed s f g
installComponent props state =
  unsafeCoerce <<< Installed { props, state }

installedState :: forall s f g. Installed s f g -> s
installedState inst =
  case unsafeCoerce inst of
    Installed { state } _ -> state

data SlotF a s f g p = Slot p a (Component a s f g)

foreign import data Slot :: * -> (* -> *) -> (* -> *) -> * -> *

mkSlot :: forall a s f g p. p -> a -> Component a s f g -> Slot s f g p
mkSlot slot props =
  unsafeCoerce <<< Slot slot props

runSlot :: forall s f g p r. (forall a. p -> a -> Component a s f g -> r) -> Slot s f g p -> r
runSlot k m =
  case unsafeCoerce m of
    Slot slot props c -> k slot props c

installSlot :: Map p (Installed s f g) -> Slot s f g p -> Map p (Installed s f g)
installSlot i =
  runSlot \slot props (Component{ initialState }) ->
    let
      state =
        case lookup p i of
          Just c' -> installedState c'
          Nothing -> initialState unit
    in
      insert p (installComponent props state c) i
```

Another pro is that this can potentially introduce mild type-variable profanities, which is always enjoyable.

**Comment by garyb** [comment]
This has been integrated into the new Halogen: slots and components now have an "input value". When a parent re-renders a query is raised on the child component with the input value, allowing it to respond accordingly. There's no intelligence in what happens here, so for React-style props it will be up to the child component to check whether anything has changed before updating itself.
