### ISSUE TITLE
Event sources aren't filterable

### ISSUE THREAD

**Issue by jonsterling** [slamdata/purescript-halogen#233]
Event sources are producers from `purescript-coroutines`, but these cannot be filtered. A (pure) producer is guaranteed to always have a value; however, most browser-related event streams do not have this property, and so it appears that "waiting on" a value that may never come has been factored into `AVar` in the `Aff` monad. That is, emptiness for producer is implemented using an effect at present, it would appear.

That was a sufficient means to deal with the fact that (for instance) a JavaScript event listener will not always be firing, but I still think the use of `Producer` is kind of unsatisfactory, since it seems to mandate that *all* events from an `EventStream` be handled; in practice, this means adding no-ops to your query algebra for no good reason.

It may be possible to "filter" an event stream by again using `AVar` and `Aff` in the same way as was done above, but this seems kind of anticompositional and difficult, especially in a real world application, you almost *always* want to filter an event stream (or, at least, say "I won't respond to this event").

One option would be to add a new type like `Producer`, but which uses something with a `Stall` constructor instead of just `Emit`. I'm also open to other suggestions; what do people think?

@garyb @jdegoes @beckyconning @cryogenian

**Comment by cryogenian** [comment]
I've had troubles with `Producer` in code that uses `forkAff`, not sure why. Probably it produced more events than `Consumer` can handle. :+1: for switching to something more `Aff`like or remake __consumer/producer__

**Comment by jonsterling** [comment]
I wonder if it would be possible to just switch Halogen to use a stack-safe version of `ListT`. Anybody have any thoughts on this?

**Comment by jonsterling** [comment]
Another option would be to have the event source use `Coproduct (Const Unit) f` instead of `f`. I am not sure what effects this would have on the rest of the apparatus, since the relationships between the various type parameters as enforced in the menagerie of Halogen types is a bit abstruse, or at least unclear to me.

**Comment by jdegoes** [comment]
`ListT (Aff _)` would indeed be much simpler (and it should already be stack safe). We used that in an earlier version of Halogen. I'm not sure that's the right abstraction either, but I think finding the right one sort of depends on unifying how HTML elements produce streams of values with how user-land code (possibly using FFI) produces them, which seems to require vdom rethinking, which in turn is a longer-term project. 

Certainly, `ListT` would provide filtering and lots of other things out of the box; it's a finite or infinite stream, albeit with no mechanism to "unsubscribe" if it's an infinite stream (not that `Producer` is any different).

**Comment by jonsterling** [comment]
@jdegoes Ah, I didn't know that the `ListT` in transformers was already stack-safe; that's good to know, thanks! This might be a reasonable way forward for the short-term (lacking a grand unification of the two different kinds of event stream we have).
