### ISSUE TITLE
Subscriptions & parent components

### ISSUE THREAD

**Issue by jonsterling** [slamdata/purescript-halogen#234]
I'm opening this ticket so that various discussions which have so far been in Slack or hangouts can be centralized here. Here are a few observations:

1. In the evaluator for a regular component (something of type `Component...`), it is already possible to use `subscribe` to translate events into queries on the component. Just so there is no confusion, this means: if component `C`'s query language contains a query `Q`, then `C`'s evaluator can interpret an event source into invocations of `Q` on itself.

2. In the evaluator for a *parent* component (something of type `ParentComponent...`), this does *not* appear to be possible. The best I was able to do was turn events into queries on a child component.

The above is pretty concerning, if true. If this is really not possible under the current design, then it smells like we have coded ourselves into a corner—ideally, the same code would work in both cases (!), but I'll grant that this is not necessary possible. I think that turning events into queries is a pretty standard use-case that we need to support, on both child and parent components.

If anyone has worked around this issue, please note it here! Or if anyone has ideas on how to change Halogen's architecture to support this, let's talk about it here as well.

**Comment by jdegoes** [comment]
You want to `subscribe` in the parent, to produce `f Unit`, which are then fed into the parent?

If so, indeed, this is pretty basic, if it doesn't work it's probably a bug, as I can't think of anything that would prevent it (I can't imagine how this would happen unless we have partial interpreters, but somehow perhaps we're dropping nested algebras somewhere?).

**Comment by jonsterling** [comment]
@jdegoes If it does work, it eluded @beckyconning, @cryogenian and myself. When you try to do this, the only thing kind of action it is possible to return is of type `ChildF`, it would appear. Part of the problem may be that in order to even use `subscribe`, you have to `liftH` the whole thing, which may be what is causing the weirdness. We weren't sure though.

**Comment by garyb** [comment]
The thing that is making it difficult is having `g` as `QueryF` in the case of the parent example, I'm going to see what's up now the notebook stuff is unblocked. I think it is possible, just needs some `liftH` or other kind of transformation to juggle the types a bit inside the `EventSource` that we're subscribing to.

**Comment by jdegoes** [comment]
Indeed, I'd expect the weirdness is caused by some helper function or another.

Trial and error should help determine what the right set of "helper functions" is that maximizes usability and composability.

I was thinking in terms of a hypothetical `Prism1` (the higher-order version of `Prism`) and how it should be possible to compose them, and offer a more generic means of lifting that has the same structure regardless of what level you're lifting to. Something like:

```purescript
-- go from a 'smaller' output to a bigger one:
lift <prism1> <out>
```

There's a symmetrical operation for building an input with prism1s on the other side (although it maybe isn't as useful).

**Comment by garyb** [comment]
Aside: `Prism1` is just `type Prism1 s t a b = Prism (s x) (t x) (a x) (b x)`. I guess you already knew that though :wink:

We're already using prisms this way in the notebook: https://github.com/slamdata/slamdata/blob/4b1526ed39b439c98b0daa0376dd6b8fc11af938/wip/src/Notebook/Cell/Component/Def.purs#L29

**Comment by jdegoes** [comment]
> We're already using prisms this way in the notebook:

Cool. We should maybe thinking about putting the type synonyms into lenses (or a new lib) and figuring out how any combinators generalize.

**Comment by garyb** [comment]
This got fixed at some point, it is now possible to subscribe in parent components.
