### ISSUE TITLE
liftEff' & parent components

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#237]
If I have a "leaf" component, I can use `liftEff'` to lift an action in the `Eff` monad into `Free (HalogenF s f g)`, provided that `g` has a `monadEff` instance.

However, if I have a parent component (that has only one type of leaf component), `g` above is in fact some `Free (HalogenF _ _ g)` (via `QueryF`). Therefore, I need to write
```purescript
liftH $ liftEff' m
```
to lift the action into where my eval function runs.

Now, when my parent component has many different types of deeply nested descendants, I probably need some wild combination of lifts to get what I want and I no longer know what to do (anyone has a recipe?).

So my idea was that it'd be convenient if a `MonadEff eff g` instance could be carried through the castle of types up to the top, e.g. by writing instances like
```purescript
instance monadEffFreeHalogenF :: (MonadEff eff g) => MonadEff eff (Free (HalogenF s f g)) where
  liftEff = liftH <<< liftEff
```
and probably other. (I guess wrapping the `Free (Halogen s f g)` would be necessary.) Then I could just write `liftEff'` no matter in what type of component I am. It would also lead to more re-usable code.

**Comment by themoritz** [comment]
Ok, I guess never mind, all of a sudden `liftH $ liftEff' m` in the eval function of a parent component high up in the hierarchy just worked.

**Comment by garyb** [comment]
Yeah, the `QueryF` nesting doesn't get any deeper no matter how many child components we have under the parent, so a single `liftH` is enough.

Avoiding the need for `liftEff'` / `liftH $ liftEff'` entirely would be preferable, but making instances like the above isn't entirely ideal either - it would be better to provide a `MonadEff` for any `Free` perhaps. I think we discussed adding one at some point, but I don't remember why we didn't do it now.

**Comment by themoritz** [comment]
Alright, I guess I'll be fine for now. The only consequence of keeping the need for `liftH` in parent components is that I have to write an extra "parent version" for some of my helper functions...

**Comment by garyb** [comment]
Yep :( Or actually, wouldn't using `liftH` in front of those just do it?

**Comment by themoritz** [comment]
One such helper is along the lines of
```purescript
apiCall :: Aff a -> (a -> ParentDSL Unit) -> ParentDSL Unit
apiCall call onSuccess = do
  result <- liftH $ liftAff' $ attempt call
  case result of
    Right x -> onSuccess x
    ...
```
But yeah, maybe there are ways of refactoring everything to avoid this. :)

**Comment by garyb** [comment]
Ah right, yeah. Something that might help is avoiding the `ParentDSL` / `ComponentDSL` synonyms too, and use the underlying `Free (HalogenF ...` type instead.

**Comment by jdegoes** [comment]
Related to #221, I think at some point you might be able to write something like:

```purescript
lift <Prism1P> <query>
```

e.g.

```purescript
lift (a >>> b >>> c) doX
```
