### ISSUE TITLE
Subscriptions and attaching event handler via ffi

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#241]
I've written a function that attaches an event handler to an element via ffi
```javascript
exports.attachHandler = function(selector) {
  return function(callback) {
    var el = document.querySelector(selector);
    el.addEventListener("click", callback);
  };
};
```
and am using it with the `eventSource_` function like this:
```purescript
subscribe $ eventSource_ (attachHandler "#fire") do
  log "moo"
  pure $ action ToggleState
```
Now, when I press the button with id `fire`, only "moo" is printed to the console, but the `ToggleState` action is not run.

The complete code (a variation on the "intro" example) can be found here: https://github.com/themoritz/halogen-subscribe

Anyone an idea what I am missing?

**Comment by garyb** [comment]
I think you'll need to add the listener as:
```
el.addEventListener("click", function (e) {
  callback(e)();
});
```
As callback is in `Eff`

**Comment by themoritz** [comment]
Not quite, but you got me on the right track:
```javascript
exports.attachHandler = function(selector) {
  return function(callback) {
    return function() {
      var el = document.querySelector(selector);
      el.addEventListener("click", callback);
    };
  };
};
```
works.

Thanks! :dancer:

**Comment by garyb** [comment]
Ah, that's the one! :+1:
