### ISSUE TITLE
SubscribeF and parent components

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#242]
@jonsterling 

Trying to free up `subscribe` / `EventSource` so we can use it in parent components (see #234) is proving troublesome.

Currently `EventSource` can only be used in a useful way when `g ~ Aff` partially due to `produce` from `Control.Coroutine.Aff`, but really there's not much else that makes sense if we build the coroutine here. This doesn't work for parent components as they force `g ~ QueryF`.

I thought one fix would be just to capture the arguments we construct the `EventSource` with and defer the coroutine construction until we're interpreting it, as then we don't force `Aff` everywhere - it happens at the end, which is fine, as it has to be `Aff` there anyway for `runUI`. The problem with that is the row of effects need to go somewhere:

``` purescript
data EventSourceF f eff a
  = EventSourceF ((a -> Eff eff Unit) -> Eff eff Unit) (a -> Eff eff (f Unit))

-- Also need to hide the `a`, but there's no problem here
newtype EventSourceE f eff = EventSourceE (Exists (EventSourceF f eff))
```

We don't want to add an additional type variable to `Component` to capture these effects as it'll make the types even worse than they already are, and there will be duplication as the row will usually be present in a component's `g` as well.

So I figured I'd use existential hiding (and `unsafeInterleaveEff` later... :cry:), but I _think_ this is safe, because we can ensure that the existential version it has to be constructed like this: 

``` purescript
subscribe :: forall s f g eff. (MonadEff eff g) => EventSourceE f eff -> Free (HalogenF s f g) Unit
subscribe = ...
  -- there's a mkExists thing in here that disappears the `eff`, but because of
  -- the constraint we know that `g` must be able to deal with them
```

However, I'm not sure this is safe: we can re-interpret a component's `g`, so there's no guarantee that future `g`s will represent the effects we hid here. But then maybe it's not a problem as `Eff`'s rows are additive (excluding ST and other FFI hacks to remove effects)?

**Comment by jonsterling** [comment]
Thanks for writing this up. I'm still trying to think through it, but when I glanced at your last sentence I became a little concerned. If safety relies on rows being strictly additive, I don't think that we can exclude things like ST or FFI hacks. Typing is a semantic / extrinsic property, and the particular set of rules which gives rise to the behavior of effect rows in the typechecker is a somewhat arbitrary approximation of the semantic typing relation. An FFI hack is a way to add a new rule to the syntax/proof theory which is sound wrt. the semantics; there are numerous cases where removing an item from an effect row is a valid thing to do, even if it's not treated in the built-in proof theory.

I guess my concern is whether your proposal is essentially predicated on the assumption that the inductive definition of effect typing which is in the type checker is actually complete for the intended semantics of the language (which it cannot be).

**Comment by garyb** [comment]
That's exactly my worry too, but I thought about it a bit more after writing that, I'm not sure considering the behaviour of effect rows is actually helpful here after all: we `interpret` a component by providing a natural transformation, therefore I if I understand correctly, it is definitely safe as any `g'` we end up with has to have a mapping from `g`.

**Comment by jonsterling** [comment]
OK, I think that makes sense.

Could you show me where you would have to unpack this existential and use `unsafeInterleaveEff`?

**Comment by garyb** [comment]
I haven't worked that bit out yet, I'll put something together now. I'm thinking it will be in the driver/`runUI` though, as that's where we'll build the coroutine based on the functions that the `EventSource` originally captured.

**Comment by garyb** [comment]
Ok, here's the plan:

``` purescript
data EventSourceF f eff a
  = EventSource ((a -> Eff eff Unit) -> Eff eff Unit) (a -> Eff eff (f Unit))
  | EventSource_ (Eff eff Unit -> Eff eff Unit) (Eff eff (f Unit))

newtype EventSourceE f eff = EventSourceE (Exists (EventSourceF f eff))

-- this will only have the smart constructor/deconstructor exported so we can
-- maintain the relationship between `g` and the original `eff`
newtype EventSource2 f (g :: * -> *) = EventSource2 (ExistsRE (EventSourceE f))

mkEventSource2 :: forall f g eff. (MonadEff eff g) => EventSourceE f eff -> EventSource2 f g
mkEventSource2 = EventSource2 <<< mkExistsRE

runEventSource2 :: forall f g eff. (MonadEff eff g) => EventSource2 f g -> EventSourceE f eff
runEventSource2 (EventSource2 x) = runExistsRE coerceEffects x
  where
  coerceEffects :: forall fff. EventSourceE f fff -> EventSourceE f eff
  coerceEffects = U.unsafeCoerce

makeItSo
  :: forall f eff
   . CR.Consumer (f Unit) (Aff (avar :: AVAR | eff)) Unit
  -> EventSource2 f (Aff (avar :: AVAR | eff))
  -> Aff (avar :: AVAR | eff) Unit
makeItSo c es2 =
  SCR.runStallingProcess (runEventSourceE (runEventSource2 es2) $$? c) $> unit
  where
  runEventSourceE :: EventSourceE f (avar :: AVAR | eff) -> EventSource f (Aff (avar :: AVAR | eff))
  runEventSourceE (EventSourceE esf) = runExists runEventSourceF esf
  runEventSourceF :: forall a. EventSourceF f (avar :: AVAR | eff) a -> EventSource f (Aff (avar :: AVAR | eff))
  runEventSourceF (EventSource attach handle) = eventSource attach handle
  runEventSourceF (EventSource_ attach handle) = eventSource_ attach handle
```

**Comment by jdegoes** [comment]
Also, not that I'm necessarily recommending it, but you can always define `IO` in PureScript (possibly based on `Aff`), which would support lifting from *any possible set of effects*. Then Halogen could just expect an `IO` at the top level.

**Comment by jonsterling** [comment]
So, one question is—in this setting, if I've already got a coroutine (from some other source), I can't use the `subscribe` machinery anymore to consume it. However, I guess I should be able to just consume it in the normal way from inside `eval` so long as I have got the right effects. Does that sound right?

**Comment by garyb** [comment]
Yeah, that's right. I hadn't realised that earlier, but that's exactly what you're doing with the file input, isn't it? The case I was trying to solve with this (updating a tick on an interval) can probably also be done with the direct coroutine approach. This just gains us the ability to `subscribe` in parent components.

**Comment by jonsterling** [comment]
Cool; I think it sounds good then! Now that I think of it, directly using the coroutine makes more sense in the context I'm doing it anyway.

**Comment by garyb** [comment]
This got fixed at some point, it is now possible to subscribe in parent components.
