### ISSUE TITLE
wrapping a ReaderT around HalogenEffects

### ISSUE THREAD

**Issue by cdepillabout** [slamdata/purescript-halogen#250]
I'd like to use a `Reader`monad in  my `eval` function.  I'd like the types to work out like this:

```purescript
ui :: forall eff . Component State Input (ReaderT Config (Aff (HalogenEffects eff)))
ui = component render eval

render :: Render State Input

eval :: Eval Input State Input (ReaderT Config (Aff (HalogenEffects eff)))
-- eval becomes this:
eval :: forall a . Input a -> Free (HalogenF State Input (ReaderT Config (Aff (HalogenEffects eff)))) a
```

Of course, the `runUI` function would need to be changed as well.  It currently looks like this:

```purescript
runUI :: forall s f eff . Component s f (Aff (HalogenEffects eff))
      -> s
      -> Aff (HalogenEffects eff) { node :: HTMLElement, driver :: Driver f eff }
```

It would have to be changed to something like this (I'm not sure if this type is exactly right, but hopefully you get the idea):

```purescript
runUI :: forall m s f eff . (Monad m)
      => Component s f (m (Aff (HalogenEffects eff)))
      -> s
      -> m (Aff (HalogenEffects eff) { node :: HTMLElement, driver :: Driver f eff })
```

Is there any standard or recommended way of doing this?

Another way of accomplishing the same thing is to encode my reader monad as an extensible effect.  I could have some kind of "readConfig" effect, and my `main` function might look something like this:

```purescript
main = runConfig defaultConfig $ do
    runAff throwException (const (pure unit)) $ do
        { node: node, driver: driver } <- runUI ui initialState
        ...
```

This might be more realistic than changing how `runUI` works?

**Comment by garyb** [comment]
I think you should be able to use [`interpret`](http://pursuit.purescript.org/packages/purescript-halogen/0.5.2/docs/Halogen.Component#v:interpret) to do this. You'd take your component with a `ReaderT` in `g`, and then use `interpret (flip runReaderT myConfig) myComponent`, which would then give you a component compatible with `runUI`.

**Comment by garyb** [comment]
Oh, and by the way, instead of using the `Eval` (etc) synonyms, we introduced some alternatives a while back that are probably better:

``` purescript
render :: s -> ComponentHTML f
eval :: Natural f (ComponentDSL s f g)

render :: s -> ParentHTML s' f f' g p
eval :: Natural f (ParentDSL s s' f f' g p)

-- which also means there is no need for a special peek synonym now:
peek :: forall x. f x -> ParentDSL s s' f f' g p Unit
```

They make it easier to see the nature of the functions, and also are more flexible in what they can express.

**Comment by cdepillabout** [comment]
`interpret` seems to be exactly what I was looking for!  Thanks!

Also, thanks for the heads up about the `render`/`eval` synonyms.  They do make it easier to see what is going on.
