### ISSUE TITLE
App Driver for Parent Components?

### ISSUE THREAD

**Issue by brsunter** [slamdata/purescript-halogen#251]
I'm trying to do something similar to the "Counter" example, where you send queries through the app.driver.

````
main :: Eff (HalogenEffects ()) Unit
main = runAff throwException (const (pure unit)) $ do
  { node: node, driver: driver } <- runUI ui initialState
  onLoad $ appendToBody node
  setInterval 1000 $ driver (action Tick)

````

However, I'm using a parent component instead of a regular component. It has the type signature

````
type StateP g = InstalledState State StoryState Query StoryQuery g StorySlot
type QueryP = Coproduct Query (ChildF StorySlot StoryQuery)


ui :: forall g . (Functor g) => Component (StateP g) QueryP g

````

I'm not able to send queries using ```` driver (action MyAction) ```` in main. The type for the query algebra in my parent component is just Query.

What is the best way to do this?

**Comment by cryogenian** [comment]
Hello!

'driver $ left $ action MyAction' should work. 'left' is used to build QueryP from Query, it lives in 'Data.Functor.Coproduct'

**Comment by brsunter** [comment]
Hey crogenian,
Thank you so much, it worked. I'll work on getting more comfortable with Coproduct.

There are some great examples already but I would love to see one with both Parent Components and Effects/Ajax together. I think the regular component type signatures are manageable, but I'm getting a little tripped up with the parent variations.
