### ISSUE TITLE
Is it possible to create query in another query?

### ISSUE THREAD

**Issue by user471** [slamdata/purescript-halogen#257]
For example, I want to remove task when task's description is changed to "delete"
So, I want to create ```Remove``` query in ```UpdateDescription``` query.
https://github.com/slamdata/purescript-halogen/blob/master/examples/todo/src/Component/Task.purs
Something like this
```
eval (UpdateDescription desc next) = do
    if desc == "delete" then 
       create Remove query
    else    
       modify (_ { description = desc })
    pure next
```

**Comment by cryogenian** [comment]
This is impossible probably. I use this 
```purescript
eval (UpdateDescription desc next) = do 
  if desc == "delete" then 
    remove
  else 
    modify _{description = desc} 
  pure next
eval (Remove next) = do 
  remove 
  pure next

remove :: ParentDSL _ _ _ _ _ Unit
remove = ...
```

**Comment by user471** [comment]
Could you explain how it's working? What does ```remove``` do?

**Comment by wiz** [comment]
Can't you just run `eval (Remove next)` instead of `pure next`?..

**Comment by cryogenian** [comment]
`remove` is just everything you put in `Remove` query interpretation w/o `pure next`. 
@wiz :+1:

**Comment by garyb** [comment]
Yep, you have to do what @cryogenian or @wiz suggest for now, as it's not possible for a component to query itself in the current version.

**Comment by user471** [comment]
>Can't you just run eval (Remove next) instead of pure next?..
it do nothing.
```
eval (Remove next) = pure next
```
Removing is in the parent eval.
https://github.com/slamdata/purescript-halogen/blob/master/examples/todo/src/Component/List.purs#L56

**Comment by user471** [comment]
>Yep, you have to do what @cryogenian or @wiz suggest for now, as it's not possible for a component to query itself in the current version.

But how it affects a parent's eval?

**Comment by garyb** [comment]
Ah ok, that's what the "peek" functionality is for, the parent needs to observe the `UpdateDescription` of the child and then determine whether it should remove it.

**Comment by user471** [comment]
>Ah ok, that's what the "peek" functionality is for, the parent needs to observe the UpdateDescription of the child and then determine whether it should remove it.

I don't want to move this logic in parent because it belong to component.

**Comment by cryogenian** [comment]
Is this ok?

+ Add `NotifyRemove a` entry to query of child component
+ Add `if desc == "remove" then eval (NotifyRemove next) else something else ... `
+ Peek only `NotifyRemove` in parent

**Comment by cryogenian** [comment]
Ah, and in child component eval
```purescript
eval (NotifyRemove next) = pure next
```
Because all logic of removing is located in parent component and this entry is used only for parent notification.

**Comment by garyb** [comment]
@cryogenian That won't work unfortunately, as calling `eval (NotifyRemove ...` in the child won't allow the parent to observe the `NotifyRemove`.

@user471 sorry, that's the way it works for now.

**Comment by user471** [comment]
@garyb How could this scenario work in the future?

**Comment by garyb** [comment]
Components would need to be able to send queries to themselves or their parents. At the moment the behind the scenes plumbing makes this impossible, but @natefaubion has a possible solution in a branch he's started. More discussion here: #245.

**Comment by garyb** [comment]
Closing this as it's not something we're going to specifically address without reworking querying generally, and we already have another issue for that.
