### ISSUE TITLE
External signal

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#26]
Suppose we have something that produce ```r``` or ```i``` in terms of ```runUIEff``` over time. 
How can this producer be integrated to ```runUIEff```? Could you please provide example of using global events which is not raised by user?

**Comment by jdegoes** [comment]
A good example, which should maybe be in Halogen, is a router, which looks at the hash part of the query string and updates the application appropriately.

**Comment by paf31** [comment]
I've added a routing example.
