### ISSUE TITLE
Small Feature Request: Generalize the type of Form Events

### ISSUE THREAD

**Issue by russellmcc** [slamdata/purescript-halogen#263]
Currently, the type of e.g. `onValueInput` is:

```
onValueInput :: forall f. (String -> EventHandler (f Unit)) -> Prop (f Unit)
```

But, it would be more convenient for me to have it be

```
onValueInput :: forall i. (String -> EventHandler i) -> Prop i
```

Since I'm using the DOM DSL without the rest of halogen and I don't use Query functors.  If this wouldn't cause problems for you, I'd be happy to change the types and issue a pull request.

In general, there's enough value in the DOM DSL and virtual dom bindings that it would be great to split it out into a separate project.  The only difficulty there would be generalizing the virtual dom `renderHTML` function.

**Comment by zudov** [comment]
:+1: to generalizing the HTML DSL and splitting it into a separate library.

I've also been using it for purescript-cycle prototype. But since I didn't need handlers or slots, so I could simply do:
```haskell
type CycleHTML = HTML Void (Identity Unit)

renderHTML :: CycleHTML -> VTree
renderHTML = Renderer.renderHTML (pure <<< runIdentity)
```

> The only difficulty there would be generalizing the virtual dom renderHTML function.

How so? It doesn't really depend on anything halogen specific.

**Comment by zudov** [comment]
Speaking of your problem, if you really don't want to have actual query algebras, I think you can just plug `Const` in there, and you would get what you want:

```haskell
onValueInput_ :: forall i. String -> EventHandler i -> Prop i
onValueInput_ event handler =
  getConst <$> onValueInput event (handler <#> \i -> Const i unit)
``` 

(I didn't typecheck this, so you might need to tweek things around, but I hope the intent is clear and I am not completely wrong about that solution)

**Comment by natefaubion** [comment]
I would like to see halogen-html split off as well. The DSL is top-notch, and the correct-by-construction approach is a great showcase for PS. FWIW, I made this same change in #245.

**Comment by jdegoes** [comment]
Splitting off the HTML is probably a good idea, I am happy to create a repo for it under `slamdata` if there's a volunteer to submit PRs for the new repo and for updating halogen.

**Comment by garyb** [comment]
I'm not sure why the `* -> *` version of the type is even used here, so :+1:.

I'll extract things out into `halogen-html`.

**Comment by garyb** [comment]
Halogen's `EventHandler` isn't necessarily something anyone else would want to rely on, is it? It's going to be a little tricky to extract the HTML stuff without parameterising that somehow.

**Comment by russellmcc** [comment]
Speaking for myself, I like the `EventHandler` included with Halogen, and I'd be fine if it were just moved into `halogen-html`.

**Comment by russellmcc** [comment]
`renderHTML` (at least, the virtual DOM version), does depend on a few halogen-specific things, in particular the query algebra system.  You can wrap it with a product functor to use non-query algebra types, so it's not a big problem as-is.  I don't think it would be very difficult to generalize, just not as trivial as the already-general HTML DSL.
