### ISSUE TITLE
`liftEff'` causes program to hang mysteriously

### ISSUE THREAD

**Issue by parsonsmatt** [slamdata/purescript-halogen#264]
In my [QuickLift](https://github.com/parsonsmatt/ql-purs/) project, I'm having a problem where a function call to `liftEff'` is causing the entire program to hang. [This is the code in question](https://github.com/parsonsmatt/ql-purs/blob/master/src/QuickLift.purs#L109-L120):

``` purescript
      eval (UserLogout a) = do
          traceAnyM "before removeItem"
          -- TODO: Figure out why this breaks??
          --liftEff' (WS.removeItem WS.localStorage "auth")
          traceAnyM "after removeItem"
          modify (stCurrentUser .~ Nothing)
          traceAnyM "after mod state"
          modify (stAuthToken .~ Nothing)
          traceAnyM "after mod token"
          eval (Goto Home unit)
          pure a
```

The liberal use of `trace` isolated the issue to the commented out call to `liftEff'`. The WS refers to the [`purescript-webstorage`](https://github.com/joneshf/purescript-webstorage/) library, and the function punts to [this function.](https://github.com/joneshf/purescript-webstorage/blob/master/src/Browser/WebStorage.js#L33-L38)

The webstorage functions all work fine when running in `main`, and I can set/get items without issue using the `liftEff'` functions. I'm at a loss as to why this is breaking things. I'm going to continue to investigate, but figured I'd post here in case someone else has seen it.

**Comment by garyb** [comment]
Hmm. We've used it extensively in slamdata without any trouble, so I suspect there's a problem in occurring in the FFI, although the code you linked to looks like it probably should work, so I'm not too sure what's going on here. Are you sure there's not an uncaught exception occurring or something like that? (it's perhaps running outside of the things that are catchable by `Aff` and is entirely uncaught, or could be caught and hidden hidden by `launchAff` usage or a `const unit` error handler).

**Comment by parsonsmatt** [comment]
I -- don't think so! I'm doing `runAff throwException (\s -> traceAnyM s $> unit) do ...` for my `main` function. Is that the wrong way to catch exceptions?

**Comment by garyb** [comment]
Nope, that's fine. If you insert `console.log`s into the webstorage JS do they appear in the console?

**Comment by parsonsmatt** [comment]
Modifying the JS to look like this:

```javascript
exports.unsafeRemoveItem = function(storage,str) {
  console.log("outer asdf");
  return function(){
    console.log("asdf")
    storage.removeItem(str);
    return {};
  }
};
```

logs `"outer asdf"` but not the inner one when running it from `liftEff'`. When calling it in the main function both get logged.

**Comment by parsonsmatt** [comment]
Alright, I think I've identified the cause.

My `eval` function handles routing with the [`Goto`](https://github.com/parsonsmatt/ql-purs/blob/master/src/QuickLift.purs#L43-L90) action. This has the form `Goto Routes a`. I punt to other handlers using, in this case, `eval (UserLogout unit)`. 

It swallows the code and invokes the error handler (verified via following the execution flow) whenever `liftEff'` is called inside of a nested call to `eval`. So in my case, the following flow was happening:

```purescript
eval (Goto routes next) = do
  -- ...
  when (routes == UserLogout) do
    eval (Logout unit)
  -- ...
  pure next

eval (Logout next) = do
  liftEff' $ ...
  pure next
```

Getting all my `liftEff'` out of nested handlers fixed the issue, and I'll probably change my code around to not require nesting the `eval` calls. I'll try to work up a minimal example if y'all think this is a bug that needs to be fixed. Otherwise, making a tiny mention of it in the docs somewhere is probably a good idea, because this was *hard* to track down!

**Comment by garyb** [comment]
I think this is `Free` doing what it should do, although I'm not totally sure. Probably what you want is something like this instead:

``` purescript
eval (Goto UserLogout next) = eval (Logout next)

eval (Logout next) = do
  liftEff' $ ...
  pure next
```

By `pure next`ing after the `eval` you're making a "dead end", there's a reason we call it `next` in the examples. :smile:

I need to think a bit more about what exactly is happening here to give a less handwavey explanation.

**Comment by parsonsmatt** [comment]
I've been using the `eval (Command unit)` pattern for a while and it has worked just like normal. I thought it was how you're supposed to call it due to a type error that I didn't understand properly. Passing `next` does allow the nested commands to call `liftEff'` without any issues though!

For another data point, `liftAff'` works when calling nested commands with `unit`.

**Comment by garyb** [comment]
> For another data point, `liftAff'` works when calling nested commands with `unit`.

Ok, that's weird!
