### ISSUE TITLE
ClassName and javascript:void

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#27]
could you please add shortcuts for ```javascript:void(0);``` and add functions that get ```String``` and ```[String]``` to define classes, not ```ClassName```.

**Comment by jdegoes** [comment]
Will you still need to define custom class names after Boostrap and other themes have been created? It's better for class names to be semantic, and fixed, rather than ad hoc and unlimited -- this way it's easier for a designer to modify the styles.

**Comment by cryogenian** [comment]
Classnames are not fixed because I can write ```classes $ className <$> ["foo", "bar"]```.
Maybe using it can be discouraged by name ```unsafeClasses``` in example or ```notTypeSafeClasses```

**Comment by jdegoes** [comment]
The main reason to want a string constructor is to create custom class names, right? What's the difference between `ClassName "foo"` and `"foo"`? The former is more to type, but makes it easier to keep things straight with the compiler's help (e.g. accidentally passing a non-classname where a classname is expected).

**Comment by cryogenian** [comment]
Then ```className``` should make correctness checks and returns ```Maybe ClassName```. 
Now it just wraps string in newtype. This is neither typesafe nor comfortable.

**Comment by jdegoes** [comment]
Also for `javascript:void(0);` I assume this is to prevent the default action on `a href` clicks, right?

**Comment by cryogenian** [comment]
```javascript:void(0);``` makes cursor pointer, and make anchor pointing exactly this page with same hash.

**Comment by jdegoes** [comment]
The cursor pointer is easy to do with css: `cursor: pointer`. What is the benefit of a link which points to the same page with the same hash?

**Comment by garyb** [comment]
`preventDefault` is the "proper" way of doing that, it'll cancel the URL change.

**Comment by cryogenian** [comment]
* ```preventDefault```, ```tabindex```, ```cursor:pointer```, ```a:hover {text-decoration: underline}``` 
* ```preventDefault```, ```href="something"```  
* ```javascript:void(0);```
* ```<button class="btn btn-link"></button>```

They all work same way.
