### ISSUE TITLE
Dep error purescript-transformers

### ISSUE THREAD

**Issue by whtoo** [slamdata/purescript-halogen#273]
I try to install purescript-halogen with empty project after pulp init.
then pulp run
it tells
Error found:
at ~/WebRoot/sc/bower_components/purescript-transformers/src/Control/Monad/Reader/Trans.purs line 24, column 1 - line 25, column 1

  Unknown module Data.Distributive

See https://github.com/purescript/purescript/wiki/Error-Code-UnknownModule for more information,
or to contribute content related to this error.

Compiling Control.Monad.Reader.Trans
* ERROR: Subcommand terminated with error code 1

**Comment by garyb** [comment]
Did you manage to sort this out in the end?
