### ISSUE TITLE
`Par` for child queries?

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-halogen#277]
Sometimes you need to issue a bunch of queries to child components (to say refresh some data in a cell). There are no `Par`-like primitives in HalogenF though, so using something like `for_` or `traverse_` will cause them to run one after the other, veeery slowly.

**Comment by codedmart** [comment]
:+1:

**Comment by garyb** [comment]
I ran into this before too, but wasn't really sure how best to express it. Including combinators like these implies that `g` always needs to have a `MonadPar` instance or something like that. Also we don't have `MonadPar` yet... purescript/purescript-parallel#2
