### ISSUE TITLE
No module docs on Pursuit?

### ISSUE THREAD

**Issue by liamcurry** [slamdata/purescript-halogen#279]
There's a link in the readme for module documentation on Pursuit: https://pursuit.purescript.org/packages/purescript-halogen

This is currently 404 for me. Searching for `purescript-halogen` or `halogen` also yields 0 results: https://pursuit.purescript.org/search?q=purescript-halogen

**Comment by garyb** [comment]
Unfortunately there's a bug in the configuration of Pursuit that prevents them from uploading currently: purescript/pursuit#189

**Comment by garyb** [comment]
I'll keep this issue open though, as it is something worth tracking.

**Comment by hdgarrood** [comment]
Fixed now :)

**Comment by garyb** [comment]
Nice, thanks!

**Comment by hdgarrood** [comment]
Although the current auto-publish setup will break in the same way, so that will want changing. Here's an example script that uses the new gzipped request body feature: https://github.com/hdgarrood/dotfiles/blob/master/bin/upload-pursuit

**Comment by garyb** [comment]
Ah okay, thanks. Should that be mentioned [in here](https://pursuit.purescript.org/help#submit-automated) too perhaps?

**Comment by hdgarrood** [comment]
Yeah, good idea.
