### ISSUE TITLE
Cancel pending evals?

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-halogen#281]
Sometimes a particular eval branch can take a little while to resolve if there are a lot of Aff calls or maybe an Aff call that can block indefinitely (if its say polling for some data in a loop). In the meantime an input may come in that invalidates a potentially pending eval. The only thing I can think of within the current framework would be to use an event subscriber + `runAff`. Then when it completes, it would push a new input to eval. The problem is that event subscribers cannot be cancelled, and `runAff` does not return a canceler. The only way to get a hold of a canceler would be to use `forkAff`, but then that particular forked `Aff` would not be able to feed the driver when it's done.

**Comment by garyb** [comment]
The `subscribe`+`runAff` approach is exactly what we're doing in SlamData and it works pretty well:

https://github.com/slamdata/slamdata/blob/00539c8d2e24d754c329364529de12d53da9a7e3/src/SlamData/Notebook/Cell/Common/EvalQuery.purs#L196-L211

Did you have an idea for how else this might be solvable?

**Comment by natefaubion** [comment]
That's a good example. I was thinking something along the lines of

```purescript
forkQuery
  :: forall a s f eff
   . (a -> Action f)
  -> Aff eff a
  -> ComponentDSL s f (Aff eff (Canceler eff))
forkQuery action aff = do
  v <- liftAff makeVar
  canceler <- liftAff $ forkAff do
    res <- aff
    putVar v res
  subscribe
    $ EventSource
    $ SCR.producerToStallingProducer
    $ produce \emit -> do
      res <- takeVar v
      emit $ E.Left $ action res unit
      emit $ E.Right unit
  pure canceler
```
```purescript
eval (Something next) = do
  canceler <- forkQuery Completed someAff
  put _ { canceler }
  pure next
eval (Completed val next) = do
  ...
```

This is one of those things that just feels very non obvious because it requires a lot of knowledge of other things that aren't really Halogen related. I'm totally fine with this pattern, but I'd like to see where we could at least document stuff like this, as it is not uncommon.
