### ISSUE TITLE
Extending Properties and Events

### ISSUE THREAD

**Issue by trilogysci** [slamdata/purescript-halogen#285]
Is it possible to extend properties and events? I created the following events and properties
but when I go to use the draggableI  it gives me an error.
```purescript
H.span
      [ P.classes [B.btn, B.btnLg, B.btnDefault]
      , DD.draggableI true
      ]
```

```purescript
onDrop :: forall i. EventProp EventDrag i
onDrop = handler (eventName "ondrop")

onDropI :: forall r i. IEventProp (onDrop :: I | r) EventDrag i
onDropI = unsafeCoerce onDrop

-- Draggable property

draggable :: forall i. Boolean -> Prop i
draggable = prop (propName "draggable") (Just $ attrName "draggable")

draggableI :: forall r i. Boolean -> IProp (draggable :: I | r) i
draggableI = unsafeCoerce draggable

```
```
  Could not match type

    ( draggable :: I
    | _1
    )

  with type

    ( onContextMenu :: I
    , finalizer :: I
   ...
  )
```

**Comment by garyb** [comment]
As you're using the indexed html and properties, then no it's not really possible to extend things this way. The closest you can do is leave the row unspecified in your custom properties like so:

``` purescript
draggableI :: forall r i. Boolean -> IProp r i
```

This does mean you can apply the property to any element so you're giving up the assistance that the indexed properties offer when it comes to ensuring properties are only attached to the relevant elements, but I dont really think we have a way around that.

Sorry about the delayed response!

**Comment by garyb** [comment]
If it helps at all the next release will have `draggable` and `DragEvent` handlers as part of the API.
