### ISSUE TITLE
The project is lacking a proper "Hello World".

### ISSUE THREAD

**Issue by MaiaVictor** [slamdata/purescript-halogen#286]
The introduction starts with a widget but no hello world. There are simple apps on the `examples` directory, like `counter`. But, if you open it, you see a very long, unexplained `gulpfile.js` (I never used `gulp`, but do I need to write all that for a hello world?). There is no way to build the example independently from the root directory. `pulp build` doesn't work. The root directory has an even longer `gulpfile.js`, a `package.json` with tons of deps, a `bower.json` with more deps. It is not obvious how I'm supposed to create a "Hello World" with the minimal amount of code, starting from an empty directory...

**Comment by wiz** [comment]
https://github.com/slamdata/purescript-halogen-bootstrap

**Comment by garyb** [comment]
https://github.com/slamdata/purescript-halogen-template

**Comment by garyb** [comment]
Closing this as there's the template project above ^, and in the next soon-to-be-released version everything uses pulp rather than gulp, and the examples have been set up so they can be run as individual projects.

**Comment by MaiaVictor** [comment]
@garyb sorry for not answering, I forgot. The template worked very well. Please make it more visible! 

Thank you.

**Comment by garyb** [comment]
No problem, and will do in the revised README!
