### ISSUE TITLE
Simpler combinators for slot/query/state unions, child paths, etc

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-halogen#290]
I think everyone knows that dealing with the `Either/Coproduct` stuff with parent components is a bit of a chore. I think at one point @garyb played with the idea of using `either2of3` and `coproduct1of4` style combinators. I actually don't think that's a terrible approach, but the main problem with that is it isn't extensible, so when you go to add another data type you have to update all of your combinators.

One idea is if, instead of using the equivalent of this (which causes the extensibility issues):

``` purescript
type Either4 a b c d= Either a (Either b (Either c d))
```

We did this:

``` purescript
type Either4 a b c d = Either a (Either b (Either c (Either d Void)))
```

Where you use `Void` as a nil-type (and likewise `Const Void` for `Coproduct`). You could then define extensible injector/projectors polymorphic over the "tail".

``` purescript
inj3 :: forall a b c z. c -> Either a (Either b (Either c z))
prj3 :: forall a b c z. Either a (Either b (Either c z)) -> Maybe c
```

If we look at slots, and you are using the child path machinery, your slots are mostly unit types. Or if you have a list of some type of component, it will be indexed by an id of some sort (almost always an Int, Number, String). These means that 98% of the time, we don't actually need to define our own slot types, because the `Either` spine is really what we care about.

``` purescript
-- Unit slot (use inj3 for an indexed slot)
at3 :: forall a b z. Either a (Either b (Either Unit z))
```

I think this could eliminate a lot of boilerplate around defining `ChildPath`s. Since they are extensible you don't need to rewrite the names if you add a new data type, and you can just use them inline (the type inference should just work out).

**Comment by garyb** [comment]
Pretty neat! We'd perhaps want corresponding `fold3` (or something) functions too, to replace the likes of `coproduct3` in eval/peek situations, so the `Void` case is omitted.

And yeah, we use the `NofX` stuff in a few places in SlamData, I didn't think it was necessarily something we should encourage though as it's probably better to use a custom sum type to avoid the deep hierarchy. It's definitely useful though, so we can always caveat the provided `atN` functions with that notice.

**Comment by jdegoes** [comment]
Good idea, and possibly a reason to revisit `Data.Either.Nested` and add a right-associated option that follows this pattern (and of course similar for `Coproduct`).
