### ISSUE TITLE
Examples: Browserify cannot find module 'virtual-dom/diff'

### ISSUE THREAD

**Issue by berdario** [slamdata/purescript-halogen#310]
I'm trying to get started with Purescript+Halogen just now, but I get this error when running `npm run example-counter` or `npm run example-ajax`:

    * Build successful.
    * Browserifying...
    events.js:141
          throw er; // Unhandled 'error' event
          ^
    
    Error: Cannot find module 'virtual-dom/diff' from '/home/dario/Projects/purescript-halogen/examples/ajax/output'
        at /home/dario/.local/lib/node_modules/pulp/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
        at process (/home/dario/.local/lib/node_modules/pulp/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
        at ondir (/home/dario/.local/lib/node_modules/pulp/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
        at load (/home/dario/.local/lib/node_modules/pulp/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
        at onex (/home/dario/.local/lib/node_modules/pulp/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
        at /home/dario/.local/lib/node_modules/pulp/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
        at FSReqWrap.oncomplete (fs.js:82:15)
    
    npm ERR! Linux 4.4.0-22-generic
    npm ERR! argv "/nix/store/xqdq16rvadslcjcc1xb4qp4ss49idc8f-nodejs-4.3.1/bin/node" "/home/dario/.nix-profile/bin/npm" "run" "build"
    npm ERR! node v4.3.1
    npm ERR! npm  v2.14.12
    npm ERR! code ELIFECYCLE
    npm ERR! @ build: `pulp browserify --optimise --to dist/example.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the @ build script 'pulp browserify --optimise --to dist/example.js'.
    npm ERR! This is most likely a problem with the  package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     pulp browserify --optimise --to dist/example.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls 
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/dario/Projects/purescript-halogen/examples/ajax/npm-debug.log
    
    npm ERR! Linux 4.4.0-22-generic
    npm ERR! argv "/nix/store/xqdq16rvadslcjcc1xb4qp4ss49idc8f-nodejs-4.3.1/bin/node" "/home/dario/.nix-profile/bin/npm" "run" "example-ajax"
    npm ERR! node v4.3.1
    npm ERR! npm  v2.14.12
    npm ERR! code ELIFECYCLE
    npm ERR! purescript-halogen@ example-ajax: `bower link && cd examples/ajax && bower link purescript-halogen && bower install && npm run build`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the purescript-halogen@ example-ajax script 'bower link && cd examples/ajax && bower link purescript-halogen && bower install && npm run build'.
    npm ERR! This is most likely a problem with the purescript-halogen package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     bower link && cd examples/ajax && bower link purescript-halogen && bower install && npm run build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls purescript-halogen
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/dario/Projects/purescript-halogen/npm-debug.log
    dario@curie ~/P/purescript-halogen (master%) [1]> 
    cat /home/dario/Projects/purescript-halogen/npm-debug.log
    0 info it worked if it ends with ok
    1 verbose cli [ '/nix/store/xqdq16rvadslcjcc1xb4qp4ss49idc8f-nodejs-4.3.1/bin/node',
    1 verbose cli   '/home/dario/.nix-profile/bin/npm',
    1 verbose cli   'run',
    1 verbose cli   'example-ajax' ]
    2 info using npm@2.14.12
    3 info using node@v4.3.1
    4 verbose run-script [ 'preexample-ajax', 'example-ajax', 'postexample-ajax' ]
    5 info preexample-ajax purescript-halogen@
    6 info example-ajax purescript-halogen@
    7 verbose unsafe-perm in lifecycle true
    8 info purescript-halogen@ Failed to exec example-ajax script
    9 verbose stack Error: purescript-halogen@ example-ajax: `bower link && cd examples/ajax && bower link purescript-halogen && bower install && npm run build`
    9 verbose stack Exit status 1
    9 verbose stack     at EventEmitter.<anonymous> (/nix/store/xqdq16rvadslcjcc1xb4qp4ss49idc8f-nodejs-4.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
    9 verbose stack     at emitTwo (events.js:87:13)
    9 verbose stack     at EventEmitter.emit (events.js:172:7)
    9 verbose stack     at ChildProcess.<anonymous> (/nix/store/xqdq16rvadslcjcc1xb4qp4ss49idc8f-nodejs-4.3.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
    9 verbose stack     at emitTwo (events.js:87:13)
    9 verbose stack     at ChildProcess.emit (events.js:172:7)
    9 verbose stack     at maybeClose (internal/child_process.js:821:16)
    9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    10 verbose pkgid purescript-halogen@
    11 verbose cwd /home/dario/Projects/purescript-halogen
    12 error Linux 4.4.0-22-generic
    13 error argv "/nix/store/xqdq16rvadslcjcc1xb4qp4ss49idc8f-nodejs-4.3.1/bin/node" "/home/dario/.nix-profile/bin/npm" "run" "example-ajax"
    14 error node v4.3.1
    15 error npm  v2.14.12
    16 error code ELIFECYCLE
    17 error purescript-halogen@ example-ajax: `bower link && cd examples/ajax && bower link purescript-halogen && bower install && npm run build`
    17 error Exit status 1
    18 error Failed at the purescript-halogen@ example-ajax script 'bower link && cd examples/ajax && bower link purescript-halogen && bower install && npm run build'.
    18 error This is most likely a problem with the purescript-halogen package,
    18 error not with npm itself.
    18 error Tell the author that this fails on your system:
    18 error     bower link && cd examples/ajax && bower link purescript-halogen && bower install && npm run build
    18 error You can get their info via:
    18 error     npm owner ls purescript-halogen
    18 error There is likely additional logging output above.
    19 verbose exit [ 1, true ]

Pulp version 8.2.1
psc version 0.8.5.0 
node v4.3.1

This might not be a bug with purescript-halogen, but maybe rather with pulp, or browserify... but since I'm quite new I cannot pinpoint it

**Comment by garyb** [comment]
Did you install `virtual-dom` with `npm` too? Please see this note about it in the README: https://github.com/slamdata/purescript-halogen#installation

**Comment by berdario** [comment]
Uhm, I'm trying out the example projects, which are supposed to already have `virtual-dom` in their package.json

https://github.com/slamdata/purescript-halogen/blob/master/examples/counter/package.json#L7

And from my understanding, bower/pulp should fetch the dependencies for me. Is there some other manual step that I'm missing?

**Comment by garyb** [comment]
Bower is used to manage dependencies in PS-land, but unfortunately `virtual-dom` is not listed as a bower dependency, and can't be as it's not published on bower. An additional `npm install` step is needed, and if you're using Halogen in your own projects then it will need adding to a `package.json` manually too so it's listed as a dependency there.

It really sucks, but unfortunately there's not much we can do about it as long as we rely on `virtual-dom` and use the current tools we do for package management.

**Comment by berdario** [comment]
Oh.

Yeah, that's clear. I mistakenly believed that bower was able to also fetch stuff specified inside the `package.json` (I'm not much of a frontend guy and I'm new to all this)

Thanks for explaining this.

**Comment by garyb** [comment]
No problem! The current situation is pretty poor, we just don't have a good solution for it yet. There's a whole rabbit-hole of discussions about how we should manage dependencies for PS ("just use npm" is often suggested, [but we can't](http://harry.garrood.me/blog/purescript-why-bower/)), it seems like maybe we do need yet another package manager, but for now bower is just about good enough in most situations.
