### ISSUE TITLE
Elements get their width/height set to auto

### ISSUE THREAD

**Issue by gurgl** [slamdata/purescript-halogen#312]
Purescript 0.9.1
Halogen: Master head today

Trying to learn Purescript Halogen here. 

I extended the example/todo in purescript-halogen source tree with some SVG elements. Sadly the svg tag magically get its width/height set to auto through javascript. Even though i managed to set attributes on the very tag. Have no clue why but maybe purescript/halogen has some internal view on dimensions and these arent reflected because svg in another namespace? To run. Just replace List.purs in original "todo" example and add SVG.purs.

https://gist.github.com/gurgl/7ce06112f925635afb360e96dce867f3

**Comment by aqui8** [comment]
I'm creating svgs with the namespace on each element and setting the namespace for the props to Nothing and the widths and heights seem to be working for me.
```
ns = (Just (namespace "http://www.w3.org/2000/svg"))
svg = Element ns (tagName "svg")
width = Attr Nothing (attrName "width") <<< printLengthLiteral

...

svg [ width (Pixels 400), height (Pixels 100 ) ] [
        circle [ r (Pixels 10) ]
]

```

**Comment by natefaubion** [comment]
@aqui8: `width` needs to be `Attr ns ...`

**Comment by aqui8** [comment]
Ah so it is a bug?
If I add a namespace to attributes, it throws an exception.
`Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'http://www.w3.org/2000/svg:width' is not a valid attribute name`

**Comment by natefaubion** [comment]
@aqui8: I mean that you need to give the `Maybe Namespace` you created for `svg` as the first argument to `Attr` rather than giving it `Nothing`. That `Nothing` is the namespace for the attribute. So you should be using:

```purescript
width = Attr ns (attrName "width") <<< printLengthLiteral
```

As far as I know others have had success with this in the past.

**Comment by aqui8** [comment]
@natefaubion yup - thats what I mean. Unless I'm doing something else wrong.

**Comment by garyb** [comment]
I'm going to close this as I don't think it's a problem with Halogen per se. I think there is a library out there that provides SVG elements/attributes/etc. now too.
