### ISSUE TITLE
Use snabbdom as render instead of virtual-dom

### ISSUE THREAD

**Issue by leiserfg** [slamdata/purescript-halogen#314]
snabbdom is faster, lighter and has internal suport for animations. Nowdays cycle is using this library.

**Comment by jdegoes** [comment]
PR coming soon, I hope? 😉

**Comment by garyb** [comment]
Looks interesting, thanks for the heads up!

**Comment by eskimor** [comment]
Alex Mingoia researched some more alternatives: https://github.com/alexmingoia/purescript-pux/issues/45#issuecomment-229181252

**Comment by natefaubion** [comment]
Since we build an intermediate `HTML` representation anyway for our own uses, maybe it makes sense to use something like `incremental-dom` to directly interpret it into DOM updates rather than into another virtual representation.

**Comment by garyb** [comment]
Closing this now as there was a similar discussion recently in #350. Hopefully we'll just be providing a driver for https://github.com/slamdata/purescript-halogen-vdom with Halogen, and then can have other projects for React/virtual-dom/snabbdom/etc drivers for those who prefer to use them.
