### ISSUE TITLE
support purescript-css for defining css styles

### ISSUE THREAD

**Issue by jdegoes** [slamdata/purescript-halogen#32]

**Comment by paf31** [comment]
Yes, [Clay](http://hackage.haskell.org/package/clay) looks like it might be a nice library to look at.

**Comment by paf31** [comment]
This seems like it would make a nice external library too.

**Comment by natefaubion** [comment]
https://medium.com/@jviereck/modularise-css-the-react-way-1e817b317b04 a neat approach

**Comment by puffnfresh** [comment]
@natefaubion that article has a really good idea in it. I think the possibility of generating a production CSS file would not be possible for this project but the VirtualCSS stuff is really great.

:+1:

**Comment by jdegoes** [comment]
Most likely built on [purescript-css](slamdata/purescript-css).

**Comment by paf31** [comment]
@jdegoes @puffnfresh How does this look?

If this looks ok, could you please set up a repo, and I'll send a PR. Thanks.

**Comment by jdegoes** [comment]
@paf31 How does what look???

**Comment by garyb** [comment]
> @paf31 How does what look???

It's not just me then :grinning:

**Comment by jdegoes** [comment]
:laughing:

**Comment by paf31** [comment]
Ugh sorry.

https://github.com/paf31/purescript-halogen-css

**Comment by puffnfresh** [comment]
@paf31 really nice!

**Comment by jdegoes** [comment]
Yes, this looks great! Can you integrate this into halogen instead of creating a separate project? From a performance and usability standpoint, it doesn't make a ton of sense to unpack from `Css` to `StrMap String` to vdom, when Halogen can simply directly use `purescript-css` -- any blockers you see with that approach?

**Comment by paf31** [comment]
My only concern was that `purescript-css` didn't have a versioned release, so I wasn't sure if the API was stable or not. If it is, can we please make a release and I'll merge it over.

**Comment by jdegoes** [comment]
^^^ @puffnfresh If it's stable please do a release, otherwise please tell us what needs to happen to make it stable and hopefully @paf31 can knock those things off. :smiley:
