### ISSUE TITLE
form-related IProp combinators

### ISSUE THREAD

**Issue by LightAndLight** [slamdata/purescript-halogen#320]
There is currently no way to set a form's `action` or `method` using `Halogen.HTML.Indexed`.

I can get them in this week, but what should we call `action`? The name will clash with `Halogen.Query`.

**Comment by garyb** [comment]
Probably `action` is fine, since I'd be surprised if people are importing any of the `Halogen.HTML` stuff without qualifying the module. I don't think it should conflict anyway, as action is `H.action` whereas this would be `P.action` or `HP.action` using the normal conventions.
