### ISSUE TITLE
Rename `Halogen.HTML.Indexed` to `Halogen.HTML`

### ISSUE THREAD

**Issue by menelaos** [slamdata/purescript-halogen#322]
Since it is recommended to use the indexed variants

``` purescript
import Halogen.HTML.Indexed as HH
import Halogen.HTML.Events.Indexed as HE
import Halogen.HTML.Properties.Indexed as HP
```

wouldn't it make sense to rename those modules to

``` purescript
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.HTML.Properties as HP
```

and use the longer form for the non-indexed (and probably lesser-used) variants?

``` purescript
import Halogen.HTML.NonIndexed as HH
import Halogen.HTML.Events.LessSafe as HE
import Halogen.HTML.Properties.WhatEver as HP
```

**Comment by garyb** [comment]
That makes sense, we could possibly do away with the unindexed varieties entirely - it was a sort of experiment at first, but doesn't seem to have any drawbacks really, aside from it being a breaking change every time we need to add something :wink:
