### ISSUE TITLE
No compatible version found: pulp@^9.1.0 for examples.

### ISSUE THREAD

**Issue by philderbeast** [slamdata/purescript-halogen#327]
When trying the multicomponent example, I found ...

No compatible version found: pulp@^9.1.0
Valid install targets:
9.0.1, 9.0.0, 8.2.1, 8.2.0, 8.2.0-rc.3, etc

**Comment by philderbeast** [comment]
I have pulp installed globally. Looking at the pulp repo, the latest tag I see is 9.0.1.

npm list -g --depth=0

+-- pulp@9.0.1
+-- purescript@0.10.1
+-- purescript-psa@0.3.9

**Comment by garyb** [comment]
Yeah, it's a mistake - it should be 9.0.1.
