### ISSUE TITLE
npm run example-multi-component unable to find virtual-dom

### ISSUE THREAD

**Issue by philderbeast** [slamdata/purescript-halogen#328]
On windows, when I run the readme provided command to build the multicomponent example from the repo root ...

```
>npm run example-multi-component

Error: Cannot find module 'virtual-dom/patch'
```

It fails, unable to find the virtual-dom. If I npm install before pulp browserify, I get around this problem.

```
  "scripts": {
    "build": "npm install && pulp browserify --optimise --to dist/example.js"
  }
```

**Comment by philderbeast** [comment]
I see now that the readme in the examples root says to `npm install` but this can be missed easily when looking at an individual example.

**Comment by garyb** [comment]
I've updated the readmes of the examples to include this info now.
