### ISSUE TITLE
Split out Themes package?

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#33]
They're pretty big and users will probably only need one, if any.

**Comment by garyb** [comment]
:+1:

**Comment by cryogenian** [comment]
:+1:

**Comment by paf31** [comment]
@jdegoes I've split these out, would you like to create separate repos for them, or leave this as-is?

**Comment by paf31** [comment]
I think I'd probably prefer to keep them together, since we can use one build to type check everything together, but we could release them as separate packages on Bower obviously.

**Comment by jdegoes** [comment]
Sounds good, I think that makes sense for now.

**Comment by jdegoes** [comment]
Oh, we should consider the idiomatic way to use these themes now that they're separated out.
