### ISSUE TITLE
Delete `EventHandler`?

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#339]
Strictly speaking we don't need it, as we could capture the event and pass it back to `eval` via query, and then `preventDefault` or whatever there instead. This would also make event handling for elements exactly the same as message handling for child components.

The downside is it's less convenient when one does want to `preventDefault` or whatever, as the effect has to appear in `m` in some form - whether that's `Eff` / `Aff` or something algebraic interpreted later on.

Thoughts? /cc @natefaubion, @cryogenian, @beckyconning, @jdegoes

**Comment by natefaubion** [comment]
I think we should keep it. I don't like the idea of having Aff/Eff/HalogenM in the DOM handler.

**Comment by garyb** [comment]
I'm not sure I follow? When removed, `handler` just drops the `EventHandler` part:

``` purescript
data HandlerF i fields = HandlerF (EventName fields) (Event fields -> EventHandler (Maybe i))
handler :: forall fields i. EventName fields -> (Event fields -> EventHandler (Maybe i)) -> Prop i
```

Becomes:

``` purescript
data HandlerF i fields = HandlerF (EventName fields) (Event fields -> Maybe i)
handler :: forall fields i. EventName fields -> (Event fields -> Maybe i) -> Prop i
```

It still just maps an event being raised to a query, only now you can't `preventDefault` (etc) before raising the query, you'd do that in the `eval` for the query instead.

**Comment by garyb** [comment]
Also 

``` purescript
input :: forall f a. (a -> Action f) -> a -> EventHandler (Maybe (f Unit))
input f x = pure $ Just $ action (f x)

input_ :: forall f a. Action f -> a -> EventHandler (Maybe (f Unit))
input_ f _ = pure $ Just $ action f
```

Become

``` purescript
input :: forall f a. (a -> Action f) -> a -> Maybe (f Unit)
input f x = pure $ Just $ action (f x)

input_ :: forall f a. Action f -> a -> Maybe (f Unit)
input_ f _ = pure $ Just $ action f
```

Which means they can be used for message handling child components too.

**Comment by natefaubion** [comment]
> Which means they can be used for message handling with child components too.

Oh that's a great point. I assume you'd just use purescript-dom then if you need to do anything with it? The only thing I _don't_ like about this is it means you pretty much _have_ to have `MonadEff` in this case and your eval has to be concerned with DOM effects. I like the uniformity though.

**Comment by garyb** [comment]
Yeah exactly. That's what I meant by:

> The downside is it's less convenient when one does want to preventDefault or whatever, as the effect has to appear in m in some form - whether that's Eff / Aff or something algebraic interpreted later on.

**Comment by beckyconning** [comment]
I'm in favour of getting rid of it. Preventing default browser actions or stopping propagations are actions of the component and so to me it makes sense that those should be represented in the component's query algebra and evaluated by the component's evaluator.

**Comment by garyb** [comment]
See #340 for what this change would look like, from the implementation point of view at least.
