### ISSUE TITLE
Boolean attributes

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#34]
```{foo: true}``` adds attribute ```foo``` without value in virtual-dom. ```{foo: false}``` removes it. 
This behaviour is simple and very helpful with ```disabled``` fields.

**Comment by paf31** [comment]
Right now, I'm using the equivalent of `{ disabled: "disabled" }` which seems to work fine, and they're behind smart constructors anyway. But this is definitely more elegant and easier to traverse, so yes, let's add this.
