### ISSUE TITLE
Unable to compile under psc 0.10.x

### ISSUE THREAD

**Issue by ThomasCrevoisier** [slamdata/purescript-halogen#349]
Hi !

When trying to use the lib in a project I encounteed some errors :
```
// error in Control.Monad.Rec.Class
Unknown value U.unsafeCoerceEff

// Error in Control.Monad.Cont.Trans
Connot import type class MonadAsk from module Control.Monad.Reader.Class
```

I'm on MacOS (don't know if it is relevant, but I managed to make it work on Arch Linux), using `psc 0.10.2`.

**Comment by garyb** [comment]
Looks like you're using it in a project with outdated dependencies - or if you don't have any other dependencies, try deleting `bower_components` and `bower i` again. Both of the above changes were made in the core libraries when they were updated for PureScript 0.10.

**Comment by ThomasCrevoisier** [comment]
Seems weird, I deleted the cache of bower, removed `bower_components` and reinstalled deps but still have the problem.

Here is the dependencies pulled by the project :
```
  "dependencies": {
    "purescript-halogen": "^0.12.0",
    "purescript-ace-halogen": "^4.0.0",
    "ace-builds": "^1.2.2"
  }
```

Here are the deps installed :
```
purescript-halogen : 0.12.0
purescript-eff : 2.0.0
purescript-transformers : 2.0.2
```

**Comment by garyb** [comment]
Huh, yeah they all look fine. Tried clearing `output` too?

**Comment by ThomasCrevoisier** [comment]
That is indeed one thing I forgot ^^ Works fine afterwards :) I'll close the issue ^^

Just by curiosity, what is generated in `output/` is handled by the compiler ?

**Comment by garyb** [comment]
The `externs.json` files, and generated javascript for each module is stored in there - the compiler reads the externs back in so that compiles can be done incrementally rather than having to recompile the whole project every time. It's supposed to notice when things go out of date and rebuild in those cases though, so not sure why that wasn't happening here!

**Comment by ThomasCrevoisier** [comment]
I'll try to reproduce this and report this issue on the compiler repo :)

Thanks a lot for your help !
