### ISSUE TITLE
Calling external JS on a component after render

### ISSUE THREAD

**Issue by BartAdv** [slamdata/purescript-halogen#356]
Hi,

So I've attempted to use material design lite, which needs the component to be "upgraded" after being rendered into DOM via simple call to `componentHandler.upgradeElement`.

I've prepared a component with `ref`, so that I can get a hold of an element after it's rendered:

```
HH.div
      [ HP.id_ "cmp-div"
      , HP.ref (HE.input Initialize)
      , HP.classes [HH.ClassName "mdl-textfield", HH.ClassName "mdl-js-textfield", HH.ClassName "mdl-textfield--floating-label"] ]
      [ HH.input
        [ HP.id_ "roleName"
        , HP.inputType (HP.InputText)
        , HP.value state.roleName
        , HE.onValueInput (HE.input UpdateRoleName)
        , HP.class_ (HH.ClassName "mdl-textfield__input") ]
      , HH.label
        [ HP.for "roleName"
        , HP.class_ (HH.ClassName "mdl-textfield__label") ]
        [ HH.text "Role name"]
```

And, to upgrade element:

```
  eval (Initialize el next) = do
    case el of
      Nothing -> pure next
      Just el' -> do
        liftEff $ upgradeElement el'
        pure next
```

`upgradeElement` is a helper I've exposed via FFI, and I needed to call `componentHandler.upgradeElement` in a window.timeout(...,0) for it to work. Is it as it supposed to be, or some kind of quirk/bug?

The full code is here: https://github.com/BartAdv/purescript-halogen-template/commit/4e0229c559aece5fcf9fe63bbd74554e7239407f

**Comment by garyb** [comment]
Note the paragraph about `ref` in here: https://github.com/slamdata/purescript-halogen/blob/master/GUIDE.md#creating-a-component

> Important: `ref` itself is not suitable for initializing and finalizing a component, as although it fires as soon as the element is created or removed there is no guarantee the element is actually in the DOM yet, and also it will not fire when a component has been removed entirely from the component tree. This is where the `SetElement` / `Initialize` / `Finalize` pattern comes in:
> 
> ``` purescript
> eval (SetElement el next) = do
>   modify (_ { element = el })
>   pure next
> eval (Initialize next) = do
>   el <- gets _.element
>   case el of
>     Nothing -> pure unit -- this case should never happen here, as refs fire before initializers even
>     Just el' -> -- do something to initialize the component
>   pure next
> eval (Finalize next) = do
>   -- clean up anything created during initialization
>   pure next
> ```

**Comment by BartAdv** [comment]
Cool, I skipped the SetElement thinking it might be of no use because I dont need to have reference to the element in state for other purposes. Will see how can I make it easier with some higher-order component. Thanks!

**Comment by BartAdv** [comment]
One more follow-up question, as this is not that straightforward to me: would it be possible to write a generic parent component that just performs the Initialize/SetElement dance, but overall its return type is the same as the child?
