### ISSUE TITLE
ajax example broken

### ISSUE THREAD

**Issue by mchaver** [slamdata/purescript-halogen#357]
Trying to get started with Ajax and Halogen but it looks like the ajax example latest commit in master won't compile.

**Comment by garyb** [comment]
If you're trying to use the version of Halogen in master, please refer to this branch: https://github.com/garyb/purescript-halogen/tree/new-guide

Otherwise, please use the tag for the latest release https://github.com/slamdata/purescript-halogen/tree/v0.12.0 :)

**Comment by mchaver** [comment]
Ah, I didn't know about tags in git/github and didn't realize that master wasn't the latest stable version.
