### ISSUE TITLE
Slamdown integration

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#36]
I'm guessing this would be useful?

This could be implemented as a function `forall a. Slamdown -> HTML a SlamdownEvent` which could be used to render reactive markdown documents.

**Comment by jdegoes** [comment]
Yes. Markdown documents are interactive (to the extent they include form elements) and need to produce variables defined by their form components. Do you think this would live here? Seems like it should live over in purescript-markdown, maybe broken out top-level like the themes here.

**Comment by paf31** [comment]
No, I was thinking it could be defined in either the markdown package, or just in its own adapter package.

**Comment by jdegoes** [comment]
Yeah, let's put it in purescript-markdown.
