### ISSUE TITLE
multi-component example requires purescript-halogen head

### ISSUE THREAD

**Issue by clample** [slamdata/purescript-halogen#362]
In the [multi-component](https://github.com/slamdata/purescript-halogen/blob/master/examples/multi-component/README.md) example, there are two ways given to build the example: build from the root of the project or build from the example directory.

Building multi-component using `npm run example-multi-component` in the root directory of the project worked fine. I think that this is because it builds purescript-halogen from latest master.

Building from the example directory, I got the error:

```
in module ComponentC
  at /Users/personal/Desktop/purescript-halogen/examples/multi-component/src/ComponentC.purs line 22, column 1 - line 22, column 58

    Could not match kind

      Type

    with kind

      Type -> Type -> Type


  while checking the kind of Component HTML QueryC Void m
  in value declaration componentC
```

I think that the issue is because building in the example directory uses purescript-halogen v0.12.0. I was able to fix the issue and build from the example directory by installing purescript-halogen from the latest commit:

`bower install 'git://github.com/slamdata/purescript-halogen.git#615bde109269124af0f01e8917c320a9f5193dcc' --save`

**Comment by clample** [comment]
To solve the issue, I would propose updating the bower.json for multi-component example to

```
{
  "name": "multi-component",
  "private": true,
  "dependencies": {
    "purescript-halogen": "git://github.com/slamdata/purescript-halogen.git#master"
  }
}
```

or change the Readme to only mention building from the root directory with `npm run example-multi-component`

**Comment by garyb** [comment]
Unfortunately using that `bower.json` won't work either, as it will cache whatever it pulls for `#master` the first time and never update it again (unless the bower cache is cleared).

This endless slow-motion release should be done soon so it will no longer be a problem!

**Comment by clample** [comment]
Cool! Thanks for the quick response, and I'll close the issue. I just thought that I would bring it up
