### ISSUE TITLE
Setting properties on SVG elements

### ISSUE THREAD

**Issue by kwohlfahrt** [slamdata/purescript-halogen#363]
I've created an SVG element (code at the bottom, more or less directly copied from `Halogen.HTML` plus a namespace). This works, if I add an `r` attribute in the browser my circle becomes visible.

However, if I try to add a property through Halogen, it doesn't work.

```
r :: forall s i. Int -> IProp (r :: I | s) i -- row parameter is 's' to avoid confusion
r = prop (PropName "r") (Just $ AttrName "r")
```

Trying to use `svg [] [circle [r 20]]` causes the page to appear blank, with the console error (Chromium, similar in Firefox):

```
Uncaught TypeError: Cannot assign to read only property 'r' of object '#<SVGCircleElement>'
    at app.js:27222
    at __do (app.js:27477)
    at app.js:28509
    at __do (app.js:27519)
    at __do (app.js:27872)
    at __do (app.js:27866)
    at app.js:28455
    at __do (app.js:27871)
    at __do (app.js:27866)
    at app.js:28455
```

I think this might be due to `r` not being a numeric value, but instead `SVGAnimatedLength` - what's the correct way to deal with properties like this?

I'm new to Halogen, so apologies if I'm using completely the wrong approach here.

SVG element code:
```
import Prelude
import Data.Maybe (Maybe(..))

import Halogen.HTML.Core (HTML, ElemName(ElemName), PropName(..), AttrName(..))
import Halogen.HTML.Elements (Node, Leaf)
import Halogen.HTML.Properties (I, IProp, prop)

import Halogen.VDom as VDom
import Halogen.VDom.DOM.Prop (Prop)

import Unsafe.Coerce (unsafeCoerce)

svgns :: String
svgns = "http://www.w3.org/2000/svg"

-- | A smart constructor for SVG elements.
celement :: forall p i. VDom.ElemName -> Array (Prop i) -> Array (HTML p i) -> HTML p i
celement = coe (\name props children -> VDom.Elem (VDom.ElemSpec ns name props) children)
  where
    coe :: (VDom.ElemName -> Array (Prop i) -> Array (VDom.VDom (Array (Prop i)) p) -> VDom.VDom (Array (Prop i)) p)
           -> VDom.ElemName -> Array (Prop i) -> Array (HTML p i) -> HTML p i
    coe = unsafeCoerce
    ns :: Maybe VDom.Namespace
    ns = Just $ VDom.Namespace svgns

-- | Creates an SVG element that expects indexed properties.
element :: forall r p i. ElemName -> Array (IProp r i) -> Array (HTML p i) -> HTML p i
element = coe celement
  where
    coe :: (ElemName -> Array (Prop i) -> Array (HTML p i) -> HTML p i)
           -> ElemName -> Array (IProp r i) -> Array (HTML p i) -> HTML p i
    coe = unsafeCoerce

svg :: forall p i. Node (viewBox :: I, height :: I, width :: I) p i
svg = element (ElemName "svg")

circle :: forall p i. Leaf (cx :: I, cy :: I, r :: I) p i
circle props = element (ElemName "circle") props []
```

**Comment by natefaubion** [comment]
For `svg`, you'll want to use the `Attr` constructor with the svg namespace, rather than `Prop`.

**Comment by kwohlfahrt** [comment]
Trying that (code below) makes some changes, but doesn't quite work. This changes the markup when inspecting (to the expected `<circle r="10"></circle>`). However, in the DOM properties browser nothing is affected and the circle is not visible.

```
---- | Create a SVG attribute.
cattr :: forall i. AttrName -> String -> Prop i
cattr (AttrName name) = Attribute ns name
  where
    ns :: Maybe Prop.Namespace
    ns = Just $ Prop.Namespace svgns

---- | Creates an indexed SVG attribute.
attr :: forall r i. AttrName -> String -> IProp r i
attr = coe cattr
  where
    coe :: (AttrName -> String -> Prop i) -> AttrName -> String -> IProp r i
    coe = unsafeCoerce

cx :: forall r i. String -> IProp (cx :: I | r) i
cx = attr (AttrName "cx")

r :: forall s i. String -> IProp (r :: I | s) i
r = attr (AttrName "r")
```

**Comment by kwohlfahrt** [comment]
Ah, the issue was that I should not have been providing the namespace in `cattr`, it should look like this:

```
---- | Create a SVG attribute.
cattr :: forall i. AttrName -> String -> Prop i
cattr (AttrName name) = Attribute Nothing name
```

This seems a bit counter-intuitive, could somebody explain why? Otherwise I'm happy for this to be closed.

**Comment by natefaubion** [comment]
@kwohlfahrt I'm not too familiar with using SVG with Halogen, unfortunately. But I know others have with some success at least. I would have expected you'd need the namespace, as I'm pretty sure others had to do that. It's what we've suggested in the past (and I think there are some issues here relating to it).

**Comment by kwohlfahrt** [comment]
Hmm, I noticed that on master, `Attribute` and `ElemSpec` expect a different `Namespace` type. This is not the case in the `purescript-halogen-vdom` repository, but `purescript-halogen` master has a non-existent commit pinned. That could be causing trouble.

**Comment by kwohlfahrt** [comment]
With the 1.0.0 release candidate, it is still necessary to use a namespace of `Nothing` for SVG attributes. That seems to work fine though! FWIW, I've thrown a (very incomplete) SVG library up here: https://github.com/kwohlfahrt/purescript-halogen-svg that I'll expand as I need additional properties.
