### ISSUE TITLE
Todo example doesn't compile

### ISSUE THREAD

**Issue by sjmackenzie** [slamdata/purescript-halogen#364]
```
$ ./node_modules/.bin/pulp build --to dist/output.js
* Building project in /home/stewart/dev/fractalide/gde
Compiling Model
Compiling Component.Task
Error found:
in module Component.Task
at /home/stewart/dev/fractalide/gde/src/Component/Task.purs line 36, column 13 - line 36, column 25

  Unknown value HP.inputType
```

it contains an exact replica of the todo application in `examples/todo`.
```
$ cat bower.json 
{
  "name": "gde",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "output"
  ],
  "dependencies": {
    "purescript-prelude": "^2.1.0",
    "purescript-halogen": "^0.12.0",
    "purescript-console": "^2.0.0"
  },
  "devDependencies": {
    "purescript-psci-support": "^2.0.0"
  }
}
```

**Comment by garyb** [comment]
If you've pulled the todo example from master then it is not for the currently released version of Halogen (v0.12.0) - try the one under that tag instead: https://github.com/slamdata/purescript-halogen/tree/v0.12.0/examples/todo

Things of this nature have occurred quite a bit, I'll not make the mistake of using `master` for a long running development branch without release again in the future :wink:

**Comment by sjmackenzie** [comment]
Greetings,

I did use the v0.12.0 tag, AFAICT, but it's npm/bower and I do not trust
that software at all.

I'm always dismayed when I see a language lance out using semantic
versioning. Semantic version gives you a license to break software, how
idiotic. The most important thing is respecting stable public APIs the
whole development experience for everyone becomes more calmer, people trust
each other's work and generally things frolic in fields. Please read and
watch

http://hintjens.com/blog:85
https://youtube.com/watch?v=oyLBGkS5ICk

Yes I understand this is early software, but being early it should at least
retain some semblance of stability for noobs like myself. I faught tooth
and nail getting nasty nasty npm and bower setup on my nixos machine.
Fighting through the impure nastiness to the land of purity and ... nothing
compiles, days of swearing and nothing works. All this "semantic
versioning" without respecting public APIs amounts to a swirling dancing
failure. It's a horrible experience that can be alleviated by some sane
practises of respecting public APIs.

The intensity of my rant is now out of proportion to the crime committed
here. I'd better shutup now, having said that I really like this project
and purescript. If I or other people am to base a company on your stuff
please respect public API contracts.

**Comment by garyb** [comment]
I think you misunderstood what I said. The files in master are not for v0.12.0, they're the currently-unreleased new version. As such, the examples in master will not work with v0.12.0, which according to the `bower.json` you posted is the version you're trying to compile them aginst. I was suggesting you use the version of the example from the v0.12.0 tag, as it most definitely does compile; the examples are checked as part of the CI setup.

**Comment by sjmackenzie** [comment]
Okay, yes I did misunderstood. Thank you for your patience. When will the new halogen release take place? I'll hold off learning halogen and just focus on purescript till then.

**Comment by sjmackenzie** [comment]
That certainly did it!

Finally I'm in the land of the pure and clean, thank you Gary!
