### ISSUE TITLE
Where's the version of halogen-vdom that bower.json references?

### ISSUE THREAD

**Issue by seagreen** [slamdata/purescript-halogen#366]
`bower.json` specifies:`"purescript-halogen-vdom": "3ef38c6ce7db4fd77c41c659c09e9e14a84b8bbb"`, but I can't find that commit at [purescript-halogen-vdom](https://github.com/slamdata/purescript-halogen-vdom). Any idea where it's located?

EDIT: Just realized this isn't used by the last release of halogen (v0.12.0) so I don't actually need that commit for my personal work. Feel free to close this as far as I'm concerned.

EDIT2: Actually I'm still interested in this.

**Comment by garyb** [comment]
It must have been referring to a commit in a branch that was squashed or something. I'll update this later along with the other pending changes mentioned on IRC :)

**Comment by garyb** [comment]
Current master now refers to a proper versioned release of `purescript-halogen-vdom`. 🎆
