### ISSUE TITLE
Higher order components

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#377]
I was trying to build a higher order component (i.e., a function `Component -> Component`) but got stuck when "forwarding" requests to the "inner" component. My approach is something like the following:

```purescript
data Query f o a
  = SomeOuterAction a
  | Inner (forall b. Tuple (f b) (b -> a))
  | HandleInner o a

type Slot = Unit

type State = Unit

hoc
  :: forall f i o m
   . Functor f
  => H.Component HH.HTML f i o m
  -> i
  -> H.Component HH.HTML (Query f o) i o m
hoc innerComponent input =
  H.parentComponent
    { initialState: const unit
    , render
    , eval
    , receiver: const Nothing
    }

  where

  render :: Unit -> H.ParentHTML (Query f o) f Slot m
  render _ =
    HH.div_
      [ HH.text "I'm the wrapper"
      , HH.slot unit innerComponent input (HE.input HandleInner)
      ]

  eval :: Query f o ~> H.ParentDSL State (Query f o) f Slot o m
  eval (SomeOuterAction next) = pure next
  eval (Inner (Tuple fb return)) = do
    result <- H.query unit fb
    pure $ return $ unsafePartial $ fromJust result
  eval (HandleInner o next) = do
    H.raise oqueries
    pure next
```

The problem is that somewhere in the line with `H.query` the `b` type variable escapes its scope and I can't figure out how to fix that. Also I'm not happy about the `unsafePartial`.

Generally, I wonder whether this is even the right approach, if higher order components are even possible, and what other approaches for achieving similar things in Halogen might be.

**Comment by garyb** [comment]
I have an immediate suggestion that may help, `Inner`'s argument is `Coyoneda`. That may fix the skolem escape as it uses `Exists` to deal with the existential `b` instead. We use the same thing to capture child queries in `HalogenM` as it happens: https://github.com/slamdata/purescript-halogen/blob/666dda47e0a41bdf8ecff71c86f70aeef130863a/src/Halogen/Query/HalogenM.purs#L39

The `unsafePartial` is unavoidable really - there's no way to prove that a `query` will succeed, since the component being queried might not exist in the HTML. Since the HTML is constant here it should be fine. Actually, another alternative would be to `case` on the result and use [`halt`](https://github.com/slamdata/purescript-halogen/blob/666dda47e0a41bdf8ecff71c86f70aeef130863a/src/Halogen/Query/HalogenM.purs#L114-L115) when the result is `Nothing`: it's just as partial, as the result is an exception, but perhaps it better expresses that it's a known invariant.

With both of the above you'd end up with something like this (which does compile without error :tada:):

``` purescript
import Prelude

import Data.Coyoneda (Coyoneda, unCoyoneda)
import Data.Maybe (Maybe(..))

import Halogen as H
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.Query.HalogenM as HQ

data Query f o a
  = SomeOuterAction a
  | Inner (Coyoneda f a)
  | HandleInner o a

type Slot = Unit

type State = Unit

hoc
  :: forall f i o m
   . Functor f
  => H.Component HH.HTML f i o m
  -> i
  -> H.Component HH.HTML (Query f o) i o m
hoc innerComponent input =
  H.parentComponent
    { initialState: const unit
    , render
    , eval
    , receiver: const Nothing
    }

  where

  render :: Unit -> H.ParentHTML (Query f o) f Slot m
  render _ =
    HH.div_
      [ HH.text "I'm the wrapper"
      , HH.slot unit innerComponent input (HE.input HandleInner)
      ]

  eval :: Query f o ~> H.ParentDSL State (Query f o) f Slot o m
  eval (SomeOuterAction next) = pure next
  eval (Inner iq) = iq # unCoyoneda \k q -> do
    result <- H.query unit q
    case result of
      Nothing -> HQ.halt "HOC inner component query failed (this should be impossible)"
      Just a -> pure (k a)
  eval (HandleInner o next) = do
    H.raise o
    pure next
```

I think this looks good as an approach for this sort of thing - it's not something I've had time to play with yet, but I've had it in mind since we made stuff existential, since it seems like it should be possible now.

**Comment by themoritz** [comment]
Exciting to discover `Coyoneda` this way. :) The whole thing turns out to work really well. For reference, here is how I use the higher order component (a variation on the "components" example):

```purescript
module Component where

import Prelude
import Button as Button
import HOC as HOC
import Halogen as H
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Data.Coyoneda (liftCoyoneda)
import Data.Maybe (Maybe(..), maybe)

data Query a
  = HandleButton Button.Message a
  | CheckButtonState a

type State =
  { toggleCount :: Int
  , buttonState :: Maybe Boolean
  }

data Slot = Button
derive instance eqTickSlot :: Eq Slot
derive instance ordTickSlot :: Ord Slot

type ChildQuery = HOC.Query Button.Query Button.Message

component :: forall m. H.Component HH.HTML Query Unit Void m
component =
  H.parentComponent
    { initialState: const initialState
    , render
    , eval
    , receiver: const Nothing
    }
  where

  initialState :: State
  initialState =
    { toggleCount: 0
    , buttonState: Nothing }

  render :: State -> H.ParentHTML Query ChildQuery Slot m
  render state =
    HH.div_
      [ HH.slot Button (HOC.hoc Button.myButton unit) unit (HE.input HandleButton)
      , HH.p_
          [ HH.text ("Button has been toggled " <> show state.toggleCount <> " time(s)") ]
      , HH.p_
          [ HH.text
              $ "Last time I checked, the button was: "
              <> (maybe "(not checked yet)" (if _ then "on" else "off") state.buttonState)
              <> ". "
          , HH.button
              [ HE.onClick (HE.input_ CheckButtonState) ]
              [ HH.text "Check now" ]
          ]
      ]

  eval :: Query ~> H.ParentDSL State Query ChildQuery Slot Void m
  eval = case _ of
    HandleButton (Button.Toggled _) next -> do
      H.modify (\st -> st { toggleCount = st.toggleCount + 1 })
      pure next
    CheckButtonState next -> do
      buttonState <- H.query Button $ HOC.Inner $ liftCoyoneda $ H.request Button.IsOn
      H.modify (_ { buttonState = buttonState })
      pure next
```

Maybe it also makes sense to add something like this to the examples? I could prepare a PR...

**Comment by themoritz** [comment]
I forgot one thing. For some reason, I need to define a `Functor` instance for the query algebra of the inner component, in this case `Button.Query`. Is there a way to avoid this?

**Comment by garyb** [comment]
Nice! 

Yeah, I was going to say if this proves to be useful technique it would be great to have as an example / eventually a chapter in the guide (got some way to go before I get to those kind of fun topics yet though :wink:).

Regarding the `Functor` constraint... I think it's unnecessary? I didn't notice that is was present in your original example so didn't remove it from my proposal, but if you just take the constraint off `hoc` it still seems to compile for me.

**Comment by themoritz** [comment]
Uh, yes, you're right. That constraint was a relic of my previous struggles...

**Comment by kana-sama** [comment]
Why do we need Coyoneda and to hide algebra argument, if this simplest approach works as well:
```purescript
data Query f i o a
  = InnerQuery (f a)
  -- ...

--  HOC eval
eval (InnerQuery query) = do
  id <- H.gets _.id
  H.query (ChildSlot id) query >>= case _ of
    Just next -> pure next
    Nothing   -> HQ.halt "impossible"

-- Container eval
eval (GetValue next) = do
  value <- H.query ChildSlot (WithDisable.liftQuery (H.request Counter.GetValue))
  pure next
```

**Comment by natefaubion** [comment]
`Coyoneda` is so that you don't incur a `Functor` constraint on `f`. `Halogen` in general does not require you to implement `Functor` for query algebras. `Coyoneda` is the free Functor.
