### ISSUE TITLE
Repeated line?

### ISSUE THREAD

**Issue by julian1** [slamdata/purescript-halogen#383]
https://github.com/slamdata/purescript-halogen/blob/master/examples/driver-io/src/Main.purs#L22

Sorry it's the first Halogen example I've looked at, but I don't understand why the Monadic IO.query function is repeated 3x.

**Comment by garyb** [comment]
It's just part of the illustration of using the IO record to listen to and send messages to a component. Note above the `query`ing a subscription is set up to log whenever a message is received. Toggling the button on and off via the query results in the messages from the button being observed and logged in the console.

**Comment by julian1** [comment]
Ahh, Thanks. I thought it was part of the subscription, rather than the functional equivalent of sending a toggle event.
