### ISSUE TITLE
Row signatures 

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#388]
`DSL`s, `HTML`s and `Component`s sigantures have  a lot of type variables. Some of them are `Unit`s, `Void`s, sometimes input type is equal to state. This makes type for `component`'s a bit too complicated to remember. Since some type vars are existentially hidden during construction maybe it would be more convenient to change from 
```
component :: Component a b c d e
render :: State -> ParentHTML a b c d 
eval :: Query ~> ParentDSL a b c d e f
``` 
to 
```
component :: Component ( view :: a, query :: b, input :: c, message :: d, monad :: e) 
render :: State -> ParentHTML ( query :: a, childQuery :: b, childSlot :: c, monad :: e) 
eval :: Query ~> ParentDSL ( state :: a, query :: b, childQuery :: c, childSlot :: d, message :: e, monad :: f)
```

If this idea looks good, I could try to implement this in current modules or adding new (e.g. `Halogen.Component.Labeled` or something)

**Comment by garyb** [comment]
I had the exact same thought, it needs a little consideration to figure it out, as it means we end up with `Component (r :: # *)`, but I think it can work if we restrict the creation/existential `un` of `Component` to also use the row.

For now I just have a cheat sheet :wink:

``` 
Component h f i om
ComponentDSL s f o m a
ComponentHTML f
ParentDSL s f g p o m
ParentHTML f g p m
```

**Comment by natefaubion** [comment]
I think it would be neat, but probably only if it could work with polymorphic rows. That way you could define the set of variables once, and just sub them in.

```purescript
type MyComponent =
  ( state :: State
  , query :: Query
  , childQuery :: ChildQuery
  , childSlot :: ChildSlot
  , input :: Input
  , output :: Message
  , effect :: Slam
  )

render :: State -> ComponentHTML MyComponent
eval :: Query ~> ComponentDSL MyComponent
component :: Component HH.HTML MyComponent
```

But I don't know if this is possible.

**Comment by garyb** [comment]
I came up with an alternative option for this, but only showed Nathan: https://gist.github.com/garyb/4c0741b92a477500158c8465a01b4079

I'm not sure how worthwhile it is, as although doing something like that would simplify the declarations, it would probably suffer from less than stellar error messages, etc.

**Comment by rightfold** [comment]
This requires quite a bit more typing, and after writing a few components it's not hard to memorize the order, IMO.

**Comment by garyb** [comment]
Closing this, as it was a nice idea, but probably not going to happen in the near future at least. There were issues with kinds (since the record is `# Type`, which meant you need yet more types so it could be like `(query :: AQuery Query)` where `AQuery` is just there to make `Query`'s `Type -> Type` work out) before we even got to the point of trying to extract parts from the row meaningfully in function type signatures.

Perhaps we can revisit it one day!
