### ISSUE TITLE
Finally tagless HTML representation

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#39]

**Comment by paf31** [comment]
@jdegoes This is the one remaining item on my list for 0.4, and I should have some time tomorrow evening to spend on it.

**Comment by jdegoes** [comment]
:+1:

**Comment by paf31** [comment]
So I made another attempt at this, here:

https://github.com/slamdata/purescript-halogen/tree/final2

I spent two hours on it, but I just kept coming up against typechecker issues:

- I can't use `[Attr i]` because of impredicative type issues.
- I lose the ability to use `Semigroup` on `Attr i` because you can't write things like `class (Semigroup (f i)) <= Attr f` so I have to use `Plus` which is a bit weird.
- The type signatures and error messages are baffling. If I were a newcomer, I would probably find it pretty offputting.

I feel like I'm pretty close, but it's not working yet, and at this point, I'm starting to feel like it's a dead end, sadly. 

Maybe I can address some of these issues by wrapping things with newtypes, instead of using rank-2 types, so I'll spend a little time on that and see how far I get.

**Comment by paf31** [comment]
Ok, newtypes fixed pretty much everything here :smile: 

It's still not entirely done, but things build and the demos work. I'll make a PR so that you can take a look.
