### ISSUE TITLE
halogen-vdom adds additional element when diffing

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#402]
This is likely a vdom issue but I'm still posting it here. It's really hard to reproduce this in a small example since the setting is so complex, but here is basically what happens:

There is an element somewhere deep in the render function of one of my components which gets copied on every render. However, it's part of a popup menu, so a descendant of some other `div` which sometimes gets removed from the DOM (i.e., when the menu is closed). Whenever I close and open the popup again, everything renders correctly, so I assume during the diffing process of the element something goes wrong.

There is nothing special about the element, it's just a `div` with a `class` attribute, has one `div` child, and has another `div` as its parent. There's also another popup menu similar like this, but which is not affected by the bug (it doesn't have the `.cell-list__element-delete` element below).

Here is the markup, if that helps debugging:

```html
<div class="cell-expanded">    <----- this is the root of the popup
  <div class="cell-expanded__body p1">
    <div class="cell-list">
      <div class="cell-list__element flex mb1">
        <div class="cell-list__element-delete p1">
          <button class="cell-button"><i class="fa fa-minus-circle"></i></button>
        </div>
        <div class="flex-auto p1">
          <div class="right-align full-height">    <----- this div gets duplicated
            <div class="editbox ">0</div>
          </div>
        </div>
      </div>
      <div class="cell-list__new p1">
        <button class="cell-button"><i class="fa fa-plus-circle"></i></button>
      </div>
    </div>
  </div>
</div>
```

**Comment by garyb** [comment]
Nathan is having trouble with GitHub at the moment, but he's pretty baffled by what is going on here.

We suspect it may be similar to the problem that the `onBlur` issue raised though, where `render`s are overlapping - once there's a fix in for that (I'll work on it now), perhaps you could try again then and see if it still manifests?

**Comment by themoritz** [comment]
Yeah, it seems crazy and there shouldn't be much room for these kind of bugs since everything is so generic.

> perhaps you could try again then and see if it still manifests?

Sure thing!

**Comment by themoritz** [comment]
The problem still persists on your `render-queuing` branch @garyb.

**Comment by garyb** [comment]
Ok thanks, darn.

**Comment by natefaubion** [comment]
Yeah, this is really strange. I don't have any other ideas off the top of my head. The virtual-dom diffing stuff is pretty straightforward, and I can't think of an obvious way that it could be truly duplicating a node in an otherwise stable environment. It does DOM inserts with nodes, obviously, but this can't duplicate. I'd really need some way to reproduce, even if it's a fairly involved example.

**Comment by themoritz** [comment]
Ok, I'll try to build one tomorrow.

**Comment by natefaubion** [comment]
Any 3rd party libs that might be doing something? Any components involved? Maybe try adding some sibling nodes next to the div and see what happens...

**Comment by garyb** [comment]
Any luck with this on the latest `render-queueing` branch?

I was seeing something similar to what you describe with your `onBlur` example with my initial fix there, but the new thing seems to have solved it there.

**Comment by themoritz** [comment]
Yes, I was about to say, while I was using the "unless" commit, the same phenomenon appeared at places where an `onBlur` handler was involved: Everytime the event fired, it's parent got duplicated. Anything we can conclude from that?

But the other problem is still there and I'm still trying to reproduce in a smaller example.

**Comment by garyb** [comment]
Overlapping renders was the only theory I had for that - although if that were true my initial fix for the other branch should probably have worked too :confused:

**Comment by natefaubion** [comment]
Yes: the machine state for the VDom is kept in a ref. When you want to transition, you pull out the machine, and feed it the next VDom, and it will diff it against the render tree it has in closure state. When it's done, we stash the next machine back in the ref. If you trigger another render before the next machine has been put in the ref, it will diff with the old state twice, which may result in two node insertions. I'm mostly convinced it's still related to overlapping renders somehow, but we may just still have something out of sequence somewhere.

**Comment by themoritz** [comment]
Ok, I might know what's going on! My render function had some recursive parts to render a tree structure, and somewhere in the tree there are child components (the `".editbox"` `div` in the snippet above) that I didn't correctly produce unique slot addresses for.

At least I could reproduce the behavior I described when slot addresses aren't unique. Will try to generate unique addresses in my larger project and if that fixes it, we're happy!

**Comment by natefaubion** [comment]
The undefined behavior of duplicate slots is unfortunate 😞. It can be hard to track down. It may be worth putting in a log to `console.error` in the case of duplicate slots. The bookkeeping overhead is non trivial though, since it's `Map` based. Maybe we could do it cheaply using `Map.update` rather than insert, and an unsafe trace.

**Comment by themoritz** [comment]
Alright, I got it fixed! :tada: Thanks for your help and sorry for picking vdom as a suspect. :wink:

**Comment by garyb** [comment]
Nice, mystery solved :smile:

We'll try and do something to warn in the console about duplicate slots, as Nate suggests... at least it should make things like this easier to track down.

**Comment by natefaubion** [comment]
> Thanks for your help and sorry for picking vdom as a suspect. 

Well considering, it's largely untested, I'd say its a viable suspect 😜 

Thank you so much for the detailed bug reports! Your feedback has been invaluable in making this release as stable as it is.

**Comment by garyb** [comment]
Yeah, thanks for taking the time to write these up / check our proposed fixes :)

**Comment by themoritz** [comment]
Well, I have to say thank you for making such an amazing GUI library and for being so responsive and active!
