### ISSUE TITLE
Closure of slot outputQuery broken?

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#405]
Ok, here is another crazy one. I have a component which basically holds an `Array String`, and for every element of that array, it renders a child component, which allows to change that string in the array.

The problem is that setting the value in the `i`th child truncates the array from `i` onward. The reason is that in the following code, the two trace statements print different values for `items`: The first (in the render function) prints the whole array, the second (in the callback) the truncated one, but both should use the same (immutable) value from the `render` closure.

Could also be a bug in the compiler or purescript-arrays? 

```purescript
module Main where

import Prelude
import Halogen as H
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.HTML.Properties as HP
import Control.Monad.Aff (Aff)
import Control.Monad.Eff (Eff)
import Control.Monad.State (modify, put)
import Data.Array (length, snoc, updateAt, zip, (..))
import Data.Const (Const)
import Data.Maybe (Maybe(..), fromMaybe)
import Data.Tuple (Tuple(..))
import Debug.Trace (trace)
import Halogen.Aff (awaitBody, runHalogenAff)
import Halogen.Aff.Effects (HalogenEffects)
import Halogen.Component.ChildPath (type (<\/>), type (\/), cp1)
import Halogen.VDom.Driver (runUI)

--------------------------------------------------------------------------------

data QueryItem a
  = UpdateItem String a
  | EmitItem String a

compItem :: H.Component HH.HTML QueryItem String String App
compItem = H.component
  { initialState: id
  , render
  , eval
  , receiver: Just <<< H.action <<< UpdateItem
  }

  where

  render :: String -> H.ComponentHTML QueryItem
  render val = HH.input
    [ HP.value val
    , HE.onValueInput (Just <<< H.action <<< EmitItem)
    ]
  
  eval :: QueryItem ~> H.ComponentDSL String QueryItem String App
  eval = case _ of
    UpdateItem val next -> do
      put val
      pure next
    EmitItem val next -> do
      put val
      H.raise val
      pure next

--------------------------------------------------------------------------------

data Query a
  = AddItem a
  | SetItems (Array String) a

type State = Array String

type Child =
  QueryItem <\/>
  Const Void

type Slot =
  Int \/
  Unit

app :: H.Component HH.HTML Query Unit Void App
app = H.parentComponent
  { initialState: const []
  , render
  , eval
  , receiver: const Nothing
  }

  where

  render :: State -> H.ParentHTML Query Child Slot App
  render items = HH.div_
    [ HH.button
      [ HE.onClick (HE.input_ AddItem) ]
      [ HH.text "+" ]
    , HH.ul_ $
      zip (0 .. length items) items <#> \(Tuple i item) ->
        trace ("Render: "<> show items) \_ ->
          HH.li_
          [ HH.slot' cp1 i compItem item \newVal ->
              trace ("Callback: " <> show items) \_ ->
                let
                  new = fromMaybe items $ updateAt i newVal items
                in
                  Just $ H.action $ SetItems new
          ]
    ]

  eval :: Query ~> H.ParentDSL State Query Child Slot Void App
  eval = case _ of
    AddItem next -> do
      modify $ flip snoc ""
      pure next
    SetItems items next -> do
      put items
      pure next

--------------------------------------------------------------------------------

type AppEffects = HalogenEffects ()
type App = Aff AppEffects
    
main :: Eff AppEffects Unit
main = runHalogenAff $ do
  body <- awaitBody
  runUI app unit body
```

**Comment by natefaubion** [comment]
This is because the message handler is not updated after initial rendering, so it keeps the closure around. We should be updating it on each render to mirror the vdom handlers.

**Comment by natefaubion** [comment]
This is difficult to do in a type-safe way because slots are the only local identity given to a component. When you mount a component, the slot is what ties a component to a lifecycle. On subsequent renders, the `Component` aspect of a slot is actually ignored, because otherwise you have to give it referential identity (The new component passed in is referentially inequal than the old component, so we should then remount it). The message handler must be tied to the component (output -> query must match), so since we ignore the `Component`, we must ignore the changed handler as well. The workaround is to just not close over render state in a message handler, unfortunately.

**Comment by themoritz** [comment]
Ok, I see. I guess one approach to this kind of situation could then be to pass the part of the state that I want modified by the child as an input to it. The child then sends a message with the modified value.

**Comment by natefaubion** [comment]
In this particular case, I would not modify the items in the message handler. I would close over `i`, and have something like `UpdateItemAt Int String a`.

**Comment by themoritz** [comment]
:+1: This is nice since the child does not need to know anything about the parent. And this works exactly because `i` is the slot address?

In my particular example, I have a tree/list combination, but maybe I could do it with something like `UpdateValueAt (Traversal' State String) String a`... if the traversal is isomorphic to the slot address (i.e. the slot address changes exactly when I need the message handler updated)?

**Comment by natefaubion** [comment]
I would use the information you use for the slot, probably, as this is what the library uses for identity.

Just as an FYI, an early design consideration was to just provide a message handler at the component level (just as `peek` used to work), but that means you have to pattern match on slots directly (which is annoying) and you must evaluate every message. I don't really care for the way that splits `eval`, though, so we opted to provide a way to map a message to a query.

**Comment by themoritz** [comment]
Ok, so essentially the message handlers have a similar sematic as peek used to have but save me the pattern matching on the coproducts and slot addresses? If I think about how peek was used, it immediately makes sense that using the child path and the slot address for constructing the query is okay, but the render state not.

I ended up implementing the lens approach which turned out to work really well. Making sure that slot addresses correspond to lenses was much easier that writing a custom traversal function for my trees `SlotAddress -> Value -> Tree -> Tree`
