### ISSUE TITLE
Support for virtual-dom's Widget feature

### ISSUE THREAD

**Issue by tdammers** [slamdata/purescript-halogen#407]
Described here: https://github.com/Matt-Esch/virtual-dom/blob/master/docs/widget.md

Widgets provide a way to hook existing JavaScript UI elements that are not virtual-dom aware into a virtual-dom based application. A Widget forms an "island" of sorts, that virtual-dom doesn't touch directly, instead it delegates the DOM creation, manipulation, and deletion to the widget itself, however the state that gets passed to the widget is still managed by virtual-dom, and you can hook the widget into the virtual DOM tree just like any other node.

Specifically, I would like to integrate [Leaflet](http://leafletjs.com/) into a Halogen app, because I really *really* don't feel like reinventing that particular wheel myself, and Leaflet pretty much Just Works.

Is there anything in Halogen (or a third-party addon library) that would allow me to do this? If not, would it be possible to add?

**Comment by natefaubion** [comment]
For something like leaflet, it's easy enough to wrap as a component using refs and the normal component lifecycle events. Halogen-vdom supports a notion of Widgets, which we use to implement components, but it's not extensible from Halogen proper, though I don't think it's necessary for your use case.

**Comment by natefaubion** [comment]
Take a look at the Ace example (which is a component that wraps the Ace editor) https://github.com/slamdata/purescript-halogen/blob/master/examples/ace/src/AceComponent.purs

**Comment by tdammers** [comment]
Thanks, that looks close enough. I'll see how far I get with this.

**Comment by natefaubion** [comment]
It should be noted, that example component does not need the `Parent` stuff, as it has no child components.

**Comment by tdammers** [comment]
Makes sense.
