### ISSUE TITLE
Advice on using Halogen with purescript-d3

### ISSUE THREAD

**Issue by seagreen** [slamdata/purescript-halogen#413]
(If this is too much like a help question please just hit the close button. Hopefully it's of general interest though.)

When trying to combine Halogen with `purescript-d3` (or any tool that also wants to manipulate the DOM) I can think of two different strategies:

1. Integrate that tool with Halogen so that it also manipulates Halogen's virtual dom.

2. Attach that tool to an element outside of the element tree controlled by Halogen. Then during the `eval` phase of a Halogen component issue commands to modify it.

Which of these strategies seems like the correct choice? Right now I'm pursuing (2), but I'm not sure this was the right decision. I've got a demo working, but it limits where I can place the d3 `<svg>` on the page, so it's not perfect.

Since I think this situation will come up in more contexts than just d3, it might be worth it to put a note somewhere on how to integrate external tools with Halogen's virtual dom.

**Comment by garyb** [comment]
I would treat this much like any other "3rd party" component - that is to say, use a `ref` on a container element in a component, which will give you the rendered `HTMLElement` for that once it has been rendered in the DOM. As long as you don't try and change anything about that element after it has been introduced it'll be perfectly safe to do whatever you want inside it, without a risk of its contents being deleted during patching, etc.

I would probably wouldn't recommend taking this approach as part of a larger component though, and instead entirely encapsulate the container with the component, so you end up with something like `render = const $ HH.div [ HP.ref myRef ] []`, that way there's no risk of accidentally patching the node at all.

**Comment by seagreen** [comment]
That makes perfect sense! And now I see the Ace editor example as well. Thanks for the help.
