### ISSUE TITLE
awaitBody does not work if the body has already loaded

### ISSUE THREAD

**Issue by timgalebach** [slamdata/purescript-halogen#420]
The below code doesn't work--fix is to move awaitBody above the line that does the API/ajax call. Sort of weird semantically: awaitBody seems as if it should work at any point before or after the body has loaded.

     main = HA.runHalogenAff $ do
     --line below causes issues; ui works as expected if it's commented out
     token <- loadOrRefreshToken C.clientId C.authDomain (C.apiUrl <> "loginping")
     liftEff $ log $ "Loaded token: " <> token
     body <- HA.awaitBody
     --ui here is just a simple Button component from the examples
     runUI ui unit body

**Comment by garyb** [comment]
Resolved by #482
