### ISSUE TITLE
method property does not match HTMLForm method row

### ISSUE THREAD

**Issue by kwohlfahrt** [slamdata/purescript-halogen#433]
I can't add a `method` property to a `form` element. I think this is because `DOM.HTML.Indexed.HTMLForm` expects `method :: String`, but `Halogen.HTML.Properties` produces `Prop (method :: I.FormMethod | r) i`?

**Comment by garyb** [comment]
I think this is a mistake in `purescript-dom-indexed` unfortunately 😕 - I don't see why we wouldn't want `I.FormMethod` there too.
