### ISSUE TITLE
Run `receiver` on first call to `Halogen.Aff.Driver.runUI`

### ISSUE THREAD

**Issue by rahulmutt** [slamdata/purescript-halogen#444]
I wrote my first Halogen app assuming that running `runUI` would automatically run the `receiver` of the `ComponentSpec` with the input I provided it and trigger a query for my component that would initialise the state after sending an AJAX request. 

But this did not work. Instead, I had to do:
```haskell
io <- runUI Home.component unit body
io.query $ H.action $ Home.SomeQuery
```
to trigger the initialisation which did what I wanted. 

Cases like these where you want to initialise an app's state through an effect (which you clearly can't do with `initialState`, which is pure) seem quite common - why not make it a default through invoking the `receiver`? 

If not made default, the docs should be made more clear that the even though both `initialState` and `receiver` take an input, only `initialState` is executed when you run the component with an input. This information is *not* clear at all from just looking at the types.

**Comment by garyb** [comment]
You can use a `lifecycleComponent` and have it raise a query using `init` to achieve this - the initial state will be set before `Init` fires. This applies to all components, not just the top level :)

**Comment by rahulmutt** [comment]
Thanks! Do you think it's worth clarifying the point I mentioned in the docs?

**Comment by garyb** [comment]
Yeah definitely, I have a TODO in the readme to add docs about the lifecycle stuff, I was going to add something in there to explain it, and link across from the section on `receivers`. I just need to actually write it!

**Comment by rahulmutt** [comment]
Great! Just wanted to make sure it's tracked somewhere. Closing.
