### ISSUE TITLE
add psc-package

### ISSUE THREAD

**Issue by shmish111** [slamdata/purescript-halogen#452]
I really want to not have to use bower and that means popular libraries like yours being added to https://github.com/purescript/package-sets

Can you do this?

**Comment by garyb** [comment]
Yeah, we should do this. 👍 Just so you know though, the library authors don't have to be the ones to do it, you could just submit a PR with the appropriate additions to `package-sets` also.

**Comment by thoradam** [comment]
Halogen is now in package-sets: https://github.com/purescript/package-sets/commit/b07adafc9f5adb603cb82dac1033d5d899d2ea26

**Comment by garyb** [comment]
Thanks!
