### ISSUE TITLE
slot variant that hides child query type

### ISSUE THREAD

**Issue by BartAdv** [slamdata/purescript-halogen#458]
Hi!

In my scenarios, I'm mostly satisfied with the 'message' component provides, and many times I don't query the child components in parent eval. Therefore, it often feels to me like being forced to change component signature to parent components is something that could be avoided.

Would it be possible to provide 'slot' variant that does not allow you to query that component, but allows you to handle it's output messages?

Scenario:

Building a form, using traditional HTML inputs. Suddenly, need to turn one 'select' into select that's enhanced by JS, so I make lifecycleComponent, add some JS magic in its Init query, but then I need to get back to that form, and make it a parent. Even if I don't intend at all to query that component (though I understand it's often needed to query it).

It sort of feels to me like component Query type describes both the public, and the private operations. And if I have only the latter (or I'm not interested in the former), then why even bother?

**Comment by BartAdv** [comment]
Another scenario: "router" component. Basing on some state, it decides which component to render, and it renders it by passing some input. No querying after that. Currently I just have separate child path for each case, but this becomes unwieldy, especially that after `cp10` I'll probably have to start define my own `cp`s...

**Comment by natefaubion** [comment]
Yeah, this is useful. We currently are using this https://github.com/slamdata/slamdata/blob/master/src/Halogen/Component/Proxy.purs to hide or remap child queries. I think it's something that we could properly support though.

**Comment by BartAdv** [comment]
Oh! So much black magic :)

Let's take it step by step:

I'm currently doing something like:

```
type ChildQuery = ComponentA.Query
                       <\/> ComponentB.Query

type ChildSlot = Unit \/ Unit \/ Void

cpComponentA = CP.cp1
cpComponentB = CP.cp2

```

Then in rendering:

```
case location of
  RouteA someValue -> HH.slot' cpComponentA unit ComponentA.component someValue absurd
  RouteB -> HH.slot' cpComponentB unit ComponentB.component unit absurd
```

So, if I could hide the type of thie child query, that would work great. Now, looking at the aforementioned Proxy, I see that:

```
proxy
  ∷ ∀ f i o m
  . H.Component HH.HTML f i o m
  → H.Component HH.HTML (ProxyQ (Const Void) i o) i o m
```

Which looks tempting, because it hides the `f`. But in return, it exposes `i` in the ProxyQ type! I am using `i` only while rendering the component (see `someValue` above), so I don't want to pollute the `ChildQuery` with anything except maybe the component output (which I'm not handling now, all those components have `Void` output).

**Comment by natefaubion** [comment]
There's no way to avoid that with this setup, unfortunately, which is why it would be nice to have first-class support for it. For the proxy component to marshal the receiver input in a well-typed manner, it has to show up in the `ProxyQ` type somehow.

**Comment by natefaubion** [comment]
It may be possible to do a specialized, "unsafe" version of this though only for hiding, and not export any constructors for the Proxy's query type.

**Comment by BartAdv** [comment]
At this moment I've went with (just took the original `slot` definition, altered the types and slapped `unsafeCoerce`....):

```
-- | Defines a slot for a child component that ignores child query. Takes:
-- | - the slot "address" value
-- | - the component for the slot
-- | - the input value to pass to the component
-- | - a function mapping outputs from the component to a query in the parent
unsafeSlot
  :: forall f m p i o g h
   . p
  -> Component HTML g i o m
  -> i
  -> (o -> Maybe (f Unit))
  -> ParentHTML f (Const Void) p m
unsafeSlot p component input outputQuery =
  let f = unComponent _.receiver component
  in unsafeCoerce $ Core.slot (mkComponentSlot p component input f outputQuery Just)

```

Hope it won't become problematic;)

**Comment by garyb** [comment]
Closing this as something like it is now possible in Halogen 5, in that components can have internal "actions" to handle interaction, etc. distinct from the "query" they advertise to the outside world.
