### ISSUE TITLE
Adding Raw HTML

### ISSUE THREAD

**Issue by mschristiansen** [slamdata/purescript-halogen#459]
For a bootstrap modal I want to render `"&times;"` instead of `"X"`. Is there something equivalent to Halogen.HTML.text (e.g. Halogen.HTML.raw) that doesn't escape or what am I missing?

**Comment by BartAdv** [comment]
You can just use the character itself (×), instead of the entity encoding.

**Comment by mschristiansen** [comment]
Sure, not too keen on utf-8 in my source code, but can certainly do that. I'll assume that's the only way within `purescript-halogen` then(?).
