### ISSUE TITLE
Move from bower packaging

### ISSUE THREAD

**Issue by juanpaucar** [slamdata/purescript-halogen#460]
Hi everyone, as expressed in this [issue from bower](https://github.com/bower/bower/issues/2298). Bower has started being deprecated in favor of other packet managers. So, I think it's probably a good idea to move it to other packet manager.

**Comment by noraesae** [comment]
I guess this issue is known in the PS community and that's why we're working on [psc-package](https://github.com/purescript/psc-package). This is also not specifically a halogen issue, but an issue of PureScript ecosystem.

**Comment by garyb** [comment]
Closing this now as Halogen is available via `package-sets`. I'll be sure to add that to the readme.
