### ISSUE TITLE
Release of `purescript-halogen-utils`

### ISSUE THREAD

**Issue by menelaos** [slamdata/purescript-halogen#467]
What do you think about releasing a `purescript-halogen-utils` package that contains the functionality of https://github.com/slamdata/slamdata/blob/master/src/Halogen/Component/Utils.purs and 
https://github.com/slamdata/slamdata/tree/master/src/Halogen/Component/Utils ? 
I've found those functions to be very useful and I'm sure there are plenty more that could go into such a package (e.g. https://github.com/slamdata/purescript-halogen/blob/master/examples/keyboard-input/src/Keyboard.purs).

**Comment by damncabbage** [comment]
I don't suppose you could summarise what you wanted? We can't see the slamdata/slamdata repo anymore, for better or worse.

**Comment by garyb** [comment]
- There are a bunch of `EventSource` helpers
  - throttled
  - debounced
  - a `oneTimeEventSource` helper
  - an `affEventSource` helper
  - a `busEventSource` helper
- some things for self-raising queries after a delay
- Drag helpers
- A proxy component 

Basically everything here aside from the proxy is out of date now though with the changes in Aff v4, so until we upgrade SlamData there's probably not much point publishing the library right now. The intention is still to publish this stuff eventually though!

**Comment by natefaubion** [comment]
@damcabbage FWIW there are still forks of the open sourced versions, even if they are outdated. https://github.com/natefaubion/slamdata

**Comment by menelaos** [comment]
Oh, I totally missed that SlamData isn't open source anymore. I found it very helpful in the beginning as a best practice manual for non-trivial Halogen projects.

**Comment by garyb** [comment]
It might not be that way permanently, and we'd like to make it as open source as we can, but we also would like people who just use the product to pay for it sometimes 😕

**Comment by menelaos** [comment]
Yeah, that is completely understandable. Thanks for open-sourcing so much of your hard work (libraries, Halogen guide etc.) at all!

**Comment by garyb** [comment]
I'm going to close this as it's pretty out of date now, and with the changes that have gone on in Halogen since, a lot (all?) of these utility things have become redundant due to the addition of `fork` / `EventSource` changes / `Aff` becoming stack-safe, etc.
