### ISSUE TITLE
Permission to submit a Halogen benchmark implementation

### ISSUE THREAD

**Issue by saylu** [slamdata/purescript-halogen#471]
Hi guys,

I've created an implementation of the JavaScript framework benchmarks that I plan to add to that repository. The repository is fairly popular, and already includes an Elm benchmark, but there is no representation from PureScript. I thought it'd be useful to add Halogen into the mix as well.

I've already implemented the benchmark and it passes the repository's tests, so I can submit this at any time. Before I do, though, I wanted to make sure y'all are OK with that, and double-check if I've done anything horribly inefficient that could cast a bad light on the framework.

In my implementation, Halogen sees a ~4x slowdown compared to vanilla JS.

My repository containing the code is linked below. You should be able to follow the few instructions to run the code yourself in ~1 minute if you would like.
https://github.com/saylu/purescript-framework-benchmark

I've briefly discussed this with @natefaubion in the #purescript Slack channel but have not explicitly made sure this is OK to submit yet.

**Comment by Cmdv** [comment]
I'd say maybe link the example to a repo incase others can spot if there are any implementational improvements that can be made. 
Will tag @garyb because he is the main wizard behind Halogen 😸

**Comment by saylu** [comment]
The full fork is here, which is an expanded version of my much smaller repository linked above:
https://github.com/saylu/js-framework-benchmark

Just the Halogen folder is this one:
https://github.com/saylu/purescript-framework-benchmark/tree/master/halogen-v2.1.0

**Comment by safareli** [comment]
Not sure how significant improvement we might have but using `Data.Sequence` might be much better based on operations you are performing on `Array`

**Comment by saylu** [comment]
Turns out using `Data.Sequence` actually has _worse_ performance (moves from ~4x slowdown to ~5x slowdown). I think theoretically Sequence is the right move, but that doesn't seem to be the case in practice.

**Comment by saylu** [comment]
The current version here -> https://github.com/saylu/js-framework-benchmark

has this result:

![comparison](https://user-images.githubusercontent.com/10245104/28998553-b853d754-79e2-11e7-907a-c072c5458474.png)

as compared here with Angular, which itself is about 1.5x slower than vanilla JS. The repo owner has indicated he's ready for a pull request, and the code has passed their integration tests.

Is it OK for me to submit this?

**Comment by garyb** [comment]
👍

**Comment by saylu** [comment]
I'm submitting this version, but if anyone notices some easy improvements please feel free to let me know!

**Comment by saylu** [comment]
Benchmark merged:
https://github.com/krausest/js-framework-benchmark/pull/227#event-1194548751

**Comment by natefaubion** [comment]
FWIW, I did a test with purescript-spork (which is a veneer over halogen-vdom) with `Html.lazy` and the mean slowdown was 2x compared to vanilla JS. Right now the Halogen test is always diffing the entire tree, and I'm sure many of the other tests account for that. You could try turning each row into a component, which is how Halogen memoizes renders. This will probably make the creation tests worse, while making the update tests faster. Using components is always keyed, though.

**Comment by saylu** [comment]
I'm happy to implement these kinds of updates! The owner has the option of doing this as a keyed variant with components, too, so I'll explore that. 

Also, while I can try and implement these myself, I certainly have no ownership over the benchmark and anyone who would like to update the Halogen benchmark in the repo -- by all means, go for it!

**Comment by natefaubion** [comment]
Other than memoizing renders for rows, node creation is especially expensive, so we could look at trying to optimize halogen-vdom around that.

**Comment by saurabhnanda** [comment]
Just wondering if [consing to create a large list/vector](https://github.com/saylu/purescript-framework-benchmark/blob/986bbd0b6bcd9b2f92cb71a874e52ebc547c29fd/halogen-v2.1.0/src/Main.purs#L125-L146) is the recommended approach in Purescript? I had worked on a Miso/GHCJS benchmark and had used [Vector and its associated `generateM` function](https://github.com/vacationlabs/js-framework-benchmark/blob/db042bdb3fe07c98294f1493fbeb863ccf501eb4/miso-non-official-v0.4.0.0-non-keyed/app/Main.hs#L106-L111) to get the job done. It seemed to be performing considerable faster.

**Comment by natefaubion** [comment]
@saurabhnanda While consing isn't efficient, the data generation part of the test is negligible when compared to the inefficiency of diffing the entire tree every tick.
