### ISSUE TITLE
Add a thunk widget to `HTML`

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-halogen#475]
This is helpful for people who want to go with more of a TEA approach. I have an implementation already in spork: https://github.com/natefaubion/purescript-spork/blob/master/src/Spork/Html/Thunk.purs

Maybe I could move this implementation to halogen-vdom and it could be shared?

**Comment by garyb** [comment]
This was done somewhere between v4 and the current v5 RC. 👍
