### ISSUE TITLE
Is there a way to cancel an event source subscription from "outside"?

### ISSUE THREAD

**Issue by mpodlasin** [slamdata/purescript-halogen#479]
I am trying to implement throttling (send HTTP request after few keystrokes, instead of immediately) with `EventSource`. I succesfully implmeneted some delay with `setTimeout` but I realized that there doesn't seem to be a way to cancel ticking `setTimeout` clock from "outside".

You can do that only form inside query cases in `eval` which will be called by subscribed event source, but this would be equivalent to being able to cancel `setTimeout` only from within passed callback:

```purescript
 -- parts of eval function:
    InputChange newInput next -> do
     -- when InputChange is called again I would like to cancel previous subscription, but I can't?
      H.subscribe $ HES.eventSource_' (\eff -> do
        id <- setTimeout 1000 eff
        pure $ void $ clearTimeout id) (H.request FetchOptions)
      H.modify \state -> state { input = newInput, options = Nothing }
      pure next
    FetchOptions status -> do
      input <- H.gets \state -> state.input
      when (input /= "") do
        getOptions <- H.gets \state -> state.getOptions
        options <- H.lift $ getOptions input
        H.modify \state -> state { options = Just options }
      pure $ status H.Done
```
It seems to me that `subscribe` should return some kind of mechanism for cancelling subscription.

**Comment by garyb** [comment]
You can already use an `Aff`-based `EventSource` to do this, but the implementation is a little more complicated than what you have here: https://github.com/natefaubion/slamdata/blob/8d7534b0a8e9819b2719ca088c620cf098630c80/src/Halogen/Component/Utils/Debounced.purs

As another simpler alternative that might work, you could use `fork`, something like:

``` purescript
  InputChange newInput next -> do
    cancel (error "cancelled") =<< H.gets _.canceller
    canceller <- H.fork do
      H.liftAff (delay 1000)
      when (newInput /= "") do
        getOptions <- H.gets _.getOptions
        options <- H.lift $ getOptions newInput
        H.modify (_ { options = Just options })
    H.modify (_ { options = Nothing, canceller = canceller })
    pure next
```

(I didn't compile this or anything, so probably needs tweaks. `cancel` is from `Control.Monad.Fork.Canceler`, `delay` is from `Control.Monad.Aff`)

This version means you don't have to keep the pending `input` in the component state, and you don't need to break the operation into two queries.

**Comment by mpodlasin** [comment]
Thank you very much! I'll try both approaches soon!

**Comment by garyb** [comment]
I'm quite late in coming back to this, but I've marked this issue as a desired enhancement, as the current subscribe API is actually kinda problematic (it behaves in a way that is surprising when a query raised by a subscription is async), so in the future I'll change it so subscriptions return a canceller.
