### ISSUE TITLE
Direct access to input in render and eval

### ISSUE THREAD

**Issue by mpodlasin** [slamdata/purescript-halogen#480]
Currently I have to "save" input in my state in order to use it later in render and eval. But this is not really a state, since these values are not going to change throughout lifecycle of component. I would prefer to have direct access to input values in render and eval functions.

**Comment by garyb** [comment]
I see where you're coming from, but that's strictly less powerful than the way things currently work. You'd lose the ability to evaluate a query to do something "interesting" (effectful / more complicated than just storing the value in the state) when the input changes.

Also, to avoid inefficiency it'd have to impose an `Eq` constraint on the input - currently that requirement is left up to the component. Without that, there's no choice about re-rendering the child only when the input value changes - it would have to render every time the parent renders too.

Having said all that, I think you should be able to build a component with an input that behaves the way you're describing on top of the existing component scheme.

**Comment by natefaubion** [comment]
If it does not change throughout the lifecycle of your component (ie, it's just an environment), you can just make it a function `MyEnv -> Component ...`.

**Comment by mpodlasin** [comment]
Yup, I felt that this is some kind of design choice. Explanation of motivation was very helpful. Thanks!
