### ISSUE TITLE
Approach to supporting electron components?

### ISSUE THREAD

**Issue by maxhillaert** [slamdata/purescript-halogen#485]
Hi,

Not an issue, but a question.

I want to use halogen with electron in my project, so I'm going to start setting up purescript-halogen-electron repo.  My feeling is that runUI will basically run a Window Manager Halogen component with a NewWindow, CloseWindow , etc query algebra.  

Does anyone foresee any issues I may encounter or maybe share some thoughts they may have around a halogen electron components.

Cheers

Max

**Comment by maxhillaert** [comment]
Having started this.  I'm running into the question of whether a Window Manager component is really supported.  It doesn't really output html, so shouldn't have a render function.  
A window manager component should have input, state , query, state and child components (Windows) but no rendering.  Can I model this?
Should I be taking the approach where there is a single halogen application per window and forget about root window manager component?
Is that possible?

**Comment by kRITZCREEK** [comment]
@maxhillaert If I remember correctly from when I was doing Electron, your application is split into renderer and a main thread. Now the renderer threads are just your regular webapp with the addition of being able to directly access and use node dependencies. This sounds like a great fit for Halogen.

The main thread coordinates these renderer threads and handles inter-process-communication to route information in between your separate windows. I don't think this is where you should use Halogen. Depending on how much work you really need to do in this thread you could either write it in JS, or use bindings to the Electon API and write a PureScript program that doesn't use Halogen.

**Comment by maxhillaert** [comment]
OK, sounds like me like you suggest the second approach where I have the window manager/bootstrapping part create windows in vanilla purescript and have the root level for halogen be a window.  I suppose I can have new window requests from a halogen window, percolate upwards via messages.
I'll play around a little and when I get further check with you guys I've got the idiomatic stuff best as can be.

**Comment by maxhillaert** [comment]
What's a ComponentPure used for typically.  Seems like it could be useful somehow for Electron components that emit message, have algebras , evaluation and messages, but no rendering.

**Comment by maxhillaert** [comment]
Upon closer examination of how electron works, I don't see a tremendous amount of value to be added in terms of a purescript-halogen-electron repo.  Seems to me halogen would live within the context of a page loaded by a renderer process BrowserWindow and not be aware of electron windows. 
Only thing I can see maybe working is 
* a BrowserWindow component, that has a query algebra for focus, unfocus, zoom, child windows, etc
* Aff based API over the Ipc stuff to communicate with the main process which would be vanilla purescript-electron based

**Comment by kRITZCREEK** [comment]
Let us know how it works out :) Do you think we can close this issue?

**Comment by paul-rouse** [comment]
Sorry I am a little late spotting this.  You might like to have a look at https://github.com/neume-notation/expo, which is a project I finished in April - it is described more fully in the README in that repo.  Its primary target is a museum/library environment, where it is run under Electron in kiosk mode.

In this particular case almost all of the data is static, apart from one very trivial visit-counting URL implemented by a tiny server in the main Electron [JavaScript file](https://github.com/neume-notation/expo/blob/master/StandAlone/run.js).  However, I'm sure you would be able to implement some more sophisticated ipc, as you say.
