### ISSUE TITLE
render time lag when handling window click event to hide dropdown

### ISSUE THREAD

**Issue by rnons** [slamdata/purescript-halogen#499]
I have a simple component with a text input and a dropdown.
When the input is focused, the dropdown shows up
When click outside, the dropdown hides.

The problem as shown in the screen cast below is, when I focus to another input, there is noticeable time lag between new dropdown shows up and old dropdown hides.

![kapture 2017-12-26 at 11 06 48](https://user-images.githubusercontent.com/1082650/34344847-7d03a948-ea2d-11e7-8f8a-670c34c43970.gif)

I'm not sure this is an issue or I'm doing something wrong. Relevant code is at https://github.com/rnons/purescript-webpack-example/blob/dropdown/src/Child.purs#L84

**Comment by safareli** [comment]
I guess focus handler is fired first and then `ClickWindow` is fired resulting in the behavior you have.

You might want to change `false` to `true` here https://github.com/rnons/purescript-webpack-example/blob/dropdown/src/Child.purs#L72

take a look at `useCapture` here https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by rnons** [comment]
@safareli Thank you, I understand focus is fired first. I thought I have used this pattern in react and didn't see a problem. I just tried again and find it's the same https://codesandbox.io/s/4j3oo79170

For anyone interested, I have changed to add an `onMouseDown` to the container element. `onMouseDown` will fire before `<input>`'s `onBlur`, so can be used to check if it's an inside click. https://github.com/rnons/purescript-halogen-day-picker/blob/master/src/Halogen/DayPickerInput.purs#L151

**Comment by rnons** [comment]
Another way that works is listen to `window.onMouseDown` instead of `window.onClick`, made a simple codepen https://codepen.io/rnons/pen/OzzeQO?editors=1001
The events sequence is: mousedown -> focus/blur -> mouseup -> click

**Comment by safareli** [comment]
As I know (might be wrong here) halogen performs dom update on each state change so if you have:
``` purescript
H.put state1
H.put state2
```
dom will be updated 2 times.

In your example this is what should be happening. handler of blur changes state and dom is rerendered for that component, then onclick of window fires and state of another component changes and it's dom is rerendered too. While React batched dom updates, so you have no such issue. 

@garyb @natefaubion @cryogenian might confirm if that's true.

**Comment by cryogenian** [comment]
> @garyb @natefaubion @cryogenian might confirm if that's true.

I confirm :wink:

**Comment by natefaubion** [comment]
@safareli React behaves the same as Halogen in this case, but yes, in Halogen, component eval will not proceed after a state modification until the render has been committed for that component. This is because it's observable. That is, you must be able to query a child mounted which would be mounted as a result of a render. React does not asynchronously batch updates across events (by default), since you can't rely on controlled inputs if that was the case.

**Comment by safareli** [comment]
Actually I played with https://codesandbox.io/s/4j3oo79170 and it has same issue.

@rnons you might need to use `blur` to hide dropdown (so it works on tab too and blur will fire before focus I think)

**Comment by rnons** [comment]
@safareli you're quite right, that's what I realized after creating the codesandbox example, and that's why I closed this issue 😃 . Sorry I didn't make myself clear in that comment.

Your're right about the `blur` as well, I already did that in the `purescript-halogen-day-picker`. Thank you very much.
