### ISSUE TITLE
Need help with async/dependent queries and rendering in between

### ISSUE THREAD

**Issue by machinedgod** [slamdata/purescript-halogen#511]
Hi,
thanks for the awesome library!

I am having a bit of a issue with this situation: in a component tree, one subcomponent should (upon received query) fire off an affjax request, and start animating immediately. When animation ends, another query is invoked and that same ajax request should be finished (its OK to block and wait if it hasn't) and some state updating done with the payload.

I managed to solve this by wrapping my payload data into an `AVar`, however the problem is that (unless I understood something wrong), effects can only be invoked inside `eval`. This means that during initial construction, I need to pass `AVar` instance (made with `makeEmptyVar`) from the outside.
Since my component exists as a part of a component tree, I have to create this right inside initial `runHalogenAff` and then carry this piece of data downwards to the place where its actually used.

While it works, it just seems really awkward to have to carry this very component-specific data downwards, and I was wondering if there's any better, cleaner way of doing this (aside wrapping entire Component with an Aff)?

Another approach I've tried is forking on the Start query and storing a Fiber into my state, then joining in my End query and manipulating the data, but after fiddling with type signatures for about 30 minutes, I gave up (perhaps wrongly) under pretense that this is impossible.

**Comment by safareli** [comment]
I think you need `lifecycleComponent` take a look at this example https://github.com/slamdata/purescript-halogen/tree/master/examples/lifecycle/src

**Comment by machinedgod** [comment]
If I understand example and your suggestion correctly, is it because I get the opportunity to Initialize component inside eval (where I can invoke sideffects)?
I guess I could do this and wrap my `AVar` with a `Maybe` (to be `Nothing` in `initialState` and `Just` immediately after `initializer`) - but this `Maybe` introduces notions in my `State` that I'm not really happy about (ie. the notion that avar might not be present during all `evals`).
I wonder if it'd be better to just keep the State as it is, and wrap my `parentComponent` with an Aff. It would indicate strongly that creating this component simply requires sideffects, and propagate this need into any other component that wants to parent them.

**Comment by safareli** [comment]
> If I understand example and your suggestion correctly, is it because I get the opportunity to Initialize component inside eval (where I can invoke sideffects)?

Yes

>  I guess I could do this and wrap my AVar with a Maybe (to be Nothing in initialState and Just immediately after initializer) - but this Maybe introduces notions in my State that I'm not really happy about (ie. the notion that avar might not be present during all evals).

Yes you need to do that. It's usual thing with halogen, you can use `for_` over Maybe AVar:

``` purs
state <- h.get
-- if var is Just _ then do block will be executed
-- otherwise it's "noop" which is what we want.
for_ state.var \var -> do
  doSomethingWIththe var
```

Or you can make your state a sum type `data State = UnInitialised | initialised { var :: Avar}`
But it would be a bit tedious to work with this kind of state.

**Comment by machinedgod** [comment]
Thanks for the time and explanations! I didn't know this is a common pattern in Halogen code. In light of this, I'll go and modify my code to act this way.

**Comment by safareli** [comment]
You can take a usages of `lifecycleParentComponent` here https://github.com/natefaubion/slamdata

**Comment by machinedgod** [comment]
Just wanted to say thanks for the help once again. I modified the code according to your suggestions and it looks much better than before.

**Comment by safareli** [comment]
You are welcome!
