### ISSUE TITLE
SVG with <use> tag not loading external resource

### ISSUE THREAD

**Issue by machinedgod** [slamdata/purescript-halogen#518]
Hi all,
I have HTML DSL code that creates `<svg>` element and adds `<use>` tag inside it, to reference external SVG file.
Problem is, when I load the page, no SVG's are shown, and Network tab shows that my external resource is not loaded.

Furthermore, I tried to debug the issue, and I've found out this, using the browser debug interface: if I copy the rendered element HTML and manually paste it inside <body> tag, all of the sudden the external file is fetched and all other rendered `<svg>` tags now show properly. I can delete the tag that I've manually copy-pasted and things still show as expected.
Before this test, I was suspecting CSS was doing something weird (and I've spent some time trying to see if this is true) but this was evidence enough for me that issue lies with fetching those external resources.

I've suspect the issue is the browser's behaviour (tested with Chromium and Palemoon) when elements are added through VDom, not loaded through raw HTML - so I've tried adding a single SVG element in the body that uses same external resource. While this manually added element shows properly, rendered HTML does not.

I'm stumped a bit, and could use some help figuring this out.
This is my SVG code:
```
svg ∷ ∀ r p i. Array (IProp r i) → Array (HTML p i) → HTML p i 
svg p = element (ElemName "svg") p


use_ ∷ ∀ p i. String → String → HTML p i 
use_ f i =
    element (ElemName "use")
        [ attr (AttrName "xlink:href") (f <> "#" <> i) ]
        [] 
``` 

The rendered HTML looks like this:
```
<svg class="svgProp"><use xlink:href="res/fruit_atlas_optimized.svg#onion_sprout"></use></svg>
```

**Comment by safareli** [comment]
I had same issue a while ago, this should work:
```
svgElem (H.ElemName "svg")
    [ H.attr (H.AttrName "viewBox") "0 0 10 10"
    , H.attr (H.AttrName "class") ("Icon Icon-foo")
    , ARIA.hidden "true"
    ]
    [ svgElem (H.ElemName "use")
      [ xlinkAttr (H.AttrName "xlink:href") "res/fruit_atlas_optimized.svg#onion_sprout" ]
      [ ]
    ]
where
svgElem = H.elementNS $ H.Namespace "http://www.w3.org/2000/svg"
xlinkAttr = H.attrNS $ H.Namespace "http://www.w3.org/1999/xlink"

```

**Comment by machinedgod** [comment]
Nice, it works!
Thanks for quick (and correct) reply, as always :-) Can you give me a quick explanation of why the `elementNS`, `attrNS` and `ARIA.hidden` make the difference? Was I on the right track assuming that browser isn't picking up the SVG resource because the DOM is being modified?

Additionally, thanks for the link - I realized, while messing with this code, that using `prop` didn't seem to set any attributes on my elements, and then I learned there's also `attr`- and got confused about the difference.

**Comment by safareli** [comment]
ARIA.hidden is not needed it's just example, demonstrating that you could use normal halogen attributes. 

Here is a good explanation of this staff https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course#Scripting_in_namespaced_XML
