### ISSUE TITLE
Runtime error related to slots

### ISSUE THREAD

**Issue by jjl** [slamdata/purescript-halogen#519]
I'm new to Purescript and Halogen, so I'm not quite sure what's going on here, but my browser informs me `TypeError: v is undefined`.

It gets triggered when I embed a single child in a parent component where my render function contains this (the child slot type is Unit):

```purescript
HH.slot unit Nav.component Nothing (const Nothing)
```

Here's the generated code:

```
var slot = function slot(p) {
    return function (component) {
        return function (input) {
            return function (outputQuery) {
                var f = Halogen_Component.unComponent(function (v) {
                    return v.receiver; /// ERROR ON THIS LINE
                })(component);
                return Halogen_HTML_Core.slot(Halogen_Component.mkComponentSlot(p)(component)(input)(f)(outputQuery)(Data_Maybe.Just.create));
            };
        };
    };
};
```
Latest halogen from bower.

**Comment by safareli** [comment]
I think if `v` is undefined it means `component ` is undefined. Which means `Nav.component` is undefined. maybe run `rm -r .output` and rebuild it again?

**Comment by jjl** [comment]
Ah yes, that worked perfectly. Sorry for the mistake :)

**Comment by safareli** [comment]
No problem 🙌
