### ISSUE TITLE
Replace (not fill) the root HTML element

### ISSUE THREAD

**Issue by abaco** [slamdata/purescript-halogen#524]
I'm trying to create pages with arbitrary content directly in the body, something like this:

```html
<body>
  <header></header>
  <article></article>
  <footer></footer>
</body>
```

As far as I understand this is currently impossible with Halogen. The reasons are:

A) components have a single root HTML element;
B) `runUI` inserts the root component into the chosen container element.

So if `<body>` is chosen as the container element, there will necessarily be a wrapping element between `<body>` and the component's content. I have to avoid the wrapping element because I want my pages to work with existing, arbitrary stylesheets.

A solution to my problem would involve relaxing either A) allowing multiple root elements in components, or B) replacing the whole root element with my root component. I think the latter option is the more feasible. My root component could then have as root element a `<body>`, which would *replace* the existing `<body>`.

First of all: does this make sense? Are there any other options I've missed?

I had partial success by modifying the [`render`](https://github.com/slamdata/purescript-halogen/blob/v3.1.3/src/Halogen/VDom/Driver.purs#L127) function thus:

```diff
-       void $ DOM.appendChild node (DOM.htmlElementToNode container)
+       let containerNode = DOM.htmlElementToNode container
+       parent <- DOM.parentNode containerNode
+       traverse_ (\pn -> DOM.replaceChild node containerNode pn) parent
```

This works fine with a childless root component, but as soon as I add a child nothing is rendered. Unfortunately I can't wrap my head around the rest of `runUI` - still a PureScript newbie...

Thanks in advance for your help!

**Comment by garyb** [comment]
Trying to modify `render` that way doesn't work as that function is used to render all components recursively, not just the root level - so by replacing the parent each time, it's flattening the hierarchy at too many levels. Aside from that it probably doesn't work because the VDom patching can't proceed when the node being patched is not what it is expected to be :wink:.

You can just do the replacement outside of Halogen though in your main function, something like this:

``` purescript
module Main where

import Prelude

import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Class (liftEff)
import Control.Monad.Maybe.Trans (MaybeT(..), lift, runMaybeT)
import DOM.HTML.Types (htmlElementToNode)
import DOM.Node.Node (removeChild)
import DOM.Node.ParentNode (QuerySelector(..))
import Halogen.Aff as HA
import Halogen.VDom.Driver (runUI)

main :: Eff (HA.HalogenEffects ()) Unit
main = HA.runHalogenAff do
  HA.awaitLoad
  runMaybeT do
    html <- MaybeT $ HA.selectElement (QuerySelector "html")
    body <- MaybeT $ HA.selectElement (QuerySelector "body")
    _ <- liftEff $ removeChild (htmlElementToNode body) (htmlElementToNode html)
    lift $ runUI ?component unit html
```

**Comment by abaco** [comment]
Thank you, @garyb! It works, it's clean, and I also understand why it works :smiley:
