### ISSUE TITLE
Subscribe to window resize event?

### ISSUE THREAD

**Issue by costructuralist** [slamdata/purescript-halogen#527]
As I understand it, subscription to the window resize event should happen within the `initializer` of a lifecycle component, since the `render` function only has access to the body element of a page, and not the window itself.

I'm having trouble navigating the types around `eventSource` though, and have come as far as the following (analogous to [this example](https://github.com/slamdata/purescript-halogen/blob/master/examples/keyboard-input/src/Main.purs)):

```
H.subscribe $ ES.eventSource' (?) (Just <<< H.request <<< WindowResizeQuery)
```

What should replace the `?` above?  Or is this approach flawed?

**Comment by safareli** [comment]
something like this should work (haven't compiled tho).
``` purescript
import DOM.HTML.Window (document)
import DOM.HTML (window)
import DOM.Event.EventTarget as (addEventListener, removeEventListener, eventListener)
import DOM.HTML.Types (windowToEventTarget )
import DOM.HTML.Event.EventTypes as (resize)
import Halogen as H
import Halogen.Query.EventSource as ES

do
  win ← H.liftEff $ window <#> windowToEventTarget 
  H.subscribe $
    H.eventSource'
      (\f -> do
        let listener = eventListener f
        addEventListener resize listener false win
        pure $ removeEventListener resize listener false win
        )
      (\e -> pure $ WindowResized ES.Listening)
```

you can also do:
```

**Comment by costructuralist** [comment]
Thank you - it works!  Just had to add `avar :: AVAR` to non-component-state effects of component.

**Comment by safareli** [comment]
Great, you are welcome!
