### ISSUE TITLE
`onValueInput` not triggered

### ISSUE THREAD

**Issue by thoferon** [slamdata/purescript-halogen#534]
I tried the example `effects-aff-ajax` (https://github.com/slamdata/purescript-halogen/blob/compiler/0.12/examples/effects-aff-ajax/src/Component.purs) with `#compiler/12.0` and `onValueInput` doesn't seem to work. Replacing the call with

```
HE.onValueInput (\value -> trace value \_ -> HE.input SetUsername value)
```

does not result in anything being logged. `onClick` works fine though.

**Comment by cryogenian** [comment]
This is already fixed in `master`

**Comment by thoferon** [comment]
My bad! I should have checked. Thanks.
