### ISSUE TITLE
Questions regarding the development of this project

### ISSUE THREAD

**Issue by JordanMartinez** [slamdata/purescript-halogen#542]
I would ask this question in a chat room, but I don't see one listed on your ReadMe and couldn't find one on Gitter.

I'm trying to create a library that can be used to build purely functional GUI programs using Scala, Scalaz, and the Java GUI toolkit, JavaFX. I was advised by a person in the scalaz Gitter chat to look at this project and [Transient](https://github.com/transient-haskell/transient/) since both have to manage state. I've read through this project's docs and have looked through some of the source code.

I was wondering whether any of the contributors here would care to answer some questions regarding the history of this project and give context for the design decisions they made.

**Comment by thomashoneyman** [comment]
@JordanMartinez you might have luck with these discussion forums:

- Many core contributors are active on the [PureScript user forum](https://purescript-users.ml) which is best for longer Q&A
- For quick questions, the [functional programming Slack](https://functionalprogramming.slack.com/) community is very active. [Use this link to join](https://fpchat-invite.herokuapp.com/)!).

There isn't a Halogen-specific forum but the folks who wrote it tend to hang out in those two places.

**Comment by JordanMartinez** [comment]
@thomashoneyman Thanks for the links! I'll try contacting them on there.

**Comment by garyb** [comment]
The discussion move to here: https://purescript-users.ml/t/questions-regarding-the-development-of-the-purescript-halogen-library/236 🙂
