### ISSUE TITLE
Add cleanup/unmount effect to HalogenIO

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-halogen#544]
Right now we assume that a `runUI` instance should run forever, but this isn't the case a lot of times when integrating Halogen components into an existing app. Maybe we could provide some way to unmount the app and run finalizers.

**Comment by garyb** [comment]
I guess this'd just be an `Aff Unit` returned in the `DriverIO` or something?

**Comment by natefaubion** [comment]
Yes. There likely needs to be some sort of state, and then throw when trying to query or subscribe.
