### ISSUE TITLE
add comment about `fork` function

### ISSUE THREAD

**Issue by safareli** [slamdata/purescript-halogen#546]
It might not be clear what happens to forked process when component is unmounted (nothing happens)

**Comment by garyb** [comment]
I'm going to add comments in #545 once I've confirmed it's working properly... hopefully with an automated test.

**Comment by garyb** [comment]
In fact, better still, I'm going to make component finalization kill any running forks the way we kill subscriptions too. Will be done along with #544.

**Comment by safareli** [comment]
yaah!

If fork is killed, like subscriptions are, what's the point of subscription? as fork is more powerful because  `HalogenM` is used instead of `Eff`.

also before if you did this:
``` purs
H.modify _{loading=true}
H.fork do
  sendRequestA
  sendRequestB
  H.modify _{loading=false}
```
both request would have been sent if component was unmounted but now second might not be sent, So we should document that clearly, we might need something like `invincible` from Aff maybe.

**Comment by garyb** [comment]
I've talked a bit about the same thing with Christoph. Fork is too powerful in some ways, it's much easier to blow your leg off with that than subscriptions. Also, subscriptions deal with the looping behaviour for persistent listening in a way that every user of fork would have to do for themselves.

It's definitely something I'm interested in thinking more about, but for the v5 release at least we're keeping both of them.
