### ISSUE TITLE
Latest Documentation Has Not Been Published to Pursuit

### ISSUE THREAD

**Issue by AlexaDeWit** [slamdata/purescript-halogen#556]
Current Pursuit latest is 3.1.3.

Would be full of love to see the current 0.12 compatible version uploaded.

**Comment by AlexaDeWit** [comment]
Understandable. Thanks for the quick update on the state of things.

**Comment by safareli** [comment]
with --max-old-space-size flag docs might be possible to publish https://github.com/purescript-contrib/pulp/issues/351#issuecomment-406097417

**Comment by garyb** [comment]
Harry pushed docs for this a while ago, after sorting out a new format / updating Pulp 🙂
