### ISSUE TITLE
Include Halogen Ecosystem links on ReadMe

### ISSUE THREAD

**Issue by JordanMartinez** [slamdata/purescript-halogen#558]
Since @garyb mentioned [purescript-halogen-svg](https://github.com/kwohlfahrt/purescript-halogen-svg) in answer to my question [here](https://purescript-users.ml/t/questions-regarding-the-development-of-the-purescript-halogen-library/236/10?u=jordanmartinez), I searched GitHub and found a number of other Halogen-related libraries.

I thought it might be helpful to include an index of Halogen-related libraries on the ReadMe. Would such a PR be desired?

**Comment by JordanMartinez** [comment]
For example, something like this:

## Halogen Ecosystem

- [Most popular Halogen Libraries](https://github.com/xgrommx/halogen-ecosystem)
- [Halogen Project Template](https://github.com/slamdata/purescript-halogen-template) - Template for starting a fresh project using the Halogen library

### Utilities 

- [SVG](https://github.com/kwohlfahrt/purescript-halogen-svg) - A collection of SVG elements for Halogen
- HTML Source to Halogen Views Parsers
    - [SVG Parser](https://github.com/rnons/purescript-svg-parser-halogen) - inline SVG source string into Halogen views
    - HTML Parser - [rnons](https://github.com/rnons/purescript-html-parser-halogen) / [maackle](https://github.com/maackle/html2purescript) - render raw HTML string into Halogen views.
- [Halogen VDOM to String Renderer](- [String Renderer](https://github.com/slamdata/purescript-halogen-vdom-string-renderer) - String rendering for halogen-vdom

### Libraries for Component Development

- [Color picker](https://github.com/slamdata/purescript-colorpicker-halogen) - A bunch of components that can be used to build a color picker
- [Formless](https://github.com/thomashoneyman/purescript-halogen-formless) - A renderless component that helps you build forms
- [Proxy](https://github.com/slamdata/purescript-halogen-proxy) - Utility component that proxies an inner component to hide all/part of its query algebra
- [Renderless](https://github.com/thomashoneyman/purescript-halogen-renderless) - Helper functions & templates for building renderless components in Halogen. In other words, implement a component's behavior and state but delegate its rendering to the developer using it
- [Select](https://github.com/citizennet/purescript-halogen-select) building blocks for common selection UI (e.g. dropdown menu, typeahead, autcomplete, multi-select, calendar, image picker, etc.)

### Reusable Components (Standalone)

- Pickers
    - [Calendar DatePicker](https://github.com/twitchard/purescript-halogen-calendar-datepicker)
    - [Color Palette Picker](https://github.com/slamdata/purescript-colorpalettepicker-halogen) - Color Palette picking
    - [Date picker](https://github.com/slamdata/purescript-halogen-datepicker) - Pickers for Date, Time, DateTime, Duration, and Interval
    - [Day Picker](https://github.com/rnons/purescript-halogen-day-picker) - provides `DayPicker` and `DayPickerInput` components
    - [File Picker](https://github.com/zudov/purescript-halogen-filepicker) - Helper functions for handling file uploads
- Other
    - [Ace](https://github.com/slamdata/purescript-ace-halogen) a component for the [Ace editor](https://ace.c9.io/)
    - [Autocomplete](https://github.com/kRITZCREEK/purescript-halogen-autocomplete) - Simple autocomplete component for Halogen
    - [Dialogs](https://github.com/brunjlar/purescript-halogen-dialog) - support for modal dialogs
    - [HTML Component](https://github.com/garyb/purescript-halogen-html-component) - encapsulates a region of arbitrary HTML
    - [JS Barcode](https://github.com/narinari/purescript-js-barcode-halogen) - Component for JsBarcode
    - [Mailing List](https://github.com/naglalakk/halogen-mailing-list) - Mailing list component
    - [Menu](https://github.com/slamdata/purescript-halogen-menu) - a reusable Halogen component that presents an interactive menu
    - [Number Input](https://github.com/slamdata/purescript-number-input-halogen) - A wrapper for HTML number input
    - [QR Code](https://github.com/narinari/purescript-qrcode-js-halogen) - QR Code
    - [Tooltip](https://github.com/MonoidMusician/purescript-halogen-tooltip) - simple tooltip component that proxies input into and out of a wrapped component, maintaining its hover state internally.
    - [Signature Pad](https://github.com/narinari/purescript-signature-pad-halogen) - Signature Pad
    - [Sprite Editor](https://github.com/epost/purescript-halogen-sprite-editor) - editor for creating/editing sprite graphics for Commodore 64
    - [Zuruzuru](https://github.com/MonoidMusician/purescript-halogen-zuruzuru) - A simple list reordering component, drag-and-drop style

### Reusable Components (Bundled)

- [PS Hendry](https://github.com/pshendry/purescript-pshendry-halogen) - Components for input types (integers only, numbers only, text only)
- [newslandvalley](https://github.com/newlandsvalley/purescript-halogen-components) - components useful in building various music player / editor applications (soundfont melody player, file input select, multiple select dropdown, trivial button)
- [fnords](https://github.com/AidanDelaney/purescript-halogen-fnords)

### Integration with other libraries

- [Bootstrap](https://github.com/slamdata/purescript-halogen-bootstrap) - Bootstrap 3 classes and utilities for Halogen
- [CSS](https://github.com/slamdata/purescript-halogen-css) - An adapter between `purescript-halogen` and `purescript-css` libraries
- [Echarts](https://github.com/slamdata/purescript-halogen-echarts) - integration for Echarts via the `purescript-echarts` library
- [Electron](https://github.com/maxhillaert/purescript-halogen-electron) - Exploration of a Halogen/Electron stack
- [Giphy](https://github.com/peeb/purescript-giphy) - Find a random type-safe GIF
- [Leaflet](https://github.com/slamdata/purescript-leafletjs-halogen) - Embedding leaflet geocharts to Halogen
- [Markdown](https://github.com/slamdata/purescript-markdown-halogen) - A Halogen rendering library for `purescript-markdown`
- [React](https://github.com/doolse/purescript-halogen-react)
- [Tachyons](https://github.com/citizennet/purescript-halogen-tachyons) - integration for tachyons

**Comment by garyb** [comment]
Maybe we'd be better off using a GH wiki page for this? I'm hesitant to include it in the "official" documentation since a bunch of these I know for sure are not up to date with the latest release. By having it in the Wiki it can be updated easily by authors who come up with new stuff rather than having to PR it too.

**Comment by JordanMartinez** [comment]
Makes sense. It's been added to the wiki and linked to in the home page.

**Comment by garyb** [comment]
Great, thanks for working on it! I've added a reverse link from the README too.
