### ISSUE TITLE
[Suggestion] Use long names for type variables

### ISSUE THREAD

**Issue by NickSeagull** [slamdata/purescript-halogen#562]
Hi, before all, thanks for Halogen, its awesome and I love it.

I was trying to teach Halogen to some friends and the biggest pitfall I've seen were the single-letter type variable names. In the end they had to have a little paper cheatsheet to know what type variable was what.

What would you think about using long type variable names, for example:
- `html` instead of `h`
- `state` instead of `s`
- `query` instead of `f`
- `childQuery` instead of `g`
- `childSlot` instead of `p`
- `message` instead of `o`

I think that this would help a lot of newcomers to halogen to pick up this easily, as I've seen some people switching to Elm just because of this. I'd love Halogen to be more adopted :grin: 

**Please let me know what you think about this, I'd be happy to submit a PR**

**Comment by safareli** [comment]
#388 is somewhat related

**Comment by NickSeagull** [comment]
Yeah, but tagging them I think is a bit overkill, just renaming them so the docs appear in a nice way will suffice I think :smile:

**Comment by JordanMartinez** [comment]
`h` doesn't have to be `html` since it could be some other renderer.

**Comment by NickSeagull** [comment]
Yeah, it can be `renderer`. But for the sake of the beginners @JordanMartinez

**Comment by garyb** [comment]
I think the quantity of type variables, and that they vary depending on whether you're talking about `Component`, `HTML`, or `HalogenM` is as much of a problem as the names - although I did ensure that at least they appear in the same relative order everywhere. I think even with long names having a cheat-sheet to remember these variations is pretty much necessary.

I'm torn on this. I did try longer names as an experiment once, but on the whole it seemed to make deciphering types at a glance more difficult, as in a screen full of words it's harder to pick out the concrete types from the variables, as case is the only signifier.

``` purescript
type ComponentSpec h state query action slots input output m =
  { initialState :: input -> state
  , render :: state -> h (ComponentSlot h slots m action) action
  , eval :: HalogenQ query action input ~> HalogenM' s action slots output m
  }
```

On the upside, in master, at least `g` and `p` are merged as the `ps` row now (`slots` in my example above).

**Comment by NickSeagull** [comment]
I don't know, for me it makes much more sense your example, than having single letters... 🤔

**Comment by JordanMartinez** [comment]
@NickSeagull Good point!

@garyb If case is the only signifier, what if something else was added to make it clearer (i.e. `_`)? For example, rather than `h` or `html`, what if it was `html_`? Or perhaps (not sure whether this is legal syntax) `_html`?

**Comment by garyb** [comment]
As of #594 all (I think I got them all anyway) public facing type variables have been given long names.
