### ISSUE TITLE
The examples don't compile

### ISSUE THREAD

**Issue by chrisdone** [slamdata/purescript-halogen#566]
For example, the basic button one:

https://github.com/slamdata/purescript-halogen/tree/master/examples/basic

With a basic `psc-package.json`:

```
{
    "name": "wibble",
    "set": "psc-0.12.0",
    "source": "https://github.com/purescript/package-sets.git",
    "depends": [
        "prelude",
        "console",
        "halogen"
    ]
}
```
```
  Could not match kind

    Type

  with kind

    # k17 -> k15


while checking the kind of State -> ComponentHTML Query () m0
while checking that expression component { initialState: ...
                                         , render: ...
                                         , eval: ...
                                         , receiver: ...
                                         , initializer: ...
                                         , finalizer: ...
                                         }
                                 where
                                 render = \state ->
                                            let
                                              ...
                                            in ...
                                 initialState = false
                                 eval = \$0 ->
                                          case $0 of
                                            ...
                                            ...
  has type Component HTML Query Unit Message m0

```

Apparently a bunch of types have had parameters removed in various types, in addition to `finalizer`  and `initializer` being removed. Probably other things that I haven't seen yet.

Perhaps you could add your examples to your CI script? 

In any case, can anyone suggest a psc-package package set that is capable of compiling halogen's examples? I'm into using this library, but most of its types have half a dozen parameters, and the documentation all refers to these types.

**Comment by justinwoo** [comment]
Are you trying to compile the examples copied from the examples on master? You might want to look at examples in your downloaded sources at `.psc-package/{set}/halogen/{version}`

**Comment by chrisdone** [comment]
@justinwoo Good tip, I'll take a look there, thanks!

**Comment by garyb** [comment]
Yeah, the version in master is the "next" version, so the examples have been updated for that - they are actually tested by CI. 

It's caught a few people out, I'll change the links in the README to point to the appropriately versioned release instead. Shame there isn't a URI I can use that would permanently work for that!

**Comment by chrisdone** [comment]
Cheers all! The example from inside the `.psc-package` dir all compile. Just for posterity (error message googling), here's the difference in API:

```haskell
H.ComponentDSL State Query Message m -- old way
```
has now become:

```haskell
H.HalogenM State Query () Message m -- new way
```

in the example.

**Comment by garyb** [comment]
Sorry for the confusion! :smile:

**Comment by paulyoung** [comment]
> Shame there isn't a URI I can use that would permanently work for that!

@garyb, can you use relative paths?

**Comment by garyb** [comment]
@paulyoung you can, that's how they were done before, but I can't have it so the links in the readme point to any kind of `{latest}/examples/...` kinda thing. There is a https://github.com/slamdata/purescript-halogen/releases/latest URI, but that only works for an actual release, you can't link to files under it as far as I can tell.
