### ISSUE TITLE
Create a keyEvent html node.

### ISSUE THREAD

**Issue by yogsototh** [slamdata/purescript-halogen#567]
I've got a very specific need. I'd like to handle `onkeypress` events on a `pre` that I made editable via `<pre contentEditable="true" tabindex="0">...`.

Currently `HTMLpre` can only handle `onScroll`. I think this is a desired behaviour.
Still I'd like to create a `HTMLEditablePre`. I ended up with this non working code:

~~~
import Halogen.HTML.Core as HC
import Halogen.HTML.Events as HE
import Halogen.HTML.Elements as HEL
import Halogen.HTML.Properties as HP
import DOM.HTML.Indexed as I
import Web.UIEvent.KeyboardEvent (KeyboardEvent)

type HTMLEditablePre = I.Interactive (onKeyPress :: KeyboardEvent)
editablePre :: forall p i. HEL.Node HTMLEditablePre p i
editablePre = HEL.element (HC.ElemName "pre")

...
editablePre [ HP.attr (H.AttrName "contentEditable") "true"
                    , HP.attr (H.AttrName "tabindex") "0"
                    , HE.onKeyPress (HE.input q)
                    ]
       [ HH.text "some text" ]
~~~

It fails with `unknown value HE.onKeyPress`. 

So could you tell me if I'm doing something silly because there is another more direct way to achieve this. Or if I'm on the right track, I might enhance the documentation about creating specific elements with slightly different behaviour.

Sorry if I'm not using the correct medium to ask this question but  I don't really know where else to ask.

**Comment by garyb** [comment]
What you've got here looks great - it's just that Halogen doesn't provide an `onKeyPress` handler since it's deprecated/non-standard. `onKeyUp` or `onKeyDown` will work, and I think the `onInput` variants will for all modern browsers too.

**Comment by yogsototh** [comment]
Ah thanks a lot for the pointer. I think I can make that work then. 

I think I can close that issue, but if I make it works and you think this is of interest, I can provide a documentation PR with an example. But I'm not sure the place for such a specific doc should be here. Perhaps I should simply write a blog post somewhere about it. Also, I'll certainly add a comment with the working version for anyone looking for this.

Thanks again! Halogen really rocks!
