### ISSUE TITLE
Preserving state for dev and testing

### ISSUE THREAD

**Issue by chrisdone** [slamdata/purescript-halogen#569]
Hi all,

With the [react-flux](http://hackage.haskell.org/package/react-flux) GHCJS package, one nice thing I was able to do was after every Query input was evaluated in the evaluator, it would write the current state to localStorage as JSON. When I refreshed the page, I'd be back where I was, because I'd restore the global state back. If I wanted to link another dev to what I was seeing, I could send them a JSON string to set as their localStorage and then hit refresh and they'd see what I see.

I'd like to have the same thing in Halogen. It looks like I could put an `Initialize` constructor in my `Query` type and update to `master` halogen (have to fiddle with psc-package) to get the `initializer` field for a component. In the evaluator, I could just restore the state from localStorage. I'd do this for all components that I want persistence on for dev purposes.

Have other people taken similar approaches?

**Comment by garyb** [comment]
The current published version does support components with initializers too, there are `lifecycleComponent` / `lifecycleParentComponent` constructors that add `initializer` and `finalizer` fields to the component record, where you (optionally) specify the query they should raise. They work a little differently to the version in `master`, but should still let you do what you describe here.

I've not tried anything similar out, but it sounds super useful. Up until fairly recently this wouldn't have worked for our use case, as some of our components were wrappers for "3rd party" (JS) components where we didn't have access to the state in a way that would let us restore it exactly.

**Comment by chrisdone** [comment]
Thanks, I'll report back in this issue if I have something working nicely using `initializer`. :ok_hand:

**Comment by rnons** [comment]
I made an example just now, only works with the master version though. https://github.com/nonbili/purescript-halogen-hmr-example
