### ISSUE TITLE
Make EventHandler a monad transformer

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#57]
By using `WriterT`. This will avoid the need for `pure <<< pure` etc.

**Comment by jdegoes** [comment]
:+1:

**Comment by puffnfresh** [comment]
Why `WriterT` over `Free`?

**Comment by paf31** [comment]
It doesn't matter I guess, I think it would be internal to the `Handler` module. The current implementation is pretty close to `Writer` so I figured it would be a minimal change.

**Comment by paf31** [comment]
Just this and #59 for 0.4 now, which I hope to wrap up this weekend.
