### ISSUE TITLE
How can you kill a forked computation?

### ISSUE THREAD

**Issue by cprussin** [slamdata/purescript-halogen#572]
I see that in the master branch, the `HalogenM.fork` function now returns a `ForkId` and a `HalogenM.kill` function as been added.  Is it possible to kill a forked computation in the current release (4.0.0), or must I wait until the next release?  If the latter, any idea when the next release will be available?

**Comment by kRITZCREEK** [comment]
If you look at the signature of the `fork` function in 4.0.0:

`fork :: forall s f g p o m a. MonadAff m => HalogenM s f g p o m a -> HalogenM s f g p o m (Error -> m Unit)`, you can see that it returns the canceller, so the usage is something like:


```purescript
eval = case _ of
  Init -> do
    canceller <- fork myComputation
    liftAff (delay (Milliseconds 1000))
    canceller (Effect.Exception.error "something")
```

https://github.com/slamdata/purescript-halogen/blob/v4.0.0/src/Halogen/Query/HalogenM.purs#L135

**Comment by cprussin** [comment]
Ah great, that helps, thanks!
