### ISSUE TITLE
Error: Examples: Pulp: Module Halogen has been defined multiple times

### ISSUE THREAD

**Issue by Arsca** [slamdata/purescript-halogen#573]
Hi,

I'm getting this error when trying to run any of the examples. 

**ENVIRONMENT**:
OS: macOS 10.13.6 / darwin 17.7.0
PULP: version 11.0.0
PURS: version 0.11.7 using /usr/local/bin/purs
NODEJS: v8.4.0

**STEPS TO REPRODUCE**
1) ➜  ~/workspace/PureScript/purescript-halogen-master  npm install
audited 2873 packages in 4.837s
found 0 vulnerabilities

2) ➜  ~/workspace/PureScript/purescript-halogen-master npm run example-basic

**EXPECTED BEHAVIOR**
Succesful build.

**ACTUAL BEHAVIOR**
> ➜  ~/workspace/PureScript/purescript-halogen-master/ npm run example-basic

> @ example-basic /Users/arsca/workspace/PureScript/purescript-halogen-master
> pulp build --main Example.Basic.Main --include examples/basic/src --to examples/basic/dist/example.js
Building project in /Users/arsca/workspace/PureScript/purescript-halogen-master
[1/20 DuplicateModule] bower_components/purescript-halogen/src/Halogen.purs:1:1
      v
   1  -- | The base Halogen module re-exports most of the library's useful types and
   2  -- | combinators, aside from the `HTML`-building functionality - the HTML
   3  -- | modules export a large number of commonly named values that are likely to
      ...
  39  -- | A specialised version of the `Halogen.HTML.Properties.IProp` type where
  40  -- | `i` is `* -> *` kinded to match the kind of a component query algebra.
  41  type IProp r i = P.IProp r (i Unit)
                                       ^
  **Module Halogen has been defined multiple times**
 Module Halogen.VDom.Driver has been defined multiple times
...
... (cut part)
...
           Src   Lib   All
Warnings   0     0     0
Errors     20    0     20
 ERROR: Subcommand terminated with exit code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ example-basic: `pulp build --main Example.Basic.Main --include examples/basic/src --to examples/basic/dist/example.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ example-basic script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
➜  ~/workspace/PureScript/purescript-halogen-master

**Comment by garyb** [comment]
It looks like you ran `bower install purescript-halogen` within the project itself perhaps, `bower_components/purescript-halogen` should not exist. Try emptying `bower_components`, run `bower install` and try again.
