### ISSUE TITLE
Question: how do you integrate events from JS into Halogen?

### ISSUE THREAD

**Issue by chrisdone** [slamdata/purescript-halogen#575]
For example:

* Writing a CodeMirror component: how do you go from an FFI call to triggering an event in Halogen?
* Using the EventSource (JS) library to receive events from the server: how do you handle that event in Halogen?

E.g. if my `Query a` type has a `CodeMirrorValueChanged String a` or `ServerEvent Json a` constructor - what's the proper way to inject that into your component?

**Comment by chrisdone** [comment]
I found the answer! For posterity, here's the link:

https://gist.github.com/dgendill/c296a8b3a37dea2c99fc2f29e8bc3941#how-do-i-asynchronously-update-the-ui-eg-showupdate-a-loading-bar

What a great gist.  This also answers another question of mine, which is:

https://gist.github.com/dgendill/c296a8b3a37dea2c99fc2f29e8bc3941#how-do-i-query-the-rendered-markup-of-my-component

:muscle:

**Comment by garyb** [comment]
That's a nice gist :+1:

**Comment by mediocrehacker** [comment]
Indeed, that is a nice gist.
