### ISSUE TITLE
Any way to use jquery plugins

### ISSUE THREAD

**Issue by alexjg** [slamdata/purescript-halogen#577]
I'm using Semantic UI in a Halogen project and there are a parts of the framework (the semantic UI framework that is) that require using jquery plugins. For example, the "dimmer" module requires a  `$(<selector>).dimmer("show")` call.

I know that Halogen is using a virtual DOM so there's no way to directly access the actual DOM nodes in order to achieve this in `eval`. Is there another way that I'm missing?

**Comment by justinwoo** [comment]
You should be looking at usages of `import Halogen.HTML.Properties as HP` like in the ACE editor example: https://github.com/slamdata/purescript-halogen/blob/23225596473898744a6cb84fde2791aa6fe8a66a/examples/ace/src/AceComponent.purs#L49

e.g. I use `ref` to get element references for audio https://github.com/justinwoo/purescript-web-audio-player-demo/blob/6f6b692ea83e840d39b32f2bd7db4a7965f44ca7/src/Main.purs#L133

**Comment by alexjg** [comment]
Ah nice, yeah that should do the trick, thanks.
