### ISSUE TITLE
Should EventSources be fixed to Aff/Effect

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-halogen#580]
Right now, EventSources are in `m` and must unify with the component's `m`. This means whenever you want to use an EventSource, you will likely incur a `MonadAff/MonadEffect` constraint, since they are usually bindings to low-level things. If EventSource was fixed to `Aff/Effect`, I think you could avoid that, since all component's must eventually be run in `Aff` anyway. It's definitely a trade-off, but maybe something to think about.

**Comment by garyb** [comment]
What's the advantage of that, other than not needing an `m` type parameter?

**Comment by natefaubion** [comment]
That you can lift low level event sources without incurring `MonadEffect/MonadAff` on `m`. `m` can continue to be "pure".

**Comment by garyb** [comment]
Ah I see, yeah. Do you think that happens often enough where `m` is not incurring an `Eff` elsewhere in the component anyway?

**Comment by natefaubion** [comment]
I think so. If you treat event sources as a sort of FFI like thing, then it means you can keep relegate DOM-twiddling to those, and keep app-logic clean. Right now it forces you to conflate the two.

**Comment by garyb** [comment]
Closing this since they're getting replaced with `Event` in v6... which is essentially fixing them to `Effect` as suggested too :smile:.
