### ISSUE TITLE
how to define eval function with empty query type?

### ISSUE THREAD

**Issue by wangbinyq** [slamdata/purescript-halogen#582]
I have query type

```purescript
data Query a
```
Because `Query` has no constructors, how can i define `eval` function ?

**Comment by cryogenian** [comment]
Use `Const Void` and then your eval would be `absurd <<< un Const`

**Comment by wangbinyq** [comment]
@cryogenian It works, thanks.
@natefaubion What is the type for stateless component?

**Comment by natefaubion** [comment]
`foo :: forall p i. Whatever -> HTML p i`

**Comment by thomashoneyman** [comment]
`purescript-ocelot` has plenty of examples of these 'stateless components':

https://github.com/citizennet/purescript-ocelot/tree/master/src/Blocks

They're informally called "blocks" there, but they're simple HTML functions as Nate described. Compare to the components in the same repository:

https://github.com/citizennet/purescript-ocelot/tree/master/src/Components

**Comment by wangbinyq** [comment]
thanks
