### ISSUE TITLE
Getting "An infinite type was inferred for an expression" for query'/request

### ISSUE THREAD

**Issue by mnn** [slamdata/purescript-halogen#583]
In my component:

    data Query a = SetImageUrl Int String a

Main (app) component:

      eval :: Query ~> H.ParentDSL State Query ChildQuery ChildSlot Void m
      eval = case _ of
        HandleItemChange groupId (LIS.ActiveChanged selected) next -> do
          let apReq = AP.SetImageUrl groupId (imageUrl selected)
          _ <- H.query' CP.cp2 AvatarPictureSlot (H.request apReq)
          pure next

Compiler says:

    [1/1 InfiniteType] src/App.purs:85:57
    
      85        _ <- H.query' CP.cp2 AvatarPictureSlot (H.request apReq)
                                                                  ^^^^^
      
      An infinite type was inferred for an expression:
      
        t0 -> t0
      
      while trying to match type t0 -> t0
        with type t0
      while checking that expression apReq
        has type (t0 -> t0) -> t1 t0
      in value declaration app
      
      where t0 is an unknown type
            t1 is an unknown type

I think slots and child paths are alright, because `render` function compiles and works correctly.

**How to fix this error?** I checked several times against guide, but I simply don't see any difference and the compiler message is super unhelpful (for me). Any advice would be appreciated.

**Comment by garyb** [comment]
I'm not really sure what is going on there - what happens if you put a `?hole` in for `apReq`? If that doesn't explode (there's a chance it's lying about where the error really is), what happens with `H.request (?f apReq)`?

**Comment by mnn** [comment]
```purescript
[1/1 HoleInferredType] src/App.purs:85:57

  85        _ <- H.query' CP.cp2 AvatarPictureSlot (H.request ?apReq) -- (H.request apReq)
                                                              ^^^^^^
  
  Hole 'apReq' has the inferred type
  
    (t0 -> t0) -> Query t0
  
  You could substitute the hole with one of these values:
  
    Unsafe.Coerce.unsafeCoerce  :: forall a b. a -> b
  
  in the following context:
  
    apReq :: t1 -> Query t1
    eval :: NaturalTransformation Query (ParentDSL State Query ChildQuery ChildSlot Void m2)
    groupId :: Int
    imageUrl :: { id :: Int
                , label :: String
                , name :: String
                }
                -> String
    initialState :: { selectedItemInGroup :: Array
                                               { id :: Int
                                               , label :: String
                                               , name :: String
                                               }
                    }
  
  in value declaration app
  
  where m2 is a rigid type variable
          bound at line 37, column 3 - line 86, column 12
        a3 is a rigid type variable
          bound at line 81, column 10 - line 86, column 12
        t1 is an unknown type
        t0 is an unknown type
```

```purescript
[1/1 HoleInferredType] src/App.purs:85:47

  85        _ <- H.query' CP.cp2 AvatarPictureSlot (?f apReq) -- (H.request apReq)
                                                    ^^
  
  Hole 'f' has the inferred type
  
    (t0 -> Query t0) -> Query t1
  
  You could substitute the hole with one of these values:
  
    Halogen.Query.action        :: forall f. (Unit -> f Unit) -> f Unit
    Unsafe.Coerce.unsafeCoerce  :: forall a b. a -> b
  
  in the following context:
  
    apReq :: t0 -> Query t0
    eval :: NaturalTransformation Query (ParentDSL State Query ChildQuery ChildSlot Void m2)
    groupId :: Int
    imageUrl :: { id :: Int
                , label :: String
                , name :: String
                }
                -> String
    initialState :: { selectedItemInGroup :: Array
                                               { id :: Int
                                               , label :: String
                                               , name :: String
                                               }
                    }
  
  in value declaration app
  
  where m2 is a rigid type variable
          bound at line 37, column 3 - line 86, column 12
        a3 is a rigid type variable
          bound at line 81, column 10 - line 86, column 12
        t0 is an unknown type
        t1 is an unknown type
```

It is happening on this line (when I comment it out, program compiles and works). It is probably something trivial, I don't know much about PureScript nor Halogen.

**Comment by garyb** [comment]
Ok, try using `H.action apReq` rather than `H.request`: note that it actually suggests that as an option in the `?f apReq` case 🙂.

 I didn't notice it earlier, but that's definitely the problem here. `H.request` is for cases when you want to retrieve some information in response to a query, and in that situation the query constructor would also take a slightly differrent form (`(SomeResult -> a)` rather than `a` as the last argument).

See [these sections in the guide](https://github.com/slamdata/purescript-halogen/blob/v4.0.0/docs/2%20-%20Defining%20a%20component.md#evaluating-actions) about actions vs requests.

**Comment by mnn** [comment]
Thank you very much, @garyb :slightly_smiling_face:. I knew it will be something basic. Whole time I was being focused on https://github.com/slamdata/purescript-halogen/blob/v4.0.0/docs/5%20-%20Parent%20and%20child%20components.md#querying-1 where only request is shown, should have went back and check the previous chapters.

**Comment by garyb** [comment]
No problem! I'll make a note that it's something we could remind people of at that point in the guide.
