### ISSUE TITLE
What's left for v5 release?

### ISSUE THREAD

**Issue by safareli** [slamdata/purescript-halogen#584]
Once #576 (Partial query evaluation) is merged is there anything left until v5 can be released (besides documentation)?

**Comment by garyb** [comment]
Yeah, that's all I have planned - I'm going to make a pre-release once #576 is done.

**Comment by AlexaDeWit** [comment]
I don't suppose a move to profunctor lenses 5.x is also possible? XD

**Comment by AlexaDeWit** [comment]
Great! I'd like to be able to migrate to Argonaut 5 with halogen 5 that's
all. The transient deps currently would prevent that.

**Comment by AlexaDeWit** [comment]
@bradediger great to hear! Thanks. Here's hoping I can migrate into 5.x argonaut alongside 5.x halogen then!

**Comment by thomashoneyman** [comment]
@AlexaDeWit if you aren't using `-traversals`, then you can just install `-core` and `-codecs` and use them with Halogen v4 right now, [as seen here](https://github.com/thomashoneyman/purescript-halogen-realworld/blob/master/bower.json).

**Comment by AlexaDeWit** [comment]
I know ;)
