### ISSUE TITLE
preventDefault

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#59]
Sometimes it's necessary to prevent event or stop its propagation without returning any message. 
Currently this is not supported by halogen.

**Comment by paf31** [comment]
I think it is. 

`EventHandler (Aff eff input)` is inhabited by `preventDefault $> x`. All we need is for `x` to not call the callback, but I'm not sure if that's possible. @jdegoes ?

**Comment by jdegoes** [comment]
`Aff eff input` is a computation which must produce an `input` or end in error, there are no other options. It's exactly like `Eff eff input` except asynchronous. However, one use `forkAff` if one wishes to fork the computation, and then const-map it to whatever. That should be enough to build this, right? Also Handler is becoming a monad transformer, isn't it?

**Comment by paf31** [comment]
I think @cryogenian wants to not produce any input to the state machine at all. I think `handler'` will let you do that. The underlying representation of a handler certainly allows it.

**Comment by jdegoes** [comment]
Perhaps a combinator, then, which operates on `EventHandler a`, goes to `EventHandler b` for all `b`, by mapping the `Maybe i` to `Nothing`?

**Comment by paf31** [comment]
It's not `EventHandler`, it's the attribute itself:

https://github.com/slamdata/purescript-halogen/blob/master/src/Halogen/HTML/Attributes.purs#L147

But yes, a combinator would probably do the trick. Rolling the Maybe into the new `EventHandlerT` would probably be a good thing.

**Comment by paf31** [comment]
@cryogenian Now you can use `cancel` if you don't want to generate any input event.

@puffnfresh You mentioned using `Free` which I think was a good idea, but I stuck with `WriterT` because I now need to turn this into `EventHandlerT` (transformer) and we don't have a free monad transformer yet in `purescript-free`.

**Comment by puffnfresh** [comment]
@paf31 that's fine.

We were not able to write a stack-safe `FreeT` in Scala due to the JVM. I wonder if JS will have the same problem...

**Comment by paf31** [comment]
Can't you play the same trick with `Gosub`? Interpreting the monad _should_ (and I'm guessing obviously) be possible safely with `tailrec`.
