### ISSUE TITLE
Update docs for 0.4

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#60]

**Comment by paf31** [comment]
I've changed the format of the docs to try to explain why we made the choices we did. Hopefully it's easier to understand what's going on now, but please let me know what you think. @jdegoes ?

**Comment by garyb** [comment]
I'm a big fan of the new docs. :metal:

**Comment by natefaubion** [comment]
Agreed. I thought it was a great intro.

**Comment by jdegoes** [comment]
:sunglasses: :+1:
