### ISSUE TITLE
Calling `docs` on `v5.0.0-rc.4` fails

### ISSUE THREAD

**Issue by JordanMartinez** [slamdata/purescript-halogen#601]
As reported in JordanMartinez/learn-halogen#5, running `spago docs` on the `v5.0.0-rc.4` will fail with this error:
```
Generating documentation for the project. This might take a while..
Error found:
in module Halogen.Query.EventSource
at .spago/halogen/v5.0.0-rc.4/src/Halogen/Query/EventSource.purs:32:8 - 32:66 (line 32, column 8 - line 32, column 66)

  Type class instances for type synonyms are disallowed.

in type class instance
                                                         
  Data.Newtype.Newtype (EventSource m a)                 
                       (m                                
                          { finalizer :: Finalizer m     
                          , producer :: Producer a m Unit
                          }                              
                       )                                 
                                                         

See https://github.com/purescript/documentation/blob/master/errors/TypeSynonymInstance.md for more information,
or to contribute content related to this error.


spago: Docs generation failed.
```
I'm assuming its because there's no `Monad` constraint in the instance derivation?

I tried reproducing the bug without using Spago (in case I was referring to an outdated dependency in my local package set). I followed these steps:
```
cd purescript-halogen
rm -rf output/ bower_components/
git checkout origin/master
bower install
pulp docs
```
And that failed with this error:
```
purs docs: error in --docgen option:
  Can't mix module names and module name/file path pairs in the same invocation.
* ERROR: Subcommand terminated with exit code 1
```

**Comment by garyb** [comment]
Why would there need to be a `Monad` constraint for the `Newtype` instance? It looks like a bug in `purs docs` to me.

The second one looks like a bug in `pulp`.

**Comment by JordanMartinez** [comment]
> Why would there need to be a Monad constraint for the Newtype instance?

I thought it might be a bug in `purs`, but in case it wasn't, that would be my next guess for fixing it.

**Comment by hdgarrood** [comment]
@JordanMartinez to reproduce this without using spago, try running `purs docs --format html 'src/**/*.purs' 'bower_components/purescript-*/src/**/*.purs` instead of `pulp docs`.

**Comment by JordanMartinez** [comment]
@hdgarrood Just tried that command and it worked without any issue.

**Comment by JordanMartinez** [comment]
Since that above command worked and since I did find a way to fix the original problem [in my comment here](https://github.com/purescript/purescript/issues/3624#issuecomment-490085608), I'm going to close this issue.
