### ISSUE TITLE
Merge `request` and `tell` with `query`?

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#611]
So instead of doing:

``` purescript
H.query _child "id" (H.request GetInfo)
void $ H.query _child "id" (H.action DoWhatever)
```

There'd be:

``` purescript
H.request _child "id" GetInfo
H.tell _child "id" DoWhatever
```

Aside from it being a bit simpler visually, and not having to explain that `request` is just `_ $ identity` / `tell` is just `_ $ unit`, it also removes the need to `void` all the tell-style requests, as they return `Maybe Unit` so can't be `discard`ed.

I guess the same would go for `queryAll` - have a `requestAll` with a result, `tellAll` with `Unit`.

Thoughts?

**Comment by thomashoneyman** [comment]
This is _much_ nicer, in my opinion.

 On the one hand you lose the concept that "both are just queries" demonstrated in the function names; on the other, you lose quite a bit of annoying `void` or `_ <-` and an extra function to remember (`query` + `request`, `query` + `action`).

I support this change.

**Comment by garyb** [comment]
Yeah, that's why I clung onto it for so long I think, the "it's all queries" viewpoint.

I guess you also kinda lose the ability to determine whether your `tell`s succeed, but I don't know how valuable that is - I've never once needed it personally.

I suppose there's no reason to get rid of the `query` functions either though, they just don't need to be promoted as the usual way of doing things.

**Comment by thomashoneyman** [comment]
> I guess you also kinda lose the ability to determine whether your tells succeed, but I don't know how valuable that is - I've never once needed it personally

Same -- never once needed it. Doesn't mean it should be dropped altogether, but it's not really worthy emphasizing this capability.

> I suppose there's no reason to get rid of the query functions either though, they just don't need to be promoted as the usual way of doing things.

Yea, good point: `query` could stick around with a documentation comment demonstrating its use, ie.

```purescript
-- | Send a query ... returns `Maybe` with the result, or `Nothing` if failed. Can be used 
-- | as an alternative to `H.tell` when you need to know whether a `tell` succeeded, or
-- | as an alternative to `H.request` when you want to supply a function other than `identity`
-- |
-- | ```
-- | request <- H.query _child "id" (GetInfo identity)
-- | tell <- H.query _child "id" (DoWhatever unit)
-- | case request, tell of
-- |   Nothing, Nothing -> ... -- request and tell failed
-- |   Just _, Just unit -> ... request and tell succeeded
-- | ```
query :: ...
query = ...
```

**Comment by garyb** [comment]
Yeah, exactly. The new `request` and `tell` would be implemented in terms of `query` anyway! :smile:

**Comment by JordanMartinez** [comment]
I like this change, too. 

I think Thomas' above documentation example should also include the point you mentioned to me, Gary, namely, that a query can fail if the child component isn't rendered when the query is made. 

On another hand, I sometimes wish `query` returned `Variant ( notRendered :: NotRendered, value :: a | otherCustomErrorRows )` where `NotRendered` indicates the above error with a type, `value` is the un-Maybed value, and `otherCustomErrorRows` provide the end-user ways to specify other error situations. However, I'm not sure how much of this is useful in real-world projects...

**Comment by safareli** [comment]
I like it too, as long as query stays there (so if you want to observe failure of query you can).

but wouldn't you still need to use `H.action` for emitting messages from HTML? if yes, then we would still have to explain what `H.action` is

**Comment by garyb** [comment]
`H.action` isn't used there in v5+ 🙂

**Comment by safareli** [comment]
Great!
