### ISSUE TITLE
Add `onFileUpload` event handler that produces an `Array File` on change

### ISSUE THREAD

**Issue by googleson78** [slamdata/purescript-halogen#612]
Hi! I would like to have an `input` from which to upload files.

What is the expected/idiomatic/etc way to get the contents of the file as a `String`. The only way I can see is to attach a ref to the `input`, then refer to the ref, and then go from there. (`HTMLElement -> HTMLInputElement -> Files -> File -> Blob -> FileReader -> result -> readString`, which seems a bit absurd to me, but that's not the point here)

Is there some way to refer to the element (or even better yet - straight up get the `FileList`) which caused the event directly, instead of having to go through a ref? This introduces the possibility of me referring to a different ref, when more and more of these things are added. (it also feels clunky to me).

Sorry if I'm missing something fundamental or a design choice, I'm rather new to html/js! (or if this is entirely the wrong place to ask!)

**Comment by garyb** [comment]
You can add an event handler to the change event, and then get the reference to the element from the event. The ref method is also fine, but shouldn't be necessary.

The process for getting the file contents is absurd, but that's the DOM API for you 🤷‍♂.

``` purescript
import Prelude

import Data.Foldable (traverse_, for_)
import Data.Maybe (Maybe(..))
import Effect.Aff.Class (class MonadAff)
import Halogen as H
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.HTML.Properties as HP
import Web.Event.Event as Event
import Web.File.File as File
import Web.File.FileList as FileList
import Web.File.FileReader.Aff as FileReaderAff
import Web.HTML.HTMLInputElement (HTMLInputElement)
import Web.HTML.HTMLInputElement as HTMLInputElement

data Action = FileChosen Event.Event

renderFileInput =
  HH.input
    [ HP.type_ HP.InputFile
    , HE.onChange (Just <<< FileChosen)
    ]

handleAction = case _ of
  FileChosen ev → do
    traverse_ handleFileUpload (HTMLInputElement.fromEventTarget =<< Event.target ev)

handleFileUpload input = do
  H.liftEffect (HTMLInputElement.files input) >>= traverse_ \files →
    for_ (FileList.item 0 files) \file → do
      content ← H.liftAff $ FileReaderAff.readAsText (File.toBlob file)
      ?doSomething content
```

Re: more things added. You can always separate things out into smaller components if a larger one is becoming unwieldy. 🙂

**Comment by googleson78** [comment]
Thanks! (your answers all over the internet are very appreciated by the way!)

Is there the possibility of adding something like `onFileUpload`, that gives you direct access to the file (as a buffer/blob/etc?), without having to be in `Eff/Aff`, or is this an inherently IO thing that you need to do? I was under the impression that it is your interpreter (your browsers) job to load the file and provide you with a reference to it, that you can read without causing any visible (to you) effects.

**Comment by garyb** [comment]
You're welcome!

I gave that some thought after seeing this question, as yeah, the current process is pretty awful. 

Adding an `onFileUpload` that produces an `Array File` does indeed seem sensible - when using the `purescript-web-html` provided stuff, it is inherently effectful to read the files from an input - but that's true for reading the `input` or `checked` the way it does for `onValueInput`, `onChecked`, etc,  too, so it wouldn't really be any different than those cases. 

The reason it's effectful to do these things is the value may differ every time it is read from the element - but that's a concern while doesn't really apply here, given the use case. In fact we're relying on the fact it'll be different! 🙂 

I'll hijack this issue to make it an enhancement request to add the handler.

**Comment by googleson78** [comment]
:+1: I could also get around to doing this, but probably not before the end of this month.

**Comment by thebrodmann** [comment]
How can convert `Foreign` to `Array File`?

**Comment by googleson78** [comment]
Not sure if I'm doing something wrong, but I can't find a `readFile` (looked in `purescript-foreign` and in `purescript-web-file`) to give to `addForeignPropHandler`.

Does this mean that such a procedure should be added to one of those first?

**Comment by thebrodmann** [comment]
I think so. There is an open issue on https://github.com/purescript-web/purescript-web-file/issues/7.
