### ISSUE TITLE
Blocking UI with form result type of component

### ISSUE THREAD

**Issue by vanceism7** [slamdata/purescript-halogen#615]
So back when I used to write some programs using winforms in c#, it was pretty common to use blocking modal dialog boxes to grab quick responses from user, stuff like
![image](https://user-images.githubusercontent.com/2016375/63726865-5eaf6e80-c813-11e9-869a-288d2d872007.png)
These modals would popup and grab some type of response from the user (usually a `boolean` but it could be a `string` or something more as well), and return it back to the calling function.

Today I've come across the need to do this in halogen, but halogen doesn't really work like that as far as I can tell. I was able to find something similar to that functionality using `confirm`: https://pursuit.purescript.org/packages/purescript-web-html/2.2.0/docs/Web.HTML.Window#v:confirm

The deal breaker here is that `confirm` doesn't make for the best UX. Is there a way to create some type of blocking component that returns data within eval queries, similar to `confirm`? I don't know if this is fundamentally against how halogen works but it would be useful to have if there was a way to get something like this working. More of a question of curiosity than anything else

Thanks!

**Comment by garyb** [comment]
If you're not worried about it being "actually" modal, and it's more about keeping the control flow where you get the response right at the point where you launch it, then you can do this with an `AVar`. You construct the `AVar` at the point you want to show the dialog, show the dialog and pass it through somehow, then `take` from the `AVar` right there. You then have the dialog `put` to the `AVar` when it closes, and the `eval` will resume at the `take`.

**Comment by garyb** [comment]
That would work, sure. I was thinking perhaps the parent/root/wherever component would have a `dialog :: Maybe Dialog` part of its state, and then an ADT like:

``` purescript
data Dialog
  = Confirm String (AVar Boolean) 
  | ... etc.
```

The component raising the dialog could then set the `dialog` property to `Just (Confirm msg responseAVar)`, or `raise` it to a higher level where the dialog should be rendered, and then the `Dialog` value could be used to conditionally render a dialog with the appropriate content.

We do something similar to that in the current iteration of SlamData, where we have a top-level component with a `Maybe Dialog`, and it handles showing the dialog and such, with the `Dialog` values arising from the various screens in the app. We just `raise` them and bubble them manually through however layers in necessary just now, but in a previous iteration we had a globally accessible `Bus` that we would use to send `Dialog`s to the top level (there are fewer layers in the current product than there used to be, so bubbling the `raise`s is no big deal, previously there was potentially unbounded depth, as there was a recursive element to the UI).
