### ISSUE TITLE
Feedback on v5 changes 

### ISSUE THREAD

**Issue by vanceism7** [slamdata/purescript-halogen#619]
Hey guys, just wanted to give feedback on one specific change in halogen 5 
(Not sure if there's a better place to do this, sorry if an issue isn't the most appropriate)

> The type variables have been renamed to full words in the component / query / etc. type signatures. Maybe this will help, maybe not - feedback is welcome and appreciated!

This change has been immensely helpful, especially in terms of migrating from v4. The api seems like its become a lot easier to use as well. Thanks for all your hard work on this!

**Comment by garyb** [comment]
Glad to hear it, thanks!
