### ISSUE TITLE
Android renderer for Halogen?

### ISSUE THREAD

**Issue by csicar** [slamdata/purescript-halogen#626]
I'am currently working on a native Android backend through the kotlin backend and was wondering if halogen could be used for creating the UIs:

Is there interest on supporting alternative GUI platforms?

Would it be feasible to create an alternative renderer?

**Comment by safareli** [comment]
v4 and v5 of halogen are parameterized with type representing UI, HTML in default case, and it's technically possible to define other renderer type and use it with that versions of halogen. But recently that type parameter was removed see https://github.com/slamdata/purescript-halogen/pull/616 and discussion on https://github.com/slamdata/purescript-halogen/pull/613

**Comment by csicar** [comment]
> A completely separate fork is what would have to happen if we make this change, yeah. Realistically, if someone is able to dig into the driver implementation enough to be able to change the surface then one extra type variable is barely going to be a dent cognitively. 

(from #613)

I guess writing a new library from scratch is the option to go then. Thanks!
