### ISSUE TITLE
How to use this with MathJax?

### ISSUE THREAD

**Issue by CarstenKoenig** [slamdata/purescript-halogen#628]
First this is probably not really an issue but a question or even me being stupid.
If this is OT then please close this and accept my apologies (A hint how I could do this would be great anyway).

---

I have a hard time using Halogen with MathJax - basically because I end up with multiple rendered formulas after some time.

My best guess is that the somehow the vdom-diff will insert the *source*-text (that MathJax will remove after `typeset()`) again and so if I rerun this function again it will add another formula.

Sadly just dropping all `.MathJax` elements (this CSS-class is attached in the output generated by MathJax) before `MathJax.typesetClear()` (to reset it's cache) and `MathJax.typeset()` won't work either as oviously not all DOM nodes are getting reinserted by the VDOM here.

Is there some kind of hook I can access, when the VDOM (re-)inserts a node? Or is it possible to tell Halogen to drop all other children when reinserting the node?

Is there another way I just don't see?

---

BTW: I had similar issues with Fontawesome where I just "copied" the SVG and used this directly - sadly this is not really possible for dynamic math formulas.

Thank you for your time

**Comment by rnons** [comment]
Have you tried [Halogen.HTML.Elements.Keyed](https://pursuit.purescript.org/packages/purescript-halogen/4.0.0/docs/Halogen.HTML.Elements.Keyed)? By assigning a key to an Element, VDOM will not unmount and mount the element again.

**Comment by CarstenKoenig** [comment]
I did not try `Keyed` but I tried `withKeys` and that did nothing

I'm willing to try though (will take a while)

---

BTW: I found a very *hacky* workaround: I render all the formulas into a `<span class="math">` and then use this foreign function to look for duplicates and remove them for everything in `handleAction`:

```js
"use strict";

exports.typeSetPage = function () {
    function cleanUp() {
        var existingNodes = document.querySelectorAll('.math');
        existingNodes.forEach(function (mathNode) {
            var mathJaxNodes = mathNode.querySelectorAll('.MathJax');
            if (mathJaxNodes.length > 0 && mathNode.innerText !== "") {
                // there is a formula text here - so MathJax will replace it
                // get rid of the already rendered children
                mathJaxNodes.forEach(function (n) { n.remove(); });
            }
        });
    }

    try {
        cleanUp();
        MathJax.typesetClear();
        MathJax.typeset();
    } catch (e) { }
}
```

**Comment by CarstenKoenig** [comment]
hmm... maybe I did not understand `withKeys` correctly - can it only be used in a `keyed` context (as a child of an `keyed` element)?

**Comment by CarstenKoenig** [comment]
I tried a local `HK.div_` and it does not change the effect - basically every action will produce a new formula - maybe if the complete page is keyed but I guess I'll have to write a simple demo for that

**Comment by rnons** [comment]
One approach is clean up mathjax before every re-render, similar to what you did.

Another approach is set the formula text imperatively, outside of the halogen render cycle. First use `H.getHTMLElementRef` to get your formula span. Then use [setInnerText](https://pursuit.purescript.org/packages/purescript-nonbili-dom/0.2.0/docs/Nonbili.DOM#v:setInnerText) to update formula text, then `MathJax.typeset`. Notice you need `MathJax.typesetClear()` as well https://github.com/mathjax/MathJax/issues/2191

A live demo is at https://rnons.github.io/halogen-mathjax-example/#Hello

**Comment by CarstenKoenig** [comment]
that might be a better approach thanks (should be able to put this into a component easily too)

btw: I wish tools like MathJax could keep better track of their replaced elements
