### ISSUE TITLE
data attributes 

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#63]
there is no way to set them. 
```purescript
attr (attributeName "data-foo") "bar" 
```
doesn't work

**Comment by garyb** [comment]
I'm not sure if it's still the case, but to use `data-*` attributes in `virtual-dom` requires the use of the [`data-set` library](https://github.com/npm-dom/data-set), similar to `dom-delegator` for `ev-*` attributes. It doesn't actually set the data on the element, but provides an abstraction for them so you can store non-string values also.

**Comment by cryogenian** [comment]
I've used `{dataset: {foo: "bar"}}` in `purescript-signal` approach. This works for `styles` also

**Comment by paf31** [comment]
So we can just add a `dataset` attribute of type `StrMap` then?

**Comment by cryogenian** [comment]
Yes, that will work

**Comment by paf31** [comment]
For now, we can get around this by using individual properties, right? Is it just the dash in the name which is problematic, I wonder?

**Comment by cryogenian** [comment]
Such properties don't set, probably it's because virtual-dom mechanic, but not sure.

**Comment by paf31** [comment]
More info here:

https://github.com/Matt-Esch/virtual-dom/blob/7cd99a160f8d7c9953e71e0b26a740dae40e55fc/docs/vnode.md#custom-attributes-data-

PR incoming.
