### ISSUE TITLE
Export for type Prim.RowList.Cons conflicts with type class Prim.Row.Cons

### ISSUE THREAD

**Issue by soywod** [slamdata/purescript-halogen#630]
From a fresh install of PureScript + Halogen, I can't build the projet with `pulp build` (I took the code from the [/examples/basic](https://github.com/slamdata/purescript-halogen/tree/master/examples/basic/src) repo):
```
Error found:
in module Type.Row
at bower_components/purescript-typelevel-prelude/src/Type/Row.purs:4:5 - 4:24 (line 4, column 5 - line 4, column 24)

  Export for type Prim.RowList.Cons conflicts with type class Prim.Row.Cons
```

I tried with v4 and v5 of Halogen, same error.

`bower.json`:
```json
{
  "name": "purescript",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "output"
  ],
  "dependencies": {
    "purescript-prelude": "^4.1.1",
    "purescript-console": "^4.2.0",
    "purescript-effect": "^2.0.1"
  },
  "devDependencies": {
    "purescript-psci-support": "^4.0.0"
  }
}
```
`versions`:
```
bower 1.8.8
pulp 13.0.0
purs 0.13.4
```

**Comment by garyb** [comment]
This does happen with v4, but v5 should definitely work.

Did you `rm -rf bower_components` before changing to it? If not, I imagine you would have been asked to resolve a bunch of stuff by `bower`, as you've ended up with an old version of `purescript-typelevel-prelude` for this error to be occurring.

**Comment by soywod** [comment]
Yes, I tried first with the v5, then v4. I will try again and let you know. Strange thing, when I clone the purescript repo and build the basic, it works :(

**Comment by soywod** [comment]
I realised that the version set in the README is not up-to-date. I tried with the `v5.0.0-rc.7` of halogen and it works :)

**Comment by garyb** [comment]
Glad to hear it!
