### ISSUE TITLE
Widgets receive inputs multiple times

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#65]
In the Ace example, if you copy text, then click the Copy button, then copy text again, the text area clears, which is wrong. I think this is something to do with `init` vs `update`.

**Comment by paf31** [comment]
This is a serious bug, and I've been working on it for a while, with no success yet. I think the problem can be summed up as "the `virtual-dom` widget API is not compatible with our `Component` API". 

The issue happens because `combine` keeps the previous state of the `Component` which does not receive the input, so the argument to `update` is the latest input.

If you try to model a widget as a pure signal function from an input to a `VTree`, you run into problems, and I haven't found a satisfactory way to hack it in using the `virtual-dom` machinery yet. 

Does anyone have any ideas? Right now, the only valid thing I can think to do is to change the input type to use `Maybe`, and document the fact that the argument is the latest input or `Nothing`, forcing the developer to handle the problem manually by either not using components in this way, or by firing an additional `Nothing` input to "clear the buffer".

**Comment by jdegoes** [comment]
Could this be a reason to opt for PureScript vdom?

**Comment by paf31** [comment]
If we could find a nice way to handle widgets then yes, I think so. The problem isn't so much with `virtual-dom`, as that the two models just don't really fit. In `virtual-dom` things only get rendered when a patch is applied. I think we'd probably want to keep that property, right? 

With widgets we want to perform arbitrary changes when an input is received, but that's not what the type of `SF1` says.

**Comment by jdegoes** [comment]
Well, thinking about it more abstractly:

Vdom seems to "create the widget and copy the state". What if that's the wrong way to model the problem?

For example, what if when creating a widget, you specify an identifier, which uniquely identifies the widget. So long as that identifier appears in the virtual dom, the widget container will be moved (i.e. reattached via parentNode) to the identifier container, allowing for a certain degree of dynamism. If it cannot be found in the virtual dom, then it's destroyed via its finalizer.

This assumes, of course, that users are responsible for ensuring that they don't reuse identifiers for conceptually distinct widgets, but that seems fine to me.

I'm sure there are other "outside the box" approaches which just treat widgets as some black box (no state or anything) to which you can send (and maybe receive) messages.

**Comment by paf31** [comment]
I've thought about this a bit more, and I think the only sensible way to sort this out is to capture the effects in the type of a widget (done) and the type of a component (not done). Components are pure signal functions, which is not right in the case of a widget: every input generates effects.

So I think we should change `Component` as follows:

```purescript
newtype Component eff m p req res = Component (exists i. SF (Either i ref) (Eff eff (HTML p (m (Either i req))))
```

Widgets would need at least `eff ~ (dom :: DOM)`, but pure HTML components could be pure (`eff ~ ()`)

**Comment by paf31** [comment]
It seems even the approach above isn't enough. We would need signal functions themselves to support effects, with `Eff eff` appearing under `SF`, since we don't get to provide inputs to the widget until after it has been (effectfully) initialized.

Do we want to add (optional) signals to effects? It seems pure signal functions are just incompatible with widgets which handle their inputs effectfully.

**Comment by jdegoes** [comment]
Have lots of thoughts on this, just give me a chance to catch up to lots and lots of emails. :)

**Comment by jdegoes** [comment]
I'll get back today in the afternoon on this, right after a meeting. :)
