### ISSUE TITLE
element life cycle

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#66]
This is very close to #53. 

I think it would be nice to provide some special events for element life cycle: init, rerender, remove, via `hook` and `unhook` probably. We already have monadic effectful handlers, so if we have `onUpdate`  we can add some external behaviour for elements. 

It can be useful for using bootstrap js integration (any js library in general) that use attributes for initialization. 

This is just idea, other option is to provide similar functionality that already is in bootstrap (collapse, tooltip, other) . What do you think?

**Comment by jdegoes** [comment]
Yes, I think this is potentially just #53. That is, I think if a native Halogen component can have its own lifecycle, like a widget, then it may solve this issue and other issues.

Special events are one "non-invasive" way to do that.

**Comment by passy** [comment]
I guess this would also be required to provide animation support. The `virtual-dom` library has an example of using hooks to enable CSS animations: https://github.com/Matt-Esch/virtual-dom/blob/1dda0f6d12630996bae5703269d5cb97fae7d142/docs/css-animations.md

**Comment by paf31** [comment]
Should I close this with #53 then?

**Comment by cryogenian** [comment]
Yes, thanks
