### ISSUE TITLE
Use simple-dom appendChild

### ISSUE THREAD

**Issue by puffnfresh** [slamdata/purescript-halogen#67]
I just opened a pull request: https://github.com/aktowns/purescript-simple-dom/pull/26

Things like the ToDo app will no longer need a foreign import! :fireworks:

**Comment by puffnfresh** [comment]
We should also switch to using its `setInterval`.

**Comment by paf31** [comment]
:+1:

**Comment by paf31** [comment]
Do we want to switch from `Node` to `HTMLElement` then?

**Comment by puffnfresh** [comment]
Looks like `Node` is from purescipt-dom. Seems like simple-dom has a lot more useful things. Do we get any benefits from purescript-dom?

**Comment by paf31** [comment]
My only reservation with `simple-dom` is that a couple of things seem to be ill-typed, mostly concerning `[Node]` vs. `NodeList`. I think some of those were fixed, but not all. I can send some PRs.

In any case, it's infinitely more useful than `purescript-dom`. Let's move the code over.

**Comment by garyb** [comment]
`purescript-dom` is included transitively by `purescript-simple-dom` anyway - they share the `DOM` effect. I don't think there is much of a downside, aside from the concerns @paf31 mentioned.

**Comment by puffnfresh** [comment]
I'll try to work on this today.

**Comment by jdegoes** [comment]
As mentioned before, I'd be in favor of forking simple dom to contrib just so more people can get PRs in (in a timely fashion), and we can do cleanup work like the above w/o reservations.
