### ISSUE TITLE
PureScript implementation of vdom tailored to pure FP / Halogen

### ISSUE THREAD

**Issue by jdegoes** [slamdata/purescript-halogen#71]

**Comment by paf31** [comment]
I've been thinking about this too. It seems something like virtual-dom could both benefits from types, and also be implemented really nicely in a pure functional language.

**Comment by jdegoes** [comment]
Yeah, and with much better Halogen integration than vdom. Maybe faster too if we can take advantage of properties that vdom can't assume.

**Comment by garyb** [comment]
This now exists in https://github.com/slamdata/purescript-halogen-vdom, although we've not made a driver for it yet.
