### ISSUE TITLE
Case consistency for events

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#74]
In `Halogen.HTML.Events` the event names are all lowercase, `onclick`, `onmouseover` and so on, in `Halogen.HTML.Events.Forms` they are camel case, `onInput`, `onValueChanged`, etc. I guess we should make these all consistent. Personally I much prefer the camelcase versions.

Any thoughts before I open a PR for this?

**Comment by jdegoes** [comment]
:+1:  Preference for camel case since that's the default in PureScript and the consistency with how they are named in JS doesn't matter all that much to me.

**Comment by paf31** [comment]
Camel case sounds good to me. I named them after the HTML attributes originally, but now they use hooks, so this makes sense.

It's a breaking change though, which is a bit of a shame.
