### ISSUE TITLE
Undo/redo mixin

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#8]
I realized that the `SF` model gives us a neat way to talk about undo/redo:

```purescript
data UndoRedo input = Undo | Redo | Other input

withUndo :: forall i o. SF i o -> SF (UndoRedo i) o
```

where the `SF` on the right hides a stack of `o`s.

@jdegoes You mentioned this as a use case at one point, right? Would you be interested in adding this as a module?

**Comment by jdegoes** [comment]
Yeah, that sounds good. Undo / redo and application persistence would be quite nice.
