### ISSUE TITLE
Finalizer and Initializer elements

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#85]
Is there a way to get a target element in initializer?

**Comment by paf31** [comment]
No, but I think it's simple to add that. What do you need it for out of curiosity?

**Comment by cryogenian** [comment]
Those bootstrap `tooltip` and other third-party things (i.e. zeroclipboard)

**Comment by paf31** [comment]
I'm generally not a fan of accessing DOM nodes in event handlers since we don't have a good way to ensure that access is read-only right now, but I guess we don't have a good alternative :(
