### ISSUE TITLE
Emit input signals from initializer 

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#87]
https://gist.github.com/cryogenian/5821dbed7f910194796a

This is slightly modified counter example. I've used **0.5** branch. 

* It compiles, but for every initializer that hasn't last sentence empty it produces unhandled error.
* Initializers don't send any messages to `update` function. It starts with `0` and after it reaches `6` there is no jump to `7`.

**Comment by paf31** [comment]
What is the unhandled error?

**Comment by paf31** [comment]
Also, you're using `yield` incorrectly. `yield` is basically just `pure` because of the way `Event` uses `ListT`. I should probably remove it, since the name is confusing.

**Comment by cryogenian** [comment]
> Uncaught error in asynchronous code: Failed pattern match

So, is there no way to emit two messages from event handler and event monad? only one or zero?

**Comment by paf31** [comment]
No you can: ```yield a `andThen` yield b```

**Comment by cryogenian** [comment]
ok, good to know

**Comment by paf31** [comment]
The pattern match failure is a problem though. Are you able to figure out where it happened?

**Comment by cryogenian** [comment]
Nope, there is lot of `Aff` code, one `hook` and `createElement` in stack. But no any place with `throw new Exception()` :disappointed: 
I suggest that it is in the `runEvent` but I'm not sure

**Comment by paf31** [comment]
The issue is here:

https://github.com/slamdata/purescript-halogen/blob/master/src/Halogen.purs#L110

**Comment by paf31** [comment]
Basically, I think you're trying to cause a rerender during the initial `createElement`, and the node hasn't been created yet. I didn't think this was possible, but there you go. Never use a partial function, I guess.

**Comment by cryogenian** [comment]
Huh 0_o

**Comment by cryogenian** [comment]
Maybe it's possible to decouple message queue and rerender queue.

**Comment by jdegoes** [comment]
We should find some way of solving this that is "safe by construction".
