### ISSUE TITLE
Additional installation/getting started notes

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#91]
- [x] Note that `virtual-dom` must be installed separately via `npm` or whatever
- [x] Either break `purescript-halogen-bootstrap` and `purescript-halogen-foundation` out into their own projects, or mention about modifiying the standard classpath from `bower_components/purescript-*/**/*.purs` to include them when running examples, etc.

**Comment by jdegoes** [comment]
1. Can vdom just be listed as a dep in bower?
2. Breaking things out probably makes more sense, I'm happy to create repos here if that's the consensus.

**Comment by garyb** [comment]
1. It doesn't seem to be listed there unfortunately - perhaps because it's CommonJS, so needs something like Browserify to package it up for the web, and Browserify has special handling of `node_modules`.
2. I think breaking them out is the way to go too, for one I don't think you can use `pulp` to build things with the current folder structure.

These are both things I saw mentioned on IRC, that a PureScript beginner struggled with but eventually fought through.

**Comment by jdegoes** [comment]
1. Bower can pull from any repo, though, and there are release tags on the Github repo for virtualdom.
2. OK, will create two packages: purescript-halogen-bootstrap, purescript-halogen-foundation.

**Comment by paf31** [comment]
I've moved code over to the new repos.

**Comment by paf31** [comment]
I added some notes about `virtual-dom` in the readme file. I recommended `npm` for now, since `browserify` needs code to be in `node_modules`. We could change over if we move to the version of `virtual-dom` which doesn't use `require`.
