### ISSUE TITLE
Make `type` type safe?

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#93]
I started working on this, adding a sum type that covers all the valid `type` attributes for `input`, but then I realised that isn't really going to work unfortunately, as the `type` attribute is also usable with `button`, `command`, `embed`, `object`, `script`, etc.

Do we have any ideas for how something like this might work? Or is it not really worth the pain to make a "truly" type safe representation of HTML?

**Comment by jdegoes** [comment]
I think there are lots of ways to make this work, what's the goal? A single `type` attribute which can cover all possible "types" of types (input, script, object, etc.)?

**Comment by garyb** [comment]
I guess ideally there would be different `type`s - one covering everything would be a bit strange as you'd have mime types (for `script`) mixed in with `checkbox` and the like for `input`.

**Comment by garyb** [comment]
Well, not full mime types exactly, but you know - `text/css`, `javascript`, and so on.

**Comment by puffnfresh** [comment]
We should use different functions for each of these cases. We could possibly use a mutli-param type-class but that would be gross.

**Comment by jdegoes** [comment]
> We should use different functions for each of these cases. 

Yeah, `mimeType`, `inputType`, etc. Doesn't have to match HTML naming convention exactly.

**Comment by jonsterling** [comment]
Resolved by #172
