### ISSUE TITLE
Remove Component API?

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#99]
This has been mentioned a few times, so I'll put this issue here so that we can discuss it properly.

Most applications I've seen (other than the Ace example) use one large component, and other techniques (`Inject1`...) to deal with large sum types. Maybe `Component` is not worth the drop in composability?

**Comment by garyb** [comment]
To be honest, I couldn't figure out how `install` was supposed to work, that's part of the reason I ended up with the `Inject1` stuff. I still wonder if maybe it would be cleaner than the inject approach...

Since I haven't taken advantage of components right now, I'm fine with getting rid of them, but I feel I should at least make another attempt at figuring out how the composition of them *should* work.

**Comment by paf31** [comment]
The idea with `install` is to replace an existing placeholder with another `Component`. On the `HTML` level, the corresponding thing (`graft`) is monadic:

```purescript
graft :: forall a b res. HTML a res -> HTML (a -> HTML b res) -> HTML b res
```

grafting trees onto leaves (placeholders) of the tree. But with `Component`, we can't do that, because the existentially-chosen type in `HTML b res` on the right of the inner function arrow _depends on_ the value of type `a`. That is, we need dependent types to properly describe the internal message type of the result.

So, instead, we treat the placeholder type like a finite sum, using `Maybe a` to represent "one more value than `a`". When you graft, you use up one position, so `Maybe a` becomes `a`.

This works fine for static, finite things, but won't work if you want to install a list of components. In that case, you will probably have to use `runComponent` manually, or use `combine` with a fold, essentially creating a data structure from nested `Either`s.

**Comment by paf31** [comment]
@cryogenian What is your experience with components so far?

**Comment by cryogenian** [comment]
I haven't use them. But I will if I start project using halogen. At least will try :smile:

**Comment by puffnfresh** [comment]
I managed to use `install` today. I took me all morning to get things to line up:

https://github.com/slamdata/slamdata/pull/67
